/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 24369ab9-ebfd-46ca-ba0f-405967a5046c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of Corollary D.3 from the paper, proving the unconditional convergence of the per-site NLL for a deterministic Cellular Automaton on a finite spatial domain. The proof leverages the eventual periodicity of the CA trajectory to show that orbit class frequencies and thus the NLL stabilize over time.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The trajectory of a CA given a rule and an initial configuration.
-/
def CA_trajectory {S : Type} (rule : (S → Bool) → (S → Bool)) (init : S → Bool) : ℕ → S → Bool
| 0 => init
| n + 1 => rule (CA_trajectory rule init n)

/-
A candidate model is defined by a temporal period `p` and a partition of `Fin p × S` into `k` orbit classes.
-/
structure CandidateModel (S : Type) [Fintype S] where
  p : ℕ
  hp : p > 0
  k : ℕ
  class_id : Fin p × S → Fin k

/-
Extend the class_id to all time steps using periodicity.
-/
def orbit_class {S : Type} [Fintype S] (model : CandidateModel S) (t : ℕ) (x : S) : Fin model.k :=
  model.class_id ⟨⟨t % model.p, Nat.mod_lt _ model.hp⟩, x⟩

/-
Count of sites in orbit class j up to time T.
-/
noncomputable def count_class {S : Type} [Fintype S] (model : CandidateModel S) (T : ℕ) (j : Fin model.k) : ℝ :=
  (Finset.filter (fun (tx : Fin T × S) => orbit_class model tx.1 tx.2 = j) Finset.univ).card

/-
Count of 1s in orbit class j up to time T for a given trajectory.
-/
noncomputable def count_ones {S : Type} [Fintype S] (model : CandidateModel S) (traj : ℕ → S → Bool) (T : ℕ) (j : Fin model.k) : ℝ :=
  (Finset.filter (fun (tx : Fin T × S) => orbit_class model tx.1 tx.2 = j ∧ traj tx.1 tx.2 = true) Finset.univ).card

/-
Empirical frequency of 1s in orbit class j.
-/
noncomputable def theta_hat {S : Type} [Fintype S] (model : CandidateModel S) (traj : ℕ → S → Bool) (T : ℕ) (j : Fin model.k) : ℝ :=
  if count_class model T j = 0 then 0 else count_ones model traj T j / count_class model T j

/-
Check if Real.binEntropy is available.
-/
#check Real.binEntropy

/-
The NLL per site is the sum of the entropy of each orbit class weighted by its size, divided by the total number of sites.
-/
noncomputable def NLL_per_site {S : Type} [Fintype S] (model : CandidateModel S) (traj : ℕ → S → Bool) (T : ℕ) : ℝ :=
  (∑ j : Fin model.k, count_class model T j * Real.binEntropy (theta_hat model traj T j)) / (T * Fintype.card S)

/-
The trajectory of a deterministic CA on a finite domain is eventually periodic.
-/
def EventuallyPeriodic {α : Type} (f : ℕ → α) : Prop :=
  ∃ T p, p > 0 ∧ ∀ t ≥ T, f (t + p) = f t

lemma CA_eventually_periodic {S : Type} [Fintype S] (rule : (S → Bool) → (S → Bool)) (init : S → Bool) :
  EventuallyPeriodic (CA_trajectory rule init) := by
  -- By definition of periodicity, there exists some $N$ such that for all $n \geq N$, $CA\_trajectory rule init (n + p) = CA\_trajectory rule init n$.
  obtain ⟨n, m, hnm, h_eq⟩ : ∃ n m, n < m ∧ CA_trajectory rule init n = CA_trajectory rule init m := by
    by_contra h;
    exact absurd ( Set.infinite_range_of_injective ( fun n m hnm => le_antisymm ( not_lt.1 fun hnm' => h ⟨ m, n, hnm', hnm.symm ⟩ ) ( not_lt.1 fun hnm' => h ⟨ n, m, hnm', hnm ⟩ ) ) ) ( Set.not_infinite.mpr <| Set.toFinite _ );
  use n, m - n, Nat.sub_pos_of_lt hnm, ?_;
  intro t ht; induction ht <;> simp_all +decide [ ← add_assoc, Nat.succ_add, le_of_lt ] ;
  rw [ Nat.add_succ, Nat.add_succ, CA_trajectory ] ; aesop;

/-
If a sequence is eventually periodic, its Cesaro mean converges.
-/
lemma avg_converges_of_eventually_periodic (f : ℕ → ℝ) (h : EventuallyPeriodic f) :
  ∃ L, Filter.Tendsto (fun T => (∑ t ∈ Finset.range T, f t) / T) Filter.atTop (nhds L) := by
  -- Since the sequence is eventually periodic with period $p$, for $T > T0$, the sum $\sum_{t < T} f(t)$ can be written as $\sum_{t < T0} f(t) + k \sum_{t=0}^{p-1} f(t) + \sum_{t=0}^{r-1} f(t)$, where $0 \leq r < p$.
  obtain ⟨T0, p, hp_pos, hp_period⟩ := h
  have h_decomp : ∀ T ≥ T0, ∑ t ∈ Finset.range T, f t = ∑ t ∈ Finset.range T0, f t + (∑ t ∈ Finset.range (p * ((T - T0) / p)), f (T0 + t)) + (∑ t ∈ Finset.range ((T - T0) % p), f (T0 + p * ((T - T0) / p) + t)) := by
    intro T hT
    have h_decomp : ∑ t ∈ Finset.range T, f t = ∑ t ∈ Finset.range T0, f t + ∑ t ∈ Finset.range (T - T0), f (T0 + t) := by
      rw [ ← Finset.sum_range_add, add_tsub_cancel_of_le hT ];
    rw [ h_decomp, add_assoc, ← Finset.sum_range_add_sum_Ico _ ( show p * ( ( T - T0 ) / p ) ≤ T - T0 from Nat.mul_div_le _ _ ) ];
    rw [ Finset.sum_Ico_eq_sum_range ] ; simp +decide [ add_assoc, Nat.mod_add_div ] ; ring;
    rw [ Nat.sub_eq_of_eq_add ] ; linarith [ Nat.mod_add_div ( T - T0 ) p ];
  -- The sum $\sum_{t=0}^{p-1} f(T0 + t)$ is constant, and the sum $\sum_{t=0}^{r-1} f(T0 + p * ((T - T0) / p) + t)$ is bounded.
  have h_const_bounded : ∃ C B : ℝ, ∀ T ≥ T0, |∑ t ∈ Finset.range (p * ((T - T0) / p)), f (T0 + t) - ((T - T0) / p : ℝ) * ∑ t ∈ Finset.range p, f (T0 + t)| ≤ C ∧ |∑ t ∈ Finset.range ((T - T0) % p), f (T0 + p * ((T - T0) / p) + t)| ≤ B := by
    -- The sum $\sum_{t=0}^{p-1} f(T0 + t)$ is constant, and the sum $\sum_{t=0}^{r-1} f(T0 + p * ((T - T0) / p) + t)$ is bounded by the maximum absolute value of $f$ over one period.
    obtain ⟨C, hC⟩ : ∃ C : ℝ, ∀ T ≥ T0, |∑ t ∈ Finset.range (p * ((T - T0) / p)), f (T0 + t) - ((T - T0) / p : ℝ) * ∑ t ∈ Finset.range p, f (T0 + t)| ≤ C := by
      -- The sum $\sum_{t=0}^{p-1} f(T0 + t)$ is constant, and the sum $\sum_{t=0}^{r-1} f(T0 + p * ((T - T0) / p) + t)$ is bounded by the maximum absolute value of $f$ over one period. Use this fact.
      have h_const_bounded : ∀ k : ℕ, ∑ t ∈ Finset.range (p * k), f (T0 + t) = k * ∑ t ∈ Finset.range p, f (T0 + t) := by
        intro k; induction k <;> simp_all +decide [ Nat.mul_succ, Finset.sum_range_add ] ; ring;
        congr! 2;
        rename_i k hk;
        rename_i n ih; rw [ show T0 + p * n + k = T0 + k + p * n by ring ] ; exact Nat.recOn n ( by norm_num ) fun n ihn => by rw [ Nat.mul_succ, ← add_assoc, hp_period _ ( by nlinarith [ Finset.mem_range.mp hk ] ) ] ; exact ihn;
      use |∑ t ∈ Finset.range p, f (T0 + t)| + 1;
      intro T hT; rw [ h_const_bounded ] ; ring_nf ;
      field_simp;
      rw [ abs_div, abs_mul, abs_of_nonneg ( by positivity : ( 0 : ℝ ) ≤ p ) ];
      rw [ div_le_iff₀ ( by positivity ) ];
      refine' le_trans ( mul_le_mul_of_nonneg_left ( show |(↑((T - T0) / p) : ℝ) * (↑p : ℝ) - (↑T : ℝ) + (↑T0 : ℝ)| ≤ p by rw [ abs_le ] ; constructor <;> nlinarith [ show ( T - T0 : ℝ ) ≥ ↑ ( ( T - T0 ) / p ) * p by exact_mod_cast Nat.div_mul_le_self _ _, show ( T - T0 : ℝ ) < ↑ ( ( T - T0 ) / p ) * p + p by exact_mod_cast by linarith [ Nat.div_add_mod ( T - T0 ) p, Nat.mod_lt ( T - T0 ) hp_pos ], show ( T : ℝ ) ≥ T0 by exact_mod_cast hT ] ) ( abs_nonneg _ ) ) _ ; nlinarith [ abs_nonneg ( ∑ x ∈ Finset.range p, f ( T0 + x ) ) ];
    use C, ∑ t ∈ Finset.range p, |f (T0 + t)|;
    intro T hT; refine ⟨ hC T hT, ?_ ⟩ ; refine' le_trans ( Finset.abs_sum_le_sum_abs _ _ ) _ ; refine' le_trans ( Finset.sum_le_sum_of_subset_of_nonneg ( Finset.range_mono <| Nat.mod_lt _ hp_pos |> Nat.le_of_lt ) fun _ _ _ => abs_nonneg _ ) _ ; simp +decide [ add_assoc, hp_period ] ;
    exact Finset.sum_le_sum fun i hi => by rw [ show T0 + ( p * ( ( T - T0 ) / p ) + i ) = T0 + i + p * ( ( T - T0 ) / p ) by ring ] ; exact Nat.recOn ( ( T - T0 ) / p ) ( by norm_num ) fun n ihn => by rw [ Nat.mul_succ, ← add_assoc, hp_period _ ( by nlinarith [ Finset.mem_range.mp hi ] ) ] ; simpa [ add_assoc ] using ihn;
  -- Using the decomposition and boundedness, we can show that the limit of the Cesaro mean exists.
  obtain ⟨C, B, hC⟩ := h_const_bounded;
  have h_limit : Filter.Tendsto (fun T : ℕ => ((∑ t ∈ Finset.range T0, f t) + ((T - T0) / p : ℝ) * ∑ t ∈ Finset.range p, f (T0 + t)) / (T : ℝ)) Filter.atTop (nhds ((∑ t ∈ Finset.range p, f (T0 + t)) / p)) := by
    -- We can factor out $1/T$ and use the fact that $(T - T0) / T$ tends to $1$ as $T$ tends to infinity.
    have h_factor : Filter.Tendsto (fun T : ℕ => ((T - T0) / p : ℝ) / T) Filter.atTop (nhds (1 / p)) := by
      ring_nf;
      exact le_trans ( Filter.Tendsto.sub ( tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with T hT; rw [ mul_right_comm, mul_inv_cancel₀ ( Nat.cast_ne_zero.mpr hT ), one_mul ] ) ) ( tendsto_const_nhds.mul tendsto_inverse_atTop_nhds_zero_nat ) ) ( by norm_num );
    convert h_factor.mul_const ( ∑ t ∈ Finset.range p, f ( T0 + t ) ) |> Filter.Tendsto.add <| tendsto_const_nhds.mul tendsto_inverse_atTop_nhds_zero_nat using 2 <;> ring;
  -- Using the decomposition and boundedness, we can show that the limit of the Cesaro mean exists by the squeeze theorem.
  have h_squeeze : Filter.Tendsto (fun T : ℕ => ((∑ t ∈ Finset.range T0, f t) + ((T - T0) / p : ℝ) * ∑ t ∈ Finset.range p, f (T0 + t) + (∑ t ∈ Finset.range (p * ((T - T0) / p)), f (T0 + t) - ((T - T0) / p : ℝ) * ∑ t ∈ Finset.range p, f (T0 + t)) + (∑ t ∈ Finset.range ((T - T0) % p), f (T0 + p * ((T - T0) / p) + t))) / (T : ℝ)) Filter.atTop (nhds ((∑ t ∈ Finset.range p, f (T0 + t)) / p)) := by
    have h_squeeze : Filter.Tendsto (fun T : ℕ => ((∑ t ∈ Finset.range (p * ((T - T0) / p)), f (T0 + t) - ((T - T0) / p : ℝ) * ∑ t ∈ Finset.range p, f (T0 + t)) + (∑ t ∈ Finset.range ((T - T0) % p), f (T0 + p * ((T - T0) / p) + t))) / (T : ℝ)) Filter.atTop (nhds 0) := by
      refine' squeeze_zero_norm' _ _;
      use fun T => ( C + B ) / T;
      · filter_upwards [ Filter.eventually_ge_atTop T0 ] with T hT using by rw [ Real.norm_eq_abs, abs_div, abs_of_nonneg ( by positivity : ( 0 : ℝ ) ≤ T ) ] ; exact div_le_div_of_nonneg_right ( abs_le.mpr ⟨ by linarith [ abs_le.mp ( hC T hT |>.1 ), abs_le.mp ( hC T hT |>.2 ) ], by linarith [ abs_le.mp ( hC T hT |>.1 ), abs_le.mp ( hC T hT |>.2 ) ] ⟩ ) ( by positivity ) ;
      · exact tendsto_const_nhds.div_atTop tendsto_natCast_atTop_atTop;
    convert h_limit.add h_squeeze using 2 <;> ring;
  exact ⟨ _, h_squeeze.congr' <| by filter_upwards [ Filter.eventually_ge_atTop T0 ] with T hT using by rw [ h_decomp T hT ] ; ring ⟩

/-
Count of sites in orbit class j at time t.
-/
noncomputable def count_class_at_t {S : Type} [Fintype S] (model : CandidateModel S) (j : Fin model.k) (t : ℕ) : ℝ :=
  (Finset.filter (fun x => orbit_class model t x = j) Finset.univ).card

/-
Count of 1s in orbit class j at time t.
-/
noncomputable def count_ones_at_t {S : Type} [Fintype S] (model : CandidateModel S) (traj : ℕ → S → Bool) (j : Fin model.k) (t : ℕ) : ℝ :=
  (Finset.filter (fun x => orbit_class model t x = j ∧ traj t x = true) Finset.univ).card

/-
The count of sites in an orbit class is periodic.
-/
lemma count_class_periodic {S : Type} [Fintype S] (model : CandidateModel S) (j : Fin model.k) :
  EventuallyPeriodic (count_class_at_t model j) := by
  use 0, model.p, model.hp, by
    unfold count_class_at_t orbit_class; aesop;;

/-
The count of 1s in an orbit class is eventually periodic.
-/
lemma count_ones_eventually_periodic {S : Type} [Fintype S] (model : CandidateModel S) (rule : (S → Bool) → (S → Bool)) (init : S → Bool) (j : Fin model.k) :
  EventuallyPeriodic (count_ones_at_t model (CA_trajectory rule init) j) := by
  obtain ⟨ T, p, hp, h ⟩ := CA_eventually_periodic rule init;
  use T, p * model.p;
  -- By definition of `count_ones_at_t`, we need to show that the number of 1s in orbit class j at time `t + p * model.p` is the same as at time `t`.
  have h_count_eq : ∀ t ≥ T, ∀ x : S, (CA_trajectory rule init (t + p * model.p) x = true) ↔ (CA_trajectory rule init t x = true) := by
    intro t ht x; rw [ show t + p * model.p = t + p * model.p from rfl, show CA_trajectory rule init ( t + p * model.p ) = CA_trajectory rule init t from Nat.recOn model.p ( by norm_num ) fun n ihn => by rw [ Nat.mul_succ, ← add_assoc, h _ ( by nlinarith ), ihn ] ] ;
  refine' ⟨ Nat.mul_pos hp model.hp, fun t ht => _ ⟩;
  unfold count_ones_at_t;
  unfold orbit_class; simp +decide [ *, Nat.add_mod, Nat.mod_eq_of_lt model.hp ] ;

/-
The cumulative count of sites in an orbit class is the sum of the per-time-step counts.
-/
lemma count_class_eq_sum {S : Type} [Fintype S] (model : CandidateModel S) (T : ℕ) (j : Fin model.k) :
  count_class model T j = ∑ t ∈ Finset.range T, count_class_at_t model j t := by
  unfold count_class count_class_at_t;
  simp +decide only [Finset.card_filter];
  erw [ Finset.sum_product ] ; norm_num [ Finset.sum_range ]

/-
The cumulative count of 1s in an orbit class is the sum of the per-time-step counts.
-/
lemma count_ones_eq_sum {S : Type} [Fintype S] (model : CandidateModel S) (traj : ℕ → S → Bool) (T : ℕ) (j : Fin model.k) :
  count_ones model traj T j = ∑ t ∈ Finset.range T, count_ones_at_t model traj j t := by
  unfold count_ones count_ones_at_t;
  simp +decide only [Finset.card_filter];
  erw [ Finset.sum_product ] ; norm_cast ; simp +decide [ Finset.sum_range ] ;

/-
The average count of sites in an orbit class converges.
-/
lemma count_class_converges {S : Type} [Fintype S] (model : CandidateModel S) (j : Fin model.k) :
  ∃ L, Filter.Tendsto (fun T => count_class model T j / T) Filter.atTop (nhds L) := by
  convert avg_converges_of_eventually_periodic ( fun T => count_class_at_t model j T ) ( count_class_periodic model j ) using 1;
  simp +decide only [count_class_eq_sum]

/-
The average count of 1s in an orbit class converges.
-/
lemma count_ones_converges {S : Type} [Fintype S] (model : CandidateModel S) (rule : (S → Bool) → (S → Bool)) (init : S → Bool) (j : Fin model.k) :
  ∃ L, Filter.Tendsto (fun T => count_ones model (CA_trajectory rule init) T j / T) Filter.atTop (nhds L) := by
  convert avg_converges_of_eventually_periodic ( fun T => count_ones_at_t model ( CA_trajectory rule init ) j T ) _;
  · exact?;
  · exact?

/-
The NLL term for a single orbit class converges.
-/
lemma term_converges {S : Type} [Fintype S] (model : CandidateModel S) (rule : (S → Bool) → (S → Bool)) (init : S → Bool) (j : Fin model.k) :
  ∃ L, Filter.Tendsto (fun T => (count_class model T j / T) * Real.binEntropy (theta_hat model (CA_trajectory rule init) T j)) Filter.atTop (nhds L) := by
  -- By definition of $c_T$ and $o_T$, we know that $c_T \to c$ and $o_T \to o$ for some $c, o$.
  obtain ⟨c, hc⟩ : ∃ c, Filter.Tendsto (fun T => count_class model T j / T) Filter.atTop (nhds c) := by
    exact count_class_converges model j
  obtain ⟨o, ho⟩ : ∃ o, Filter.Tendsto (fun T => count_ones model (CA_trajectory rule init) T j / T) Filter.atTop (nhds o) := by
    exact?;
  by_cases hc0 : c = 0;
  · -- Since $c = 0$, we have $\theta_hat \to 0$ as well.
    have h_theta_hat_zero : ∀ T, theta_hat model (CA_trajectory rule init) T j ∈ Set.Icc 0 1 := by
      intro T
      unfold theta_hat
      simp [count_class, count_ones];
      split_ifs <;> norm_num;
      exact ⟨ div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ), div_le_one_of_le₀ ( mod_cast Finset.card_mono <| fun x hx => by aesop ) ( Nat.cast_nonneg _ ) ⟩;
    -- Since $c = 0$, we have $\binEntropy(\theta_hat) \leq \binEntropy(1/2) = \log 2$.
    have h_binEntropy_bound : ∀ T, Real.binEntropy (theta_hat model (CA_trajectory rule init) T j) ≤ Real.log 2 := by
      exact?;
    exact ⟨ _, squeeze_zero ( fun T => mul_nonneg ( div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( Real.binEntropy_nonneg ( h_theta_hat_zero T |>.1 ) ( h_theta_hat_zero T |>.2 ) ) ) ( fun T => mul_le_mul_of_nonneg_left ( h_binEntropy_bound T ) ( div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ) ( by simpa [ hc0 ] using hc.mul_const ( Real.log 2 ) ) ⟩;
  · have h_theta_hat : Filter.Tendsto (fun T => theta_hat model (CA_trajectory rule init) T j) Filter.atTop (nhds (o / c)) := by
      refine' Filter.Tendsto.congr' _ ( ho.div hc hc0 );
      filter_upwards [ hc.eventually_ne hc0 ] with T hT ; unfold theta_hat ; by_cases hT' : ( Finset.filter ( fun x : Fin T × S => orbit_class model x.1 x.2 = j ) Finset.univ ).card = 0 <;> simp_all +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ] ;
    have h_binEntropy_cont : ContinuousAt Real.binEntropy (o / c) := by
      fun_prop;
    exact ⟨ _, Filter.Tendsto.mul hc ( h_binEntropy_cont.tendsto.comp h_theta_hat ) ⟩

/-
For a deterministic CA on a finite spatial domain, the per-site NLL converges unconditionally.
-/
theorem corollary_d3 {S : Type} [Fintype S] (rule : (S → Bool) → (S → Bool)) (init : S → Bool) (model : CandidateModel S) :
  ∃ limit_val : ℝ, Filter.Tendsto (fun T => NLL_per_site model (CA_trajectory rule init) T) Filter.atTop (nhds limit_val) := by
  -- By lemma `term_converges`, for each orbit class `j`, the term `(count_class model T j / T) * Real.binEntropy (theta_hat model (CA_trajectory rule init) T j)` converges.
  have h_term_converge : ∀ j, ∃ L, Filter.Tendsto (fun T => (count_class model T j / T) * Real.binEntropy (theta_hat model (CA_trajectory rule init) T j)) Filter.atTop (nhds L) := by
    exact?;
  choose L hL using h_term_converge;
  -- The NLL per site is `(1 / |S|) * ∑ j, (count_class model T j / T) * Real.binEntropy (theta_hat model traj T j)`.
  use (∑ j : Fin model.k, L j) / (Fintype.card S : ℝ);
  convert Filter.Tendsto.div_const ( tendsto_finset_sum _ fun j _ => hL j ) ( Fintype.card S : ℝ ) using 2 ; unfold NLL_per_site ; ring;
  simp +decide only [mul_comm, Finset.mul_sum _ _ _, mul_left_comm, mul_assoc]

