/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).
Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: a90ef93b-293b-4df7-91e3-8c6d731daa67
To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/
/-
Formalization of Theorem 5 from the attached paper, covering parts (i) through (iv) regarding identifiability for eventually exactly periodic backgrounds. The proofs rely on the provided lemmas and theorems which are assumed to be true.
-/
/-
Formalization and proof of Theorem 5 from the paper, establishing identifiability for eventually exactly periodic backgrounds.
The theorem is broken down into four parts:
(i) `theorem_5_i_proved`: The per-site NLL rates are equal to 0.
(ii) `theorem_5_ii`: The NLL difference NLL(p, T) - NLL(p0, T) is bounded by a constant (O(1)).
(iii) `theorem_5_iii`: The NML score difference grows logarithmically with T, specifically as (m-1) * k_p0 / 2 * log2(T) + O(1).
(iv) `theorem_5_iv`: The NML criterion eventually selects the true period p0 over the multiple p = m*p0.
Helper lemmas include asymptotic bounds for entropy and complexity, and consistency of orbit projections.
-/
import Mathlib
set_option linter.mathlibStandardSet false
open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise
set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128
set_option relaxedAutoImplicit false
set_option autoImplicit false
noncomputable section
/-
Definitions of Spacetime and binary entropy h_b.
-/
def Spacetime (X : Type*) := ℕ → X → Bool
noncomputable def h_b (theta : Real) : Real :=
  if theta = 0 ∨ theta = 1 then 0 else - theta * Real.logb 2 theta - (1 - theta) * Real.logb 2 (1 - theta)
/-
Definitions of orbitIndex, count_in_class, NLL, and NML.
-/
variable {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
/-- The orbit index maps a spacetime point (t, x) to its canonical representative in the fundamental domain. -/
def orbitIndex (p : ℕ) (s : X) (t : ℕ) (x : X) (hp : p > 0) : (Fin p) × X :=
  (⟨t % p, Nat.mod_lt _ hp⟩, x - (t / p) • s)
/-- Count total points and ones in a specific orbit class within the window [0, T). -/
def count_in_class (U : Spacetime X) (p : ℕ) (s : X) (T : ℕ) (idx : (Fin p) × X) (hp : p > 0) : ℕ × ℕ :=
  let total := (Finset.range T).sum (fun t => Finset.univ.filter (fun x => orbitIndex p s t x hp = idx) |>.card)
  let ones := (Finset.range T).sum (fun t => Finset.univ.filter (fun x => orbitIndex p s t x hp = idx ∧ U t x = true) |>.card)
  (total, ones)
/-- Negative Log Likelihood. -/
noncomputable def NLL (U : Spacetime X) (p : ℕ) (s : X) (T : ℕ) (hp : p > 0) : Real :=
  Finset.univ.sum (fun (idx : (Fin p) × X) =>
    let (n, k) := count_in_class U p s T idx hp
    if n = 0 then 0 else
    let theta := (k : Real) / n
    n * h_b theta
  )
/-- Normalized Maximum Likelihood score. -/
noncomputable def NML (U : Spacetime X) (p : ℕ) (s : X) (T : ℕ) (hp : p > 0) : Real :=
  NLL U p s T hp + Finset.univ.sum (fun (idx : (Fin p) × X) =>
    let (n, _) := count_in_class U p s T idx hp
    if n = 0 then 0 else 0.5 * Real.logb 2 n
  )
/-
Definition of EventuallyPeriodic.
-/
/-- Definition of eventually exactly periodic background. -/
def EventuallyPeriodic (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ) : Prop :=
  ∀ t ≥ T0, ∀ x, U (t + p) (x + s) = U t x
/-
orbitIndex is invariant under shifting by (p, s).
-/
lemma orbitIndex_add_period (p : ℕ) (s : X) (t : ℕ) (x : X) (hp : p > 0) :
  orbitIndex p s (t + p) (x + s) hp = orbitIndex p s t x hp := by
    unfold orbitIndex; simp +decide [ hp, Nat.add_mod ] ; ring;
    simp +decide [ add_smul, add_assoc, add_sub_assoc ];
    rw [ sub_eq_add_neg ]
/-
Lemma: If the number of minority symbols k is bounded, then the total entropy n * h_b(k/n) grows at most logarithmically with n.
-/
lemma entropy_bound_of_bounded_k (C : ℕ) :
  ∃ C' : ℝ, ∀ n : ℕ, n > 0 → ∀ k : ℕ, k ≤ C → k ≤ n →
  n * h_b (k / n) ≤ C' * Real.log (n + 1) + C' := by
    unfold h_b;
    -- For $0 < k < n$, we have $n * h_b(k/n) \leq n * (-k/n * \log(k/n) - (1 - k/n) * \log(1 - k/n))$.
    suffices h_cases : ∃ C', ∀ n > 0, ∀ k ≤ C, k ≤ n → k ≠ 0 → k ≠ n → n * (-((k : ℝ) / n) * Real.log ((k : ℝ) / n) - (1 - (k : ℝ) / n) * Real.log (1 - (k : ℝ) / n)) / Real.log 2 ≤ C' * Real.log (n + 1) + C' by
      simp_all +decide [ Real.logb ];
      obtain ⟨ C', hC' ⟩ := h_cases; use Max.max C' 1; intros n hn k hk₁ hk₂; split_ifs <;> simp_all +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ] ;
      · exact add_nonneg ( mul_nonneg ( le_max_of_le_right zero_le_one ) ( Real.log_nonneg ( by linarith ) ) ) ( le_max_of_le_right zero_le_one );
      · convert le_trans ( hC' n hn k hk₁ hk₂ ( by tauto ) ( by aesop ) ) ( add_le_add ( mul_le_mul_of_nonneg_right ( le_max_left _ _ ) ( Real.log_nonneg ( by norm_cast; linarith ) ) ) ( le_max_left _ _ ) ) using 1 ; ring;
    -- For $0 < k < n$, we have $n * (-((k : ℝ) / n) * Real.log ((k : ℝ) / n) - (1 - (k : ℝ) / n) * Real.log (1 - (k : ℝ) / n)) \leq n * (-(k/n) * \log(k/n)) + n * (-(1 - k/n) * \log(1 - k/n))$.
    suffices h_cases : ∃ C', ∀ n > 0, ∀ k ≤ C, k ≤ n → k ≠ 0 → k ≠ n → n * (-((k : ℝ) / n) * Real.log ((k : ℝ) / n)) / Real.log 2 ≤ C' * Real.log (n + 1) + C' by
      -- For $0 < k < n$, we have $n * (-(1 - k/n) * \log(1 - k/n)) \leq n * (-(1 - k/n) * \log(1 - k/n))$.
      suffices h_cases2 : ∃ C', ∀ n > 0, ∀ k ≤ C, k ≤ n → k ≠ 0 → k ≠ n → n * (-(1 - (k : ℝ) / n) * Real.log (1 - (k : ℝ) / n)) / Real.log 2 ≤ C' * Real.log (n + 1) + C' by
        obtain ⟨ C₁, hC₁ ⟩ := h_cases; obtain ⟨ C₂, hC₂ ⟩ := h_cases2; use C₁ + C₂; intros n hn k hk₁ hk₂ hk₃ hk₄; have := hC₁ n hn k hk₁ hk₂ hk₃ hk₄; have := hC₂ n hn k hk₁ hk₂ hk₃ hk₄; ring_nf at *; linarith;
      -- For $0 < k < n$, we have $n * (-(1 - k/n) * \log(1 - k/n)) \leq n * (-(1 - k/n) * \log(1 - k/n))$ and $n * (-(1 - k/n) * \log(1 - k/n)) \leq n * (-(1 - k/n) * \log(1 - k/n))$.
      have h_cases2 : ∃ C', ∀ n > 0, ∀ k ≤ C, k ≤ n → k ≠ 0 → k ≠ n → (1 - (k : ℝ) / n) * n * (-Real.log (1 - (k : ℝ) / n)) / Real.log 2 ≤ C' * Real.log (n + 1) + C' := by
        -- Since $k \leq C$, we have $1 - k/n \geq 1 - C/n$. For large $n$, this is close to $1$.
        have h_bound : ∃ C', ∀ n > 0, ∀ k ≤ C, k ≤ n → k ≠ 0 → k ≠ n → (1 - (k : ℝ) / n) * n * (-Real.log (1 - (k : ℝ) / n)) / Real.log 2 ≤ C' := by
          use ( C + 1 ) / Real.log 2;
          intros n hn k hk₁ hk₂ hk₃ hk₄
          have h_bound : (1 - (k : ℝ) / n) * n * (-Real.log (1 - (k : ℝ) / n)) ≤ (C + 1) := by
            have h_bound : (1 - (k : ℝ) / n) * n * (-Real.log (1 - (k : ℝ) / n)) ≤ (k : ℝ) := by
              have h_bound : ∀ x : ℝ, 0 < x ∧ x < 1 → (1 - x) * (-Real.log (1 - x)) ≤ x := by
                exact fun x hx => by nlinarith [ Real.log_inv ( 1 - x ), Real.log_le_sub_one_of_pos ( inv_pos.mpr ( by linarith : 0 < 1 - x ) ), mul_inv_cancel₀ ( by linarith : ( 1 - x ) ≠ 0 ) ] ;
              convert mul_le_mul_of_nonneg_right ( h_bound ( k / n ) ⟨ by exact div_pos ( Nat.cast_pos.mpr ( Nat.pos_of_ne_zero hk₃ ) ) ( Nat.cast_pos.mpr hn ), by exact div_lt_one ( Nat.cast_pos.mpr hn ) |>.2 ( Nat.cast_lt.mpr ( lt_of_le_of_ne hk₂ hk₄ ) ) ⟩ ) ( Nat.cast_nonneg n ) using 1 ; ring;
              rw [ div_mul_cancel₀ _ ( by positivity ) ];
            exact h_bound.trans ( by norm_cast; linarith );
          gcongr;
        obtain ⟨ C', hC' ⟩ := h_bound;
        use Max.max C' 1;
        exact fun n hn k hk₁ hk₂ hk₃ hk₄ => le_trans ( hC' n hn k hk₁ hk₂ hk₃ hk₄ ) ( by nlinarith [ le_max_left C' 1, le_max_right C' 1, Real.log_nonneg ( show ( n : ℝ ) + 1 ≥ 1 by linarith ) ] );
      exact ⟨ h_cases2.choose, fun n hn k hk₁ hk₂ hk₃ hk₄ => by convert h_cases2.choose_spec n hn k hk₁ hk₂ hk₃ hk₄ using 1 ; ring ⟩;
    -- For $0 < k < n$, we have $n * (-((k : ℝ) / n) * Real.log ((k : ℝ) / n)) \leq n * (-(k/n) * \log(k/n))$.
    suffices h_cases : ∃ C', ∀ n > 0, ∀ k ≤ C, k ≤ n → k ≠ 0 → k ≠ n → -((k : ℝ) * Real.log ((k : ℝ) / n)) / Real.log 2 ≤ C' * Real.log (n + 1) + C' by
      obtain ⟨ C', hC' ⟩ := h_cases; use C'; intros n hn k hk hk' hk'' hk'''; convert hC' n hn k hk hk' hk'' hk''' using 1; ring;
      simp +decide [ mul_assoc, mul_comm, mul_left_comm, hn.ne' ];
    -- For $0 < k < n$, we have $-((k : ℝ) * Real.log ((k : ℝ) / n)) \leq k * \log(n) + k * \log(k)$.
    suffices h_cases : ∃ C', ∀ n > 0, ∀ k ≤ C, k ≤ n → k ≠ 0 → k ≠ n → -((k : ℝ) * Real.log ((k : ℝ) / n)) ≤ C' * Real.log (n + 1) + C' by
      obtain ⟨ C', hC' ⟩ := h_cases; use C' / Real.log 2; intros n hn k hk₁ hk₂ hk₃ hk₄; rw [ div_le_iff₀ ( Real.log_pos one_lt_two ) ] ; convert hC' n hn k hk₁ hk₂ hk₃ hk₄ using 1 ; ring;
      norm_num [ mul_assoc ];
    use C + 1;
    intro n hn k hk₁ hk₂ hk₃ hk₄; rw [ Real.log_div ( by positivity ) ( by positivity ) ] ; ring_nf; (
    nlinarith [ show ( k : ℝ ) ≤ C by norm_cast, show ( k : ℝ ) ≤ n by norm_cast, show ( 0 : ℝ ) ≤ Real.log ( 1 + n ) by exact Real.log_nonneg ( by linarith ), show ( Real.log ( k : ℝ ) ) ≥ 0 by exact Real.log_nonneg ( Nat.one_le_cast.mpr ( Nat.pos_of_ne_zero hk₃ ) ), show ( Real.log ( n : ℝ ) ) ≤ Real.log ( 1 + n ) by exact Real.log_le_log ( by positivity ) ( by linarith ) ]);
/-
Lemma: If U is eventually periodic, then for any orbit class, the values U(t, x) are eventually constant.
-/
lemma values_eventually_constant_of_eventually_periodic {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ) (hp : p > 0)
  (h_eventual : EventuallyPeriodic U p s T0)
  (idx : (Fin p) × X) :
  ∃ c : Bool, ∃ T1 ≥ T0, ∀ t ≥ T1, ∀ x, orbitIndex p s t x hp = idx → U t x = c := by
    -- By definition of orbitIndex, for any t and x, orbitIndex p s t x hp = idx implies that t ≡ idx.1.val (mod p) and x = idx.2 + (t / p) • s.
    have h_orbit_index : ∀ t x, orbitIndex p s t x hp = idx → ∃ m : ℕ, t = idx.1.val + m * p ∧ x = idx.2 + m • s := by
      unfold orbitIndex;
      rintro t x rfl; use t / p; simp +decide [ mul_comm, ← add_assoc, Nat.div_add_mod ] ;
      rw [ Nat.mod_add_div ];
    obtain ⟨c, hc⟩ : ∃ c : Bool, ∀ m : ℕ, m ≥ T0 → U (idx.1.val + m * p) (idx.2 + m • s) = c := by
      use U (idx.1.val + T0 * p) (idx.2 + T0 • s);
      intro m hm; induction hm <;> simp_all +decide [ Nat.succ_mul, ← add_assoc ] ;
      have := h_eventual ( ( idx.1 : ℕ ) + ‹_› * p ) ( by nlinarith ) ( idx.2 + ‹_› • s ) ; simp_all +decide [ add_smul, add_assoc ] ;
    refine' ⟨ c, T0 * p + idx.1.val, _, _ ⟩;
    · nlinarith [ Fin.is_lt idx.1 ];
    · intro t ht x hx; obtain ⟨ m, rfl, rfl ⟩ := h_orbit_index t x hx; exact hc m ( by nlinarith ) ;
/-
Lemma: For a single orbit class in an eventually periodic spacetime, the number of minority symbols is bounded.
-/
lemma bounded_minority_in_single_class {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ) (hp : p > 0)
  (h_eventual : EventuallyPeriodic U p s T0)
  (idx : (Fin p) × X) :
  ∃ C : ℕ, ∀ T ≥ T0,
    let (n, k) := count_in_class U p s T idx hp
    min k (n - k) ≤ C := by
      -- By Lemma values_eventually_constant_of_eventually_periodic, there exists a constant $c$ and a time $T1 \geq T0$ such that for all $t \geq T1$ and $x$, $U(t, x) = c$ if $(t, x)$ is in the orbit class $idx$.
      obtain ⟨c, T1, hT1, hc⟩ : ∃ c : Bool, ∃ T1 ≥ T0, ∀ t ≥ T1, ∀ x, orbitIndex p s t x hp = idx → U t x = c := by
        exact?;
      -- Let's denote the number of minority symbols in the orbit class up to time $T$ as $k(T)$.
      set kT := fun T => (Finset.range T).sum (fun t => Finset.univ.filter (fun x => orbitIndex p s t x hp = idx ∧ U t x ≠ c) |>.card);
      -- Since $k(T)$ is the number of minority symbols in the orbit class up to time $T$, and $U$ is eventually periodic, $k(T)$ is bounded.
      have h_kT_bounded : ∃ C : ℕ, ∀ T ≥ T1, kT T ≤ C := by
        use kT T1;
        intro T hT; simp +decide only [kT] ; induction' hT with T hT ih <;> simp_all +decide [ Finset.sum_range_succ ] ;
        rw [ Finset.card_eq_zero.mpr ] <;> aesop;
      -- Since $k(T)$ is bounded, there exists a constant $C$ such that for all $T \geq T0$, $k(T) \leq C$.
      obtain ⟨C, hC⟩ : ∃ C : ℕ, ∀ T ≥ T0, kT T ≤ C := by
        exact ⟨ Max.max ( ∑ T ∈ Finset.range T1, Finset.card ( Finset.filter ( fun x => orbitIndex p s T x hp = idx ∧ U T x ≠ c ) Finset.univ ) ) h_kT_bounded.choose, fun T hT => if hT' : T < T1 then le_trans ( Finset.sum_le_sum_of_subset ( Finset.range_mono ( Nat.le_of_lt hT' ) ) ) ( le_max_left _ _ ) else le_trans ( h_kT_bounded.choose_spec T ( le_of_not_gt hT' ) ) ( le_max_right _ _ ) ⟩;
      refine' ⟨ C, fun T hT => _ ⟩ ; cases' eq_or_ne c Bool.true with hc hc <;> simp_all +decide [ count_in_class ] ;
      · refine' Or.inr ( le_trans _ ( add_le_add_right ( hC T hT ) _ ) );
        rw [ ← Finset.sum_add_distrib ] ; exact Finset.sum_le_sum fun t ht => by rw [ ← Finset.card_union_of_disjoint ( Finset.disjoint_filter.mpr fun _ _ _ => by aesop ) ] ; exact Finset.card_mono fun x hx => by by_cases hx' : U t x = Bool.true <;> aesop; ;
      · refine' Or.inl ( le_trans _ ( hC T hT ) ) ; aesop;
/-
Lemma: NLL grows at most logarithmically with T for an eventually periodic spacetime.
-/
lemma nll_growth_bound {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ) (hp : p > 0)
  (h_eventual : EventuallyPeriodic U p s T0) :
  ∃ C : ℝ, ∀ T ≥ T0, NLL U p s T hp ≤ C * Real.log (T + 1) + C := by
    -- Applying the entropy bound lemma to each orbit class.
    obtain ⟨C', hC'⟩ : ∃ C' : ℝ, ∀ (idx : (Fin p) × X), ∀ T ≥ T0, let (n, k) := count_in_class U p s T idx hp; n > 0 → n * h_b (k / n) ≤ C' * Real.log (T + 1) + C' := by
      have h_bound : ∀ (idx : (Fin p) × X), ∃ C : ℕ, ∀ T ≥ T0, let (n, k) := count_in_class U p s T idx hp; min k (n - k) ≤ C := by
        exact?;
      have h_entropy_bound : ∀ (idx : (Fin p) × X), ∃ C' : ℝ, ∀ (T : ℕ), T ≥ T0 → let (n, k) := count_in_class U p s T idx hp; n > 0 → n * h_b (k / n) ≤ C' * Real.log (n + 1) + C' := by
        intro idx
        obtain ⟨C, hC⟩ := h_bound idx
        obtain ⟨C', hC'⟩ := entropy_bound_of_bounded_k C
        use C';
        intro T hT hn_pos
        have hk_le_C : let (n, k) := count_in_class U p s T idx hp; k ≤ C ∨ n - k ≤ C := by
          exact?;
        cases' hk_le_C with hk_le_C hk_le_C;
        · convert hC' _ hn_pos _ hk_le_C _ using 1;
          exact Finset.sum_le_sum fun _ _ => Finset.card_mono fun x hx => by aesop;
        · convert hC' ( ∑ t ∈ Finset.range T, Finset.card ( Finset.filter ( fun x => orbitIndex p s t x hp = idx ) Finset.univ ) ) hn_pos ( ∑ t ∈ Finset.range T, Finset.card ( Finset.filter ( fun x => orbitIndex p s t x hp = idx ) Finset.univ ) - ∑ t ∈ Finset.range T, Finset.card ( Finset.filter ( fun x => orbitIndex p s t x hp = idx ∧ U t x = Bool.true ) Finset.univ ) ) hk_le_C ( Nat.sub_le _ _ ) using 1;
          rw [ Nat.cast_sub ];
          · unfold h_b; ring;
            by_cases h : ( ∑ t ∈ Finset.range T, Finset.card ( Finset.filter ( fun x => orbitIndex p s t x hp = idx ) Finset.univ ) : ℝ ) = 0 <;> simp_all +decide [ sub_eq_iff_eq_add ];
            split_ifs <;> ring;
            · grind +ring;
            · grind +ring;
          · exact Finset.sum_le_sum fun _ _ => Finset.card_mono fun x hx => by aesop;
      choose C' hC' using h_entropy_bound;
      -- Since $n \leq T$ for any $T \geq T0$, we can bound the logarithm term.
      have h_log_bound : ∀ (idx : (Fin p) × X), ∀ T ≥ T0, let (n, k) := count_in_class U p s T idx hp; n > 0 → Real.log (n + 1) ≤ Real.log (T + 1) := by
        intros idx T hT hn_pos
        have h_n_le_T : let (n, k) := count_in_class U p s T idx hp; n ≤ T := by
          -- Each term in the sum is at most 1, so the sum is at most T.
          have h_card_le_one : ∀ t ∈ Finset.range T, Finset.card (Finset.filter (fun x => orbitIndex p s t x hp = idx) Finset.univ) ≤ 1 := by
            intro t ht
            have h_unique : ∀ x y : X, orbitIndex p s t x hp = idx → orbitIndex p s t y hp = idx → x = y := by
              unfold orbitIndex; aesop;
            exact Finset.card_le_one.mpr fun x hx y hy => h_unique x y ( Finset.mem_filter.mp hx |>.2 ) ( Finset.mem_filter.mp hy |>.2 );
          exact le_trans ( Finset.sum_le_sum h_card_le_one ) ( by simp +decide );
        exact Real.log_le_log ( Nat.cast_add_one_pos _ ) ( mod_cast Nat.succ_le_succ h_n_le_T );
      use ∑ idx : Fin p × X, |C' idx| + ∑ idx : Fin p × X, |C' idx|;
      intro idx T hT hn; specialize hC' idx T hT hn; specialize h_log_bound idx T hT hn; simp_all +decide [ abs_le ] ;
      refine' le_trans hC' _;
      refine' add_le_add _ _;
      · refine' le_trans ( mul_le_mul_of_nonneg_right ( show C' idx ≤ ∑ idx : Fin p × X, |C' idx| by exact le_trans ( le_abs_self _ ) ( Finset.single_le_sum ( fun a _ => abs_nonneg ( C' a ) ) ( Finset.mem_univ idx ) ) ) ( Real.log_nonneg ( by linarith [ show ( ∑ x ∈ Finset.range T, ( Finset.card ( Finset.filter ( fun x_1 => orbitIndex p s x x_1 hp = idx ) Finset.univ ) : ℝ ) ) ≥ 0 by exact Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ] ) ) ) _;
        exact mul_le_mul ( le_add_of_nonneg_right <| Finset.sum_nonneg fun _ _ => abs_nonneg _ ) h_log_bound ( Real.log_nonneg <| by linarith [ show ( ∑ x ∈ Finset.range T, ( Finset.card ( Finset.filter ( fun x_1 => orbitIndex p s x x_1 hp = idx ) Finset.univ ) : ℝ ) ) ≥ 0 by exact Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ] ) ( add_nonneg ( Finset.sum_nonneg fun _ _ => abs_nonneg _ ) ( Finset.sum_nonneg fun _ _ => abs_nonneg _ ) );
      · exact le_add_of_le_of_nonneg ( le_trans ( le_abs_self _ ) ( Finset.single_le_sum ( fun a _ => abs_nonneg ( C' a ) ) ( Finset.mem_univ idx ) ) ) ( Finset.sum_nonneg fun _ _ => abs_nonneg _ );
    refine' ⟨ C' * Fintype.card ( Fin p × X ), fun T hT => _ ⟩;
    convert Finset.sum_le_sum fun idx _ => show ( let ( n, k ) := count_in_class U p s T idx hp; if n > 0 then n * h_b ( k / n ) else 0 ) ≤ C' * Real.log ( T + 1 ) + C' from ?_ using 1 <;> norm_num [ Finset.sum_add_distrib, Finset.mul_sum _ _ _ ] ; ring!;
    any_goals exact Finset.univ;
    · exact Finset.sum_congr rfl fun _ _ => by cases h : count_in_class U p s T ‹_› hp ; aesop;
    · simp +decide [ Finset.card_univ, mul_assoc, mul_comm, mul_left_comm ];
    · split_ifs <;> [ exact hC' idx T hT ‹_›; exact le_trans ( by norm_num ) ( add_nonneg ( mul_nonneg ( show 0 ≤ C' by
                                                                                                          contrapose! hC';
                                                                                                          refine' ⟨ idx, T0 + p, _, _, _ ⟩ <;> norm_num [ hp ];
                                                                                                          · refine' Nat.pos_of_ne_zero _ ; intro h ; simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg ] ; (
                                                                                                            unfold count_in_class at *; simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg ] ;
                                                                                                            specialize h ( idx.1.val ) ( by linarith [ Fin.is_lt idx.1 ] ) ; simp_all +decide [ orbitIndex ] ;
                                                                                                            simp_all +decide [ Nat.mod_eq_of_lt, Fin.is_lt ];
                                                                                                            simp_all +decide [ Nat.div_eq_of_lt, Fin.is_lt ];
                                                                                                            exact h rfl);
                                                                                                          · refine' lt_of_lt_of_le ( add_neg_of_nonpos_of_neg ( mul_nonpos_of_nonpos_of_nonneg hC'.le ( Real.log_nonneg ( by linarith ) ) ) hC' ) _;
                                                                                                            refine' mul_nonneg ( Nat.cast_nonneg _ ) _;
                                                                                                            unfold h_b; split_ifs <;> norm_num;
                                                                                                            rename_i h₁ h₂ h₃;
                                                                                                            refine' le_trans ( mul_nonpos_of_nonneg_of_nonpos _ _ ) _ <;> norm_num at *;
                                                                                                            · refine' div_le_one_of_le₀ _ _ <;> norm_cast <;> norm_num [ count_in_class ] at *;
                                                                                                              exact Finset.sum_le_sum fun _ _ => Finset.card_mono fun x hx => by aesop;
                                                                                                            · refine' Real.logb_nonpos ( by norm_num ) _ _ <;> norm_num at *;
                                                                                                              · refine' div_le_one_of_le₀ _ _ <;> norm_cast <;> norm_num [ count_in_class ] at *;
                                                                                                                exact Finset.sum_le_sum fun _ _ => Finset.card_mono fun x hx => by aesop;
                                                                                                              · positivity;
                                                                                                            · refine' mul_nonpos_of_nonneg_of_nonpos ( div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( Real.logb_nonpos ( by norm_num ) _ _ ) <;> norm_num [ h₃ ];
                                                                                                              · positivity;
                                                                                                              · refine' div_le_one_of_le₀ _ _ <;> norm_cast <;> simp_all +decide [ count_in_class ];
                                                                                                                exact Finset.sum_le_sum fun _ _ => Finset.card_mono fun x hx => by aesop; ) ( Real.log_nonneg ( by linarith ) ) ) ( show 0 ≤ C' by
                                                                                                                                                                          contrapose! hC';
                                                                                                                                                                          refine' ⟨ idx, T0 + p, _, _, _ ⟩ <;> norm_num [ hp ];
                                                                                                                                                                          · refine' Nat.pos_of_ne_zero _ ; intro h ; simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg ] ; (
                                                                                                                                                                            unfold count_in_class at *; simp_all +decide [ Finset.sum_eq_zero_iff_of_nonneg ] ;
                                                                                                                                                                            specialize h ( idx.1.val ) ( by linarith [ Fin.is_lt idx.1 ] ) ; simp_all +decide [ orbitIndex ] ;
                                                                                                                                                                            simp_all +decide [ Nat.mod_eq_of_lt, Fin.is_lt ];
                                                                                                                                                                            simp_all +decide [ Nat.div_eq_of_lt, Fin.is_lt ];
                                                                                                                                                                            exact h rfl);
                                                                                                                                                                          · refine' lt_of_lt_of_le ( add_neg_of_nonpos_of_neg ( mul_nonpos_of_nonpos_of_nonneg hC'.le ( Real.log_nonneg ( by linarith ) ) ) hC' ) _;
                                                                                                                                                                            refine' mul_nonneg ( Nat.cast_nonneg _ ) _;
                                                                                                                                                                            unfold h_b; split_ifs <;> norm_num;
                                                                                                                                                                            rename_i h₁ h₂ h₃;
                                                                                                                                                                            refine' le_trans ( mul_nonpos_of_nonneg_of_nonpos _ _ ) _ <;> norm_num at *;
                                                                                                                                                                            · refine' div_le_one_of_le₀ _ _ <;> norm_cast <;> norm_num [ count_in_class ] at *;
                                                                                                                                                                              exact Finset.sum_le_sum fun _ _ => Finset.card_mono fun x hx => by aesop;
                                                                                                                                                                            · refine' Real.logb_nonpos ( by norm_num ) _ _ <;> norm_num at *;
                                                                                                                                                                              · refine' div_le_one_of_le₀ _ _ <;> norm_cast <;> norm_num [ count_in_class ] at *;
                                                                                                                                                                                exact Finset.sum_le_sum fun _ _ => Finset.card_mono fun x hx => by aesop;
                                                                                                                                                                              · positivity;
                                                                                                                                                                            · refine' mul_nonpos_of_nonneg_of_nonpos ( div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( Real.logb_nonpos ( by norm_num ) _ _ ) <;> norm_num [ h₃ ];
                                                                                                                                                                              · positivity;
                                                                                                                                                                              · refine' div_le_one_of_le₀ _ _ <;> norm_cast <;> simp_all +decide [ count_in_class ];
                                                                                                                                                                                exact Finset.sum_le_sum fun _ _ => Finset.card_mono fun x hx => by aesop; ) ) ]
/-
Lemma: If U is eventually periodic with (p, s), it is also eventually periodic with (m*p, m*s).
-/
lemma eventually_periodic_multiple {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ)
  (h : EventuallyPeriodic U p s T0) (m : ℕ) (hm : m > 0) :
  EventuallyPeriodic U (m * p) (m • s) T0 := by
    intro t ht x; induction' m with m ih <;> simp_all +decide [ Nat.succ_mul, add_smul ] ; ring;
    by_cases hm : 0 < m <;> simp_all +decide [ ← add_assoc ];
    · rw [ ← ih, h ( t + m * p ) ( by nlinarith ) ( x + m • s ) ];
    · exact h t ht x
/-
Theorem 5(i): The per-site NLL rates are equal to 0 (formalized as NLL being o(T)).
-/
/-- Theorem 5(i): The per-site NLL rates are equal to 0. -/
theorem theorem_5_i {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  Asymptotics.IsLittleO Filter.atTop (fun T => NLL U (m * p0) (m • s) T (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0)) (fun T : ℕ => (T : Real)) ∧
  Asymptotics.IsLittleO Filter.atTop (fun T => NLL U p0 s T hp0) (fun T : ℕ => (T : Real)) := by
  have hp : m * p0 > 0 := Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0
  constructor
  · -- Part 1: p = m * p0
    have h_eventual_p : EventuallyPeriodic U (m * p0) (m • s) T0 := by
      apply eventually_periodic_multiple U p0 s T0 h_eventual m (Nat.lt_trans Nat.zero_lt_one hm)
    obtain ⟨C, hC⟩ := nll_growth_bound U (m * p0) (m • s) T0 hp h_eventual_p
    have h_bigO : Asymptotics.IsBigO Filter.atTop (fun T => NLL U (m * p0) (m • s) T hp) (fun T : ℕ => Real.log (T + 1)) := by
      rw [Asymptotics.isBigO_iff]
      use C + |C| + 1
      filter_upwards [Filter.eventually_ge_atTop T0] with T hT
      rw [Real.norm_eq_abs, abs_of_nonneg (by
      -- Since each term in the sum is non-negative, the entire sum is non-negative.
      have h_nonneg : ∀ (idx : (Fin (m * p0)) × X), 0 ≤ (let (n, k) := count_in_class U (m * p0) (m • s) T idx hp; if n = 0 then 0 else n * h_b ((k : ℝ) / n)) := by
        -- Since $h_b(x)$ is non-negative for all $x \in [0, 1]$, and $n$ is non-negative, their product is non-negative.
        have h_h_b_nonneg : ∀ x : ℝ, 0 ≤ x → x ≤ 1 → 0 ≤ h_b x := by
          intro x hx₁ hx₂; unfold h_b; split_ifs <;> norm_num;
          rw [ Real.logb, Real.logb ];
          field_simp;
          nlinarith [ Real.log_le_sub_one_of_pos ( show 0 < 1 - x by exact sub_pos.mpr ( lt_of_le_of_ne hx₂ ( by tauto ) ) ), Real.log_le_sub_one_of_pos ( show 0 < x by exact lt_of_le_of_ne hx₁ ( by tauto ) ) ];
        intro idx
        simp [count_in_class];
        split_ifs <;> [ exact le_rfl; exact mul_nonneg ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ( h_h_b_nonneg _ ( div_nonneg ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ) ( div_le_one_of_le₀ ( Finset.sum_le_sum fun _ _ => mod_cast Finset.card_mono <| fun x hx => by aesop ) ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ) ) ];
      exact Finset.sum_nonneg fun _ _ => h_nonneg _)]
      specialize hC T hT
      cases abs_cases C <;> simp +decide [ * ];
      · by_cases h_log : Real.log (T + 1) ≥ 1;
        · rw [ abs_of_nonneg ( Real.log_nonneg ( by linarith ) ) ] ; nlinarith;
        · rw [ abs_of_nonneg ( Real.log_nonneg ( by linarith ) ) ];
          rcases T with ( _ | _ | T ) <;> norm_num at *;
          · unfold NLL; aesop;
          · nlinarith [ Real.log_two_gt_d9, show ( NLL U ( m * p0 ) ( m • s ) 1 hp : ℝ ) ≤ 0 from by
                                              unfold NLL;
                                              unfold count_in_class; simp +decide [ Finset.sum_range_succ' ] ;
                                              simp +decide [ Finset.sum_ite, orbitIndex ];
                                              simp +decide [ Finset.filter_eq', Finset.filter_and ];
                                              refine' Finset.sum_nonpos fun x _ => _;
                                              by_cases hx : U 0 x <;> simp +decide [ hx, h_b ] ];
          · exact False.elim <| h_log.not_le <| Real.le_log_iff_exp_le ( by positivity ) |>.2 <| by exact Real.exp_one_lt_d9.le.trans <| by norm_num; linarith;
      · nlinarith [ abs_nonneg ( Real.log ( T + 1 ) ), Real.log_nonneg ( by linarith : ( T : ℝ ) + 1 ≥ 1 ) ]
    have h_littleO : Asymptotics.IsLittleO Filter.atTop (fun T : ℕ => Real.log (T + 1)) (fun T : ℕ => (T : Real)) := by
      -- To show that Real.log (T + 1) is little-o of T, we can use the fact that the limit of Real.log T / T as T approaches infinity is 0.
      have h_log_div_T_zero : Filter.Tendsto (fun T : ℝ => Real.log T / T) Filter.atTop (nhds 0) := by
        -- Let $y = \frac{1}{x}$, so we can rewrite the limit as $\lim_{y \to 0^+} y \log(1/y)$.
        suffices h_log_recip : Filter.Tendsto (fun y : ℝ => y * Real.log (1 / y)) (Filter.map (fun x => 1 / x) Filter.atTop) (nhds 0) by
          exact h_log_recip.congr ( by simp +contextual [ div_eq_inv_mul ] );
        norm_num +zetaDelta at *;
        exact tendsto_nhdsWithin_of_tendsto_nhds ( by simpa using Real.continuous_mul_log.neg.tendsto 0 );
      rw [ Asymptotics.isLittleO_iff_tendsto' ] <;> norm_num;
      · have h_log_div_T_zero : Filter.Tendsto (fun T : ℝ => Real.log (T + 1) / T) Filter.atTop (nhds 0) := by
          have h_log_div_T_zero : Filter.Tendsto (fun T : ℝ => (Real.log T + Real.log (1 + 1 / T)) / T) Filter.atTop (nhds 0) := by
            simpa [ add_div ] using h_log_div_T_zero.add ( Filter.Tendsto.div_atTop ( Filter.Tendsto.log ( tendsto_const_nhds.add ( tendsto_inv_atTop_zero ) ) ( by norm_num ) ) Filter.tendsto_id );
          refine h_log_div_T_zero.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by rw [ one_add_div hT.ne', Real.log_div ] <;> ring <;> positivity );
        exact h_log_div_T_zero.comp tendsto_natCast_atTop_atTop;
      · exact ⟨ 1, by intros; linarith ⟩
    exact Asymptotics.IsBigO.trans_isLittleO h_bigO h_littleO
  · -- Part 2: p0
    obtain ⟨C, hC⟩ := nll_growth_bound U p0 s T0 hp0 h_eventual
    have h_bigO : Asymptotics.IsBigO Filter.atTop (fun T => NLL U p0 s T hp0) (fun T : ℕ => Real.log (T + 1)) := by
      rw [Asymptotics.isBigO_iff]
      use C + |C| + 1
      filter_upwards [Filter.eventually_ge_atTop T0] with T hT
      rw [Real.norm_eq_abs, abs_of_nonneg (by
      -- Each term in the sum is non-negative because $h_b(\theta)$ is non-negative for any $\theta \in [0, 1]$.
      have h_nonneg : ∀ idx : (Fin p0) × X, 0 ≤ (let (n, k) := count_in_class U p0 s T idx hp0; if n = 0 then 0 else n * h_b (k / n)) := by
        -- Since $h_b(\theta)$ is non-negative for any $\theta \in [0, 1]$, and $n$ is non-negative, their product is also non-negative.
        have h_nonneg : ∀ theta : ℝ, 0 ≤ theta ∧ theta ≤ 1 → 0 ≤ h_b theta := by
          unfold h_b;
          -- Since $\log_2(\theta)$ and $\log_2(1-\theta)$ are negative for $0 < \theta < 1$, their product with $-\theta$ and $-(1-\theta)$ respectively will be positive.
          intros theta htheta
          by_cases htheta0 : theta = 0 ∨ theta = 1;
          · aesop;
          · split_ifs ; nlinarith [ show Real.logb 2 theta ≤ 0 from Real.logb_nonpos ( by norm_num ) ( by linarith ) ( by linarith ), show Real.logb 2 ( 1 - theta ) ≤ 0 from Real.logb_nonpos ( by norm_num ) ( by linarith ) ( by linarith ) ];
        intro idx
        simp [count_in_class];
        split_ifs <;> norm_num;
        exact mul_nonneg ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ( h_nonneg _ ⟨ div_nonneg ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ), div_le_one_of_le₀ ( Finset.sum_le_sum fun _ _ => mod_cast Finset.card_le_card fun _ => by aesop ) ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ⟩ );
      exact Finset.sum_nonneg fun _ _ => h_nonneg _)]
      specialize hC T hT
      cases abs_cases C <;> simp +decide [ * ];
      · by_cases h_log : Real.log (T + 1) ≥ 1;
        · rw [ abs_of_nonneg ( by positivity ) ] ; nlinarith;
        · rw [ abs_of_nonneg ( Real.log_nonneg ( by linarith ) ) ];
          contrapose! h_log;
          rcases T with ( _ | _ | T ) <;> norm_num at *;
          · unfold NLL at h_log ; aesop;
          · have hNLL_zero : NLL U p0 s 1 hp0 = 0 := by
              unfold NLL; simp +decide [ Finset.sum_range_succ' ] ;
              unfold count_in_class; simp +decide [ Finset.sum_range_succ' ] ;
              unfold orbitIndex; simp +decide [ Finset.sum_ite ] ;
              simp +decide [ Finset.filter_eq', Finset.filter_and ];
              refine' Finset.sum_eq_zero fun x _ => _ ; by_cases hx : U 0 x = Bool.true <;> simp +decide [ hx ] ;
              · unfold h_b; simp +decide ;
              · unfold h_b; simp +decide ;
            nlinarith [ Real.log_pos one_lt_two ];
          · exact Real.le_log_iff_exp_le ( by linarith ) |>.2 ( by exact Real.exp_one_lt_d9.le.trans ( by norm_num; linarith ) );
      · exact le_trans hC ( by nlinarith [ abs_of_nonneg ( Real.log_nonneg ( by linarith : ( T:ℝ ) + 1 ≥ 1 ) ), Real.log_nonneg ( by linarith : ( T:ℝ ) + 1 ≥ 1 ) ] )
    have h_littleO : Asymptotics.IsLittleO Filter.atTop (fun T : ℕ => Real.log (T + 1)) (fun T : ℕ => (T : Real)) := by
      -- To show that Real.log (T + 1) is little-o of T, we can use the fact that the limit of Real.log T / T as T approaches infinity is 0.
      have h_log_div_T_zero : Filter.Tendsto (fun T : ℝ => Real.log T / T) Filter.atTop (nhds 0) := by
        -- Let $y = \frac{1}{x}$, so we can rewrite the limit as $\lim_{y \to 0^+} y \log(1/y)$.
        suffices h_log_recip : Filter.Tendsto (fun y : ℝ => y * Real.log (1 / y)) (Filter.map (fun x => 1 / x) Filter.atTop) (nhds 0) by
          exact h_log_recip.congr ( by simp +contextual [ div_eq_inv_mul ] );
        norm_num +zetaDelta at *;
        exact tendsto_nhdsWithin_of_tendsto_nhds ( by simpa using Real.continuous_mul_log.neg.tendsto 0 );
      rw [ Asymptotics.isLittleO_iff_tendsto' ] <;> norm_num;
      · have h_log_div_T_zero : Filter.Tendsto (fun T : ℝ => Real.log (T + 1) / T) Filter.atTop (nhds 0) := by
          have h_log_div_T_zero : Filter.Tendsto (fun T : ℝ => (Real.log T + Real.log (1 + 1 / T)) / T) Filter.atTop (nhds 0) := by
            simpa [ add_div ] using h_log_div_T_zero.add ( Filter.Tendsto.div_atTop ( Filter.Tendsto.log ( tendsto_const_nhds.add ( tendsto_inv_atTop_zero ) ) ( by norm_num ) ) Filter.tendsto_id );
          refine h_log_div_T_zero.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by rw [ one_add_div hT.ne', Real.log_div ] <;> ring <;> positivity );
        exact h_log_div_T_zero.comp tendsto_natCast_atTop_atTop;
      · exact ⟨ 1, by intros; linarith ⟩
    exact Asymptotics.IsBigO.trans_isLittleO h_bigO h_littleO
/-
For a fixed number of minority symbols k, the total entropy n * h_b(k/n) is asymptotically k * log2(n) + O(1).
-/
lemma entropy_asymptotic (k : ℕ) :
  Asymptotics.IsBigO Filter.atTop (fun (n : ℕ) => (n : ℝ) * h_b (k / n) - k * Real.logb 2 n) (fun _ => (1 : Real)) := by
    field_simp;
    by_cases hk : k = 0 <;> simp +decide [ hk, h_b, Real.logb ];
    · exact ⟨ 0, Filter.eventually_atTop.mpr ⟨ 0, fun x hx => by norm_num ⟩ ⟩;
    · -- For large $n$, the expression simplifies to $-k \log k + k + O(1/n)$.
      have h_simplify : ∀ᶠ n : ℕ in Filter.atTop, abs ((n : ℝ) * (-(k / n * (Real.log (k / n) / Real.log 2)) - (1 - k / n) * (Real.log (1 - k / n) / Real.log 2)) - k * (Real.log n / Real.log 2)) ≤ abs (-k * Real.log k / Real.log 2 + k / Real.log 2) + 1 := by
        -- For large $n$, the term $(1 - k/n) \log(1 - k/n)$ can be approximated by $-k/n$.
        have h_approx : Filter.Tendsto (fun n : ℕ => (n : ℝ) * (1 - k / n) * (Real.log (1 - k / n) / Real.log 2)) Filter.atTop (nhds (-k / Real.log 2)) := by
          -- We'll use the fact that $(1 - k/n) \log(1 - k/n)$ converges to $-\frac{k}{n}$ as $n \to \infty$.
          have h_log_approx : Filter.Tendsto (fun n : ℕ => (n : ℝ) * (Real.log (1 - k / n) / Real.log 2)) Filter.atTop (nhds (-k / Real.log 2)) := by
            -- We'll use the fact that $n \log(1 - k/n) \to -k$ as $n \to \infty$.
            have h_log : Filter.Tendsto (fun n : ℕ => (n : ℝ) * Real.log (1 - k / n)) Filter.atTop (nhds (-k)) := by
              -- Let $y = \frac{1}{n}$, so we can rewrite the limit as $\lim_{y \to 0^+} \frac{\log(1 - ky)}{y}$.
              suffices h_log_approx' : Filter.Tendsto (fun y : ℝ => Real.log (1 - k * y) / y) (Filter.map (fun n => 1 / (n : ℝ)) Filter.atTop) (nhds (-k)) by
                exact h_log_approx'.comp ( Filter.map_mono tendsto_natCast_atTop_atTop ) |> fun h => h.congr ( by intros; simp +decide [ div_eq_mul_inv, mul_comm ] );
              simpa [ div_eq_inv_mul ] using HasDerivAt.tendsto_slope_zero_right ( HasDerivAt.log ( HasDerivAt.const_sub 1 ( HasDerivAt.const_mul ( k : ℝ ) ( hasDerivAt_id 0 ) ) ) ( by aesop ) );
            simpa only [ mul_div ] using h_log.div_const _;
          convert h_log_approx.mul ( show Filter.Tendsto ( fun n : ℕ => ( 1 - k / ( n : ℝ ) ) ) Filter.atTop ( nhds 1 ) from by simpa using tendsto_const_nhds.sub ( tendsto_const_nhds.mul tendsto_inverse_atTop_nhds_zero_nat ) ) using 2 <;> ring;
        -- Using the approximation, we can bound the expression.
        have h_bound : Filter.Tendsto (fun n : ℕ => (n : ℝ) * (-(k / n * (Real.log (k / n) / Real.log 2)) - (1 - k / n) * (Real.log (1 - k / n) / Real.log 2)) - k * (Real.log n / Real.log 2)) Filter.atTop (nhds (-k * Real.log k / Real.log 2 + k / Real.log 2)) := by
          have h_bound : Filter.Tendsto (fun n : ℕ => (n : ℝ) * (-(k / n * (Real.log k / Real.log 2)) + k / n * (Real.log n / Real.log 2)) - k * (Real.log n / Real.log 2)) Filter.atTop (nhds (-k * Real.log k / Real.log 2)) := by
            refine' Filter.Tendsto.congr' _ tendsto_const_nhds;
            filter_upwards [ Filter.eventually_gt_atTop 0 ] with n hn using by simp [ div_eq_mul_inv, mul_add, mul_assoc, mul_comm, mul_left_comm, hn.ne' ];
          convert h_bound.add ( h_approx.neg ) using 2 <;> ring;
          by_cases h : ‹_› = 0 <;> simp +decide [ h, mul_assoc, mul_comm, mul_left_comm ] ; ring;
          rw [ Real.log_mul ( by positivity ) ( by positivity ), Real.log_inv ] ; ring;
        have := h_bound.abs.eventually ( ge_mem_nhds <| show |-↑k * Real.log ↑k / Real.log 2 + ↑k / Real.log 2| < |-↑k * Real.log ↑k / Real.log 2 + ↑k / Real.log 2| + 1 by linarith ) ; aesop;
      refine' ⟨ |-k * Real.log k / Real.log 2 + k / Real.log 2| + 1, _ ⟩;
      simp +zetaDelta at *;
      obtain ⟨ a, ha ⟩ := h_simplify; use Max.max a k; intro b hb; specialize ha b ( le_trans ( le_max_left _ _ ) hb ) ; aesop;
/-
Definition of projecting an orbit index from a larger period m*p0 to a smaller period p0.
-/
def projectIndex (p0 : ℕ) (s : X) (m : ℕ) (idx : (Fin (m * p0)) × X) (hp0 : p0 > 0) : (Fin p0) × X :=
  let ⟨j, y⟩ := idx
  ⟨⟨j % p0, Nat.mod_lt _ hp0⟩, y - (j / p0) • s⟩
/-
Correctness of projecting an orbit index from a larger period to a smaller period.
-/
lemma projectIndex_correct (p0 : ℕ) (s : X) (m : ℕ) (t : ℕ) (x : X) (hp0 : p0 > 0) (hm : m > 0) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos hm hp0
  projectIndex p0 s m (orbitIndex p s_p t x hp) hp0 = orbitIndex p0 s t x hp0 := by
    simp +decide [ orbitIndex, projectIndex ];
    rw [ show t / p0 = t / ( m * p0 ) * m + t % ( m * p0 ) / p0 from ?_ ];
    · rw [ add_smul, mul_smul ];
      rw [ sub_sub ];
    · rw [ ← Nat.div_add_mod t ( m * p0 ) ];
      norm_num [ Nat.add_div, Nat.add_mod, Nat.mul_div_assoc, Nat.mul_mod, hp0, hm ];
      split_ifs <;> simp_all +decide [ Nat.mul_assoc, Nat.mul_div_assoc, Nat.mod_eq_of_lt ] ; linarith [ Nat.mod_lt t ( mul_pos hm hp0 ) ] ;
      · linarith [ Nat.mod_lt t hp0 ];
      · exact absurd ‹_› ( not_le_of_gt ( Nat.mod_lt _ ( by positivity ) ) );
      · ring
/-
The counts of total points and ones in an orbit class of the smaller period are the sums of the counts in the corresponding orbit classes of the larger period.
-/
lemma count_sum_of_split (U : Spacetime X) (p0 : ℕ) (s : X) (T : ℕ) (idx0 : (Fin p0) × X) (hp0 : p0 > 0) (m : ℕ) (hm : m > 0) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos hm hp0
  let preimages := Finset.univ.filter (fun idx => projectIndex p0 s m idx hp0 = idx0)
  let (N, K) := count_in_class U p0 s T idx0 hp0
  N = preimages.sum (fun idx => (count_in_class U p s_p T idx hp).1) ∧
  K = preimages.sum (fun idx => (count_in_class U p s_p T idx hp).2) := by
    refine' ⟨ _, _ ⟩;
    · -- By definition of `count_in_class`, we can rewrite the left-hand side as a sum over the preimages.
      have h_sum_preimages : ∑ t ∈ Finset.range T, (Finset.univ.filter (fun x => orbitIndex p0 s t x hp0 = idx0)).card = ∑ t ∈ Finset.range T, ∑ idx ∈ Finset.univ.filter (fun idx => projectIndex p0 s m idx hp0 = idx0), (Finset.univ.filter (fun x => orbitIndex (m * p0) (m • s) t x (Nat.mul_pos hm hp0) = idx)).card := by
        refine' Finset.sum_congr rfl fun t ht => _;
        rw [ ← Finset.card_biUnion ];
        · congr with x;
          simp +decide [ projectIndex_correct p0 s m t x hp0 hm ];
        · exact fun x hx y hy hxy => Finset.disjoint_left.mpr fun z hz1 hz2 => hxy <| by aesop;
      rw [ h_sum_preimages, Finset.sum_comm ];
      exact Finset.sum_congr rfl fun _ _ => rfl;
    · simp +decide only [count_in_class];
      rw [ Finset.sum_comm, Finset.sum_congr rfl ];
      intro t ht;
      rw [ ← Finset.card_biUnion ];
      · congr with x ; simp +decide [ projectIndex_correct ];
        constructor <;> intro h
        all_goals generalize_proofs at *;
        · exact ⟨ _, _, projectIndex_correct p0 s m t x hp0 hm ▸ h.1, rfl, h.2 ⟩;
        · obtain ⟨ a, b, h₁, h₂, h₃ ⟩ := h; have := projectIndex_correct p0 s m t x hp0 hm; aesop;
      · intro x hx y hy hxy; simp_all +decide [ Finset.disjoint_left ] ;
/-
Definition of the eventual value of an orbit class and the number of transient disagreements (k_inf).
-/
noncomputable def eventual_value (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ) (hp : p > 0) (h_eventual : EventuallyPeriodic U p s T0) (idx : (Fin p) × X) : Bool :=
  Classical.choose (values_eventually_constant_of_eventually_periodic U p s T0 hp h_eventual idx)
noncomputable def k_inf (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ) (hp : p > 0) (h_eventual : EventuallyPeriodic U p s T0) (idx : (Fin p) × X) : ℕ :=
  let c := eventual_value U p s T0 hp h_eventual idx
  Finset.card (Finset.filter (fun t =>
    if t % p = idx.1 then
      U t (idx.2 + (t / p) • s) ≠ c
    else false
  ) (Finset.range T0))
/-
Consistency of eventual values under period multiplication.
-/
lemma eventual_value_consistent (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ) (hp0 : p0 > 0) (h_eventual : EventuallyPeriodic U p0 s T0) (m : ℕ) (hm : m > 0) (idx : (Fin (m * p0)) × X) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos hm hp0
  have h_eventual_p : EventuallyPeriodic U p s_p T0 := eventually_periodic_multiple U p0 s T0 h_eventual m hm
  eventual_value U p s_p T0 hp h_eventual_p idx = eventual_value U p0 s T0 hp0 h_eventual (projectIndex p0 s m idx hp0) := by
    -- By definition of `eventual_value`, there exist $T1$ and $T2$ such that for all $t \geq T1$, $U(t, x) = eventual\_value U p s_p T0 hp h_eventual_p idx$ and for all $t \geq T2$, $U(t, x) = eventual\_value U p0 s T0 hp0 h_eventual (projectIndex p0 s m idx hp0)$.
    obtain ⟨T1, hT1⟩ : ∃ T1 ≥ T0, ∀ t ≥ T1, ∀ x, orbitIndex (m * p0) (m • s) t x (Nat.mul_pos hm hp0) = idx → U t x = eventual_value U (m * p0) (m • s) T0 (Nat.mul_pos hm hp0) (eventually_periodic_multiple U p0 s T0 h_eventual m hm) idx := by
      have := Classical.choose_spec ( values_eventually_constant_of_eventually_periodic U ( m * p0 ) ( m • s ) T0 ( Nat.mul_pos hm hp0 ) ( eventually_periodic_multiple U p0 s T0 h_eventual m hm ) idx );
      exact this
    obtain ⟨T2, hT2⟩ : ∃ T2 ≥ T0, ∀ t ≥ T2, ∀ x, orbitIndex p0 s t x hp0 = projectIndex p0 s m idx hp0 → U t x = eventual_value U p0 s T0 hp0 h_eventual (projectIndex p0 s m idx hp0) := by
      have := Classical.choose_spec ( values_eventually_constant_of_eventually_periodic U p0 s T0 hp0 h_eventual ( projectIndex p0 s m idx hp0 ) ) ; aesop;
    -- Choose $t$ such that $t \geq \max(T1, T2)$ and $t \equiv idx.1 \pmod{m * p0}$.
    obtain ⟨t, ht⟩ : ∃ t ≥ max T1 T2, t % (m * p0) = idx.1 := by
      use (max T1 T2) * (m * p0) + idx.1.val;
      exact ⟨ by nlinarith [ Nat.zero_le ( max T1 T2 ), mul_pos hm hp0 ], by simp +decide [ Nat.add_mod, Nat.mod_eq_of_lt ( show ( idx.1 : ℕ ) < m * p0 from idx.1.2 ) ] ⟩;
    -- Let $x = idx.2 + (t / (m * p0)) • (m • s)$.
    set x := idx.2 + (t / (m * p0)) • (m • s);
    have hx : orbitIndex (m * p0) (m • s) t x (Nat.mul_pos hm hp0) = idx := by
      unfold orbitIndex; aesop;
    have hx' : orbitIndex p0 s t x hp0 = projectIndex p0 s m idx hp0 := by
      have := projectIndex_correct p0 s m t x hp0 hm; aesop;
    have h_eq : U t x = eventual_value U (m * p0) (m • s) T0 (Nat.mul_pos hm hp0) (eventually_periodic_multiple U p0 s T0 h_eventual m hm) idx ∧ U t x = eventual_value U p0 s T0 hp0 h_eventual (projectIndex p0 s m idx hp0) := by
      exact ⟨ hT1.2 t ( le_trans ( le_max_left _ _ ) ht.1 ) x hx, hT2.2 t ( le_trans ( le_max_right _ _ ) ht.1 ) x hx' ⟩
    aesop
/-
The total number of transient disagreements is invariant under period multiplication.
-/
lemma k_inf_sum_eq (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ) (hp0 : p0 > 0) (h_eventual : EventuallyPeriodic U p0 s T0) (m : ℕ) (hm : m > 1) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0
  have h_eventual_p : EventuallyPeriodic U p s_p T0 := eventually_periodic_multiple U p0 s T0 h_eventual m (Nat.lt_trans Nat.zero_lt_one hm)
  ∑ idx : (Fin p) × X, k_inf U p s_p T0 hp h_eventual_p idx = ∑ idx0 : (Fin p0) × X, k_inf U p0 s T0 hp0 h_eventual idx0 := by
    apply le_antisymm
    all_goals generalize_proofs at *;
    · -- By definition of $k_inf$, we can expand both sides of the inequality.
      have h_expand : ∀ (p : ℕ) (s : X) (hp : p > 0) (h_eventual : EventuallyPeriodic U p s T0), ∑ idx : (Fin p) × X, k_inf U p s T0 hp h_eventual idx = ∑ t ∈ Finset.range T0, ∑ x : X, if U t x ≠ eventual_value U p s T0 hp h_eventual (orbitIndex p s t x hp) then 1 else 0 := by
        unfold k_inf;
        intro p s hp h_eventual
        have h_split : ∀ t ∈ Finset.range T0, ∑ x : X, (if U t x ≠ eventual_value U p s T0 hp h_eventual (orbitIndex p s t x hp) then 1 else 0) = ∑ idx : (Fin p) × X, (if t % p = idx.1 then if U t (idx.2 + (t / p) • s) ≠ eventual_value U p s T0 hp h_eventual idx then 1 else 0 else 0) := by
          intro t ht
          have h_split : ∀ x : X, (if U t x ≠ eventual_value U p s T0 hp h_eventual (orbitIndex p s t x hp) then 1 else 0) = ∑ idx : (Fin p) × X, (if t % p = idx.1 then if x = idx.2 + (t / p) • s then if U t x ≠ eventual_value U p s T0 hp h_eventual idx then 1 else 0 else 0 else 0) := by
            intro x
            simp [orbitIndex];
            rw [ Finset.sum_eq_single ( ⟨ ⟨ t % p, Nat.mod_lt _ hp ⟩, x - ( t / p ) • s ⟩ : ( Fin p ) × X ) ] <;> simp +decide [ Fin.ext_iff ];
            grind;
          rw [ Finset.sum_congr rfl fun x hx => h_split x, Finset.sum_comm ];
          simp +decide [ Finset.sum_ite ];
        rw [ Finset.sum_congr rfl h_split, Finset.sum_comm ];
        simp +decide [ Finset.sum_ite ];
        simp +decide only [Finset.filter_filter];
      -- By definition of $eventual_value$, we know that for any $t$, the condition $U t x ≠ eventual_value U p s T0 hp h_eventual (orbitIndex p s t x hp)$ is the same for both periods.
      have h_eventual_value : ∀ (t : ℕ) (x : X), eventual_value U (m * p0) (m • s) T0 (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0) (eventually_periodic_multiple U p0 s T0 h_eventual m (Nat.lt_trans Nat.zero_lt_one hm)) (orbitIndex (m * p0) (m • s) t x (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0)) = eventual_value U p0 s T0 hp0 h_eventual (orbitIndex p0 s t x hp0) := by
        intro t x; exact (by
        convert eventual_value_consistent U p0 s T0 hp0 h_eventual m ( Nat.lt_trans Nat.zero_lt_one hm ) ( orbitIndex ( m * p0 ) ( m • s ) t x ( Nat.mul_pos ( Nat.lt_trans Nat.zero_lt_one hm ) hp0 ) ) using 1
        generalize_proofs at *; (
        exact congr_arg _ ( projectIndex_correct p0 s m t x hp0 ( Nat.lt_trans Nat.zero_lt_one hm ) ▸ rfl )));
      convert h_expand ( m * p0 ) ( m • s ) ( Nat.mul_pos ( Nat.lt_trans Nat.zero_lt_one hm ) hp0 ) ( eventually_periodic_multiple U p0 s T0 h_eventual m ( Nat.lt_trans Nat.zero_lt_one hm ) ) |> le_of_eq using 2 ; aesop ( simp_config := { singlePass := true } ) ;
    · -- By definition of $k_inf$, we can expand both sides of the inequality.
      have h_expand : ∀ (p : ℕ) (s : X) (hp : p > 0) (h_eventual : EventuallyPeriodic U p s T0), ∑ idx : (Fin p) × X, k_inf U p s T0 hp h_eventual idx = ∑ t ∈ Finset.range T0, ∑ x : X, if U t x ≠ eventual_value U p s T0 hp h_eventual (orbitIndex p s t x hp) then 1 else 0 := by
        unfold k_inf;
        intro p s hp h_eventual
        have h_split : ∀ t ∈ Finset.range T0, ∑ x : X, (if U t x ≠ eventual_value U p s T0 hp h_eventual (orbitIndex p s t x hp) then 1 else 0) = ∑ idx : (Fin p) × X, (if t % p = idx.1 then if U t (idx.2 + (t / p) • s) ≠ eventual_value U p s T0 hp h_eventual idx then 1 else 0 else 0) := by
          intro t ht
          have h_split : ∀ x : X, (if U t x ≠ eventual_value U p s T0 hp h_eventual (orbitIndex p s t x hp) then 1 else 0) = ∑ idx : (Fin p) × X, (if t % p = idx.1 then if x = idx.2 + (t / p) • s then if U t x ≠ eventual_value U p s T0 hp h_eventual idx then 1 else 0 else 0 else 0) := by
            intro x
            simp [orbitIndex];
            rw [ Finset.sum_eq_single ( ⟨ ⟨ t % p, Nat.mod_lt _ hp ⟩, x - ( t / p ) • s ⟩ : ( Fin p ) × X ) ] <;> simp +decide [ Fin.ext_iff ];
            grind;
          rw [ Finset.sum_congr rfl fun x hx => h_split x, Finset.sum_comm ];
          simp +decide [ Finset.sum_ite ];
        rw [ Finset.sum_congr rfl h_split, Finset.sum_comm ];
        simp +decide [ Finset.sum_ite ];
        simp +decide only [Finset.filter_filter];
      rw [ h_expand p0 s hp0 h_eventual, h_expand ( m * p0 ) ( m • s ) ( Nat.mul_pos ( pos_of_gt hm ) hp0 ) ( eventually_periodic_multiple U p0 s T0 h_eventual m hm.le ) ];
      refine' Finset.sum_le_sum fun t ht => Finset.sum_le_sum fun x hx => _;
      rw [ eventual_value_consistent ];
      rw [ projectIndex_correct ];
      · linarith;
      · exact hp0;
      · assumption;
      · linarith
/-
The NLL term for an orbit class depends only on the number of transient disagreements k_inf.
-/
lemma nll_term_eq_k_inf (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ) (hp : p > 0) (h_eventual : EventuallyPeriodic U p s T0) (idx : (Fin p) × X) (T : ℕ) (hT : T ≥ T0) :
  let (n, k) := count_in_class U p s T idx hp
  let k_i := k_inf U p s T0 hp h_eventual idx
  (if n = 0 then (0 : ℝ) else (n : ℝ) * h_b ((k : ℝ) / (n : ℝ))) = (if n = 0 then (0 : ℝ) else (n : ℝ) * h_b ((k_i : ℝ) / (n : ℝ))) := by
    -- Let $c$ be the eventual value of the orbit class.
    set c := eventual_value U p s T0 hp h_eventual idx;
    -- For $t \geq T0$, $U(t, x) = c$ for all $x$ in the orbit class.
    have h_const : ∀ t ≥ T0, ∀ x, orbitIndex p s t x hp = idx → U t x = c := by
      have := Classical.choose_spec ( values_eventually_constant_of_eventually_periodic U p s T0 hp h_eventual idx );
      obtain ⟨ T1, hT1, h ⟩ := this; intro t ht x hx; by_cases hT : t < T1 <;> simp_all +decide ;
      · convert h ( t + p * ( T1 - t ) ) ( by nlinarith [ Nat.sub_add_cancel hT.le ] ) ( x + ( T1 - t ) • s ) _ using 1;
        · induction' T1 - t with k hk <;> simp_all +decide [ Nat.mul_succ, ← add_assoc ];
          convert h_eventual ( t + p * k ) ( by nlinarith ) ( x + k • s ) |> Eq.symm using 1 ; simp +decide [ add_smul, add_assoc ];
        · induction' T1 - t with k hk <;> simp_all +decide [ Nat.mul_succ, ← add_assoc ];
          convert orbitIndex_add_period p s ( t + p * k ) ( x + k • s ) hp using 1 ; simp +decide [ add_smul, add_assoc ];
          exact hk.symm;
      · rfl;
    -- For $t < T0$, $U(t, x) = 1 - c$ if and only if $U(t, x)$ is in the orbit class and $U(t, x) \neq c$.
    have h_disagreements : Finset.sum (Finset.range T) (fun t => Finset.card (Finset.filter (fun x => orbitIndex p s t x hp = idx ∧ U t x = 1 - c) Finset.univ)) = k_inf U p s T0 hp h_eventual idx := by
      have h_disagreements : ∀ t < T0, Finset.card (Finset.filter (fun x => orbitIndex p s t x hp = idx ∧ U t x = 1 - c) Finset.univ) = if t % p = idx.1 ∧ U t (idx.2 + (t / p) • s) = 1 - c then 1 else 0 := by
        intro t ht; split_ifs <;> simp_all +decide [ Fin.ext_iff, orbitIndex ] ;
        · rw [ Finset.card_eq_one ] ; use idx.2 + ( t / p ) • s ; ext x ; aesop;
        · intro x hx; contrapose! hx; aesop;
      rw [ ← Finset.sum_subset ( Finset.range_mono hT ) ];
      · rw [ Finset.sum_congr rfl fun t ht => h_disagreements t ( Finset.mem_range.mp ht ) ] ; simp +decide [ k_inf ] ; ring;
        congr! 2;
        ext; simp [c];
        cases eventual_value U p s T0 hp h_eventual idx <;> simp +decide [ * ];
        · aesop;
        · aesop;
      · simp +contextual [ Finset.ext_iff, h_const ];
        cases c <;> simp +decide;
    -- For $t < T0$, $U(t, x) = c$ if and only if $U(t, x)$ is in the orbit class and $U(t, x) = c$.
    have h_agreements : Finset.sum (Finset.range T) (fun t => Finset.card (Finset.filter (fun x => orbitIndex p s t x hp = idx ∧ U t x = c) Finset.univ)) = (count_in_class U p s T idx hp).1 - k_inf U p s T0 hp h_eventual idx := by
      rw [ ← h_disagreements, Nat.sub_eq_of_eq_add ];
      rw [ ← Finset.sum_add_distrib, count_in_class ];
      cases c <;> simp +decide [ *, Finset.filter_or ];
      · refine' Finset.sum_congr rfl fun t ht => _;
        rw [ Finset.card_filter, Finset.card_filter, Finset.card_filter ];
        rw [ ← Finset.sum_add_distrib ] ; congr ; ext x ; cases U t x <;> simp +decide [ * ] ;
      · refine' Finset.sum_congr rfl fun t ht => _;
        rw [ Finset.card_filter, Finset.card_filter, Finset.card_filter ];
        rw [ ← Finset.sum_add_distrib ] ; congr ; ext x ; by_cases hx : U t x <;> simp +decide [ hx ] ;
    -- By definition of $k$, we know that $k = \sum_{t=0}^{T-1} \sum_{x \in \text{orbit class}} U(t, x)$.
    have h_k : (count_in_class U p s T idx hp).2 = Finset.sum (Finset.range T) (fun t => Finset.card (Finset.filter (fun x => orbitIndex p s t x hp = idx ∧ U t x = true) Finset.univ)) := by
      exact?;
    by_cases hc : c <;> simp_all +decide [ Finset.sum_ite ];
    · rw [ Nat.cast_sub ];
      · unfold h_b; ring;
        grind;
      · rw [ ← h_disagreements ];
        exact Finset.sum_le_sum fun i hi => Finset.card_le_card fun x hx => by aesop;
    · rw [ ← h_disagreements ];
      norm_num [ Finset.sum_filter ];
      congr! 3
/-
The NLL grows asymptotically as `K * log2(T) + O(1)`, where `K` is the total number of transient disagreements.
-/
lemma nll_asymptotic (U : Spacetime X) (p : ℕ) (s : X) (T0 : ℕ) (hp : p > 0) (h_eventual : EventuallyPeriodic U p s T0) :
  Asymptotics.IsBigO Filter.atTop (fun T => NLL U p s T hp - (∑ idx : (Fin p) × X, (k_inf U p s T0 hp h_eventual idx : ℝ)) * Real.logb 2 T) (fun T => (1 : Real)) := by
    -- Apply the lemma `nll_term_eq_k_inf` to each term in the sum.
    have h_term : ∀ idx : (Fin p) × X, (fun T => (if (count_in_class U p s T idx hp).1 = 0 then (0 : ℝ) else (count_in_class U p s T idx hp).1 * h_b ((k_inf U p s T0 hp h_eventual idx : ℝ) / (count_in_class U p s T idx hp).1)) - (k_inf U p s T0 hp h_eventual idx : ℝ) * Real.logb 2 (T : ℝ)) =O[Filter.atTop] (fun _ => 1 : ℕ → ℝ) := by
      intro idx
      have h_count_growth : Asymptotics.IsBigO Filter.atTop (fun T => (count_in_class U p s T idx hp).1 - (T : ℝ) / p) (fun _ => (1 : ℝ)) := by
        -- The count_in_class is the sum of the number of points in each time step, which is T/p plus some error term.
        have h_count_in_class : ∀ T ≥ T0, (count_in_class U p s T idx hp).1 = ∑ t ∈ Finset.range T, (if t % p = idx.1.val then 1 else 0) := by
          intro T hT
          simp [count_in_class, orbitIndex];
          rw [ Finset.card_filter ];
          refine' Finset.sum_congr rfl fun i hi => _;
          split_ifs <;> simp_all +decide [ Fin.ext_iff, Prod.ext_iff ];
          exact Finset.card_eq_one.mpr ⟨ idx.2 + ( i / p ) • s, by ext x; simp +decide [ sub_eq_iff_eq_add ] ⟩;
        -- The sum of the number of points in each time step is equal to the number of times the condition holds, which is T/p plus some error term.
        have h_sum : ∀ T ≥ T0, (∑ t ∈ Finset.range T, (if t % p = idx.1.val then 1 else 0)) = (T / p : ℕ) + (if idx.1.val < T % p then 1 else 0) := by
          intro T hT
          have h_sum : Finset.card (Finset.filter (fun t => t % p = idx.1.val) (Finset.range T)) = Finset.card (Finset.image (fun t => p * t + idx.1.val) (Finset.range (T / p + (if idx.1.val < T % p then 1 else 0)))) := by
            congr with t ; simp +decide [ Nat.mod_eq_of_lt ];
            constructor <;> intro h;
            · use t / p;
              exact ⟨ by split_ifs <;> nlinarith [ Nat.mod_add_div t p, Nat.mod_add_div T p, Nat.mod_lt t hp, Nat.mod_lt T hp ], by linarith [ Nat.mod_add_div t p ] ⟩;
            · rcases h with ⟨ a, ha, rfl ⟩ ; split_ifs at ha <;> simp_all +decide [ Nat.mod_eq_of_lt ] ; nlinarith [ Nat.div_add_mod T p, Nat.mod_lt T hp ] ;
              nlinarith [ Nat.div_mul_le_self T p, Nat.mod_add_div T p, Fin.is_lt idx.1 ];
          rw [ Finset.card_image_of_injective _ fun x y hxy => by nlinarith ] at h_sum ; aesop;
        rw [ Asymptotics.isBigO_iff ];
        use 2 + 1 / p; filter_upwards [ Filter.eventually_ge_atTop T0 ] with T hT; rw [ h_count_in_class T hT, h_sum T hT ] ; norm_num [ abs_le ] ; ring_nf ;
        field_simp;
        split_ifs <;> constructor <;> nlinarith [ show ( p : ℝ ) ≥ 1 by exact_mod_cast hp, show ( T : ℝ ) ≥ p * ( T / p : ℕ ) by exact_mod_cast Nat.mul_div_le _ _, show ( T : ℝ ) < p * ( T / p : ℕ ) + p by exact_mod_cast by linarith [ Nat.div_add_mod T p, Nat.mod_lt T hp ] ] ;
      have h_entropic_term : Asymptotics.IsBigO Filter.atTop (fun T => (count_in_class U p s T idx hp).1 * h_b ((k_inf U p s T0 hp h_eventual idx : ℝ) / (count_in_class U p s T idx hp).1) - (k_inf U p s T0 hp h_eventual idx : ℝ) * Real.logb 2 ((count_in_class U p s T idx hp).1 : ℝ)) (fun _ => (1 : ℝ)) := by
        have := @entropy_asymptotic;
        convert this ( k_inf U p s T0 hp h_eventual idx ) |> Asymptotics.IsBigO.comp_tendsto <| show Filter.Tendsto ( fun T : ℕ => ( count_in_class U p s T idx hp |>.1 : ℕ ) ) Filter.atTop Filter.atTop from ?_ using 1;
        -- Since $n = T/p + O(1)$, we have $n \to \infty$ as $T \to \infty$.
        have h_n_inf : Filter.Tendsto (fun T => (T : ℝ) / p) Filter.atTop Filter.atTop := by
          exact Filter.tendsto_id.atTop_mul_const ( by positivity );
        rw [ Filter.tendsto_atTop_atTop ] at *;
        rw [ Asymptotics.isBigO_iff ] at h_count_growth;
        norm_num +zetaDelta at *;
        obtain ⟨ c, a, hc ⟩ := h_count_growth; intro b; rcases h_n_inf ( b + c + 1 ) with ⟨ i, hi ⟩ ; exact ⟨ ⌈i⌉₊ + a, fun n hn => by have := hi n ( Nat.le_of_ceil_le ( by linarith ) ) ; have := hc n ( by linarith ) ; rw [ abs_le ] at this; push_cast [ ← @Nat.cast_le ℝ .. ] at *; linarith ⟩ ;
      have h_log_term : Asymptotics.IsBigO Filter.atTop (fun T => (count_in_class U p s T idx hp).1 - (T : ℝ) / p) (fun _ => (1 : ℝ)) := by
        exact h_count_growth
      have h_log_term : Asymptotics.IsBigO Filter.atTop (fun T => Real.logb 2 ((count_in_class U p s T idx hp).1 : ℝ) - Real.logb 2 (T : ℝ)) (fun _ => (1 : ℝ)) := by
        have h_log_term : Asymptotics.IsBigO Filter.atTop (fun T => Real.logb 2 ((count_in_class U p s T idx hp).1 : ℝ) - Real.logb 2 (T / p : ℝ)) (fun _ => (1 : ℝ)) := by
          have h_log_term : ∀ᶠ T in Filter.atTop, (count_in_class U p s T idx hp).1 ≥ (T / p : ℝ) / 2 := by
            rw [ Asymptotics.isBigO_iff ] at h_log_term;
            norm_num +zetaDelta at *;
            obtain ⟨ c, a, h ⟩ := h_log_term; use ⌈2 * c * p⌉₊ + a + 1; intro b hb; have := h b ( by linarith ) ; rw [ abs_le ] at this; nlinarith [ Nat.le_ceil ( 2 * c * p ), show ( b : ℝ ) ≥ ⌈2 * c * p⌉₊ + a + 1 by exact_mod_cast hb, show ( p : ℝ ) > 0 by positivity, mul_div_cancel₀ ( b : ℝ ) ( by positivity : ( p : ℝ ) ≠ 0 ) ] ;
          have h_log_term : ∀ᶠ T in Filter.atTop, Real.logb 2 ((count_in_class U p s T idx hp).1 : ℝ) ≤ Real.logb 2 (T / p : ℝ) + Real.logb 2 2 := by
            have h_log_term : ∀ᶠ T in Filter.atTop, (count_in_class U p s T idx hp).1 ≤ (T / p : ℝ) * 2 := by
              rw [ Asymptotics.isBigO_iff ] at h_count_growth;
              obtain ⟨ c, hc ⟩ := h_count_growth; filter_upwards [ hc, Filter.eventually_gt_atTop ⌈c * 2 * p⌉₊ ] with T hT₁ hT₂; norm_num at *; nlinarith [ Nat.le_ceil ( c * 2 * p ), show ( T : ℝ ) ≥ ⌈c * 2 * p⌉₊ + 1 by exact_mod_cast hT₂, abs_le.mp hT₁, show ( p : ℝ ) > 0 by positivity, mul_div_cancel₀ ( T : ℝ ) ( show ( p : ℝ ) ≠ 0 by positivity ) ] ;
            filter_upwards [ h_log_term, ‹∀ᶠ T in Filter.atTop, ( count_in_class U p s T idx hp |>.1 : ℝ ) ≥ T / p / 2›, Filter.eventually_gt_atTop 0 ] with T hT₁ hT₂ hT₃ ; rw [ ← Real.logb_mul ( by positivity ) ( by positivity ) ] ; gcongr ; aesop;
            exact lt_of_lt_of_le ( by positivity ) hT₂;
          have h_log_term : ∀ᶠ T in Filter.atTop, Real.logb 2 ((count_in_class U p s T idx hp).1 : ℝ) ≥ Real.logb 2 (T / p : ℝ) - Real.logb 2 2 := by
            filter_upwards [ ‹∀ᶠ T in Filter.atTop, ( count_in_class U p s T idx hp |>.1 : ℝ ) ≥ T / p / 2›, Filter.eventually_gt_atTop 0 ] with T hT₁ hT₂ ; rw [ ge_iff_le ] ; rw [ sub_le_iff_le_add ] ; rw [ Real.logb_le_iff_le_rpow, Real.rpow_add, Real.rpow_logb ] <;> norm_num <;> try positivity;
            · linarith [ show ( T : ℝ ) / p ≥ 0 by positivity ];
            · contrapose! hT₁; aesop;
          rw [ Asymptotics.isBigO_iff ] at *;
          norm_num +zetaDelta at *;
          exact ⟨ 1, Max.max ( Classical.choose ‹∃ a, ∀ b : ℕ, a ≤ b → Real.logb 2 ( b / p : ℝ ) ≤ Real.logb 2 ( count_in_class U p s b idx hp |>.1 : ℝ ) + 1› ) ( Classical.choose ‹∃ a, ∀ b : ℕ, a ≤ b → Real.logb 2 ( count_in_class U p s b idx hp |>.1 : ℝ ) ≤ Real.logb 2 ( b / p : ℝ ) + 1› ), fun n hn => abs_le.mpr ⟨ by linarith [ Classical.choose_spec ‹∃ a, ∀ b : ℕ, a ≤ b → Real.logb 2 ( b / p : ℝ ) ≤ Real.logb 2 ( count_in_class U p s b idx hp |>.1 : ℝ ) + 1› n ( le_trans ( le_max_left _ _ ) hn ) ], by linarith [ Classical.choose_spec ‹∃ a, ∀ b : ℕ, a ≤ b → Real.logb 2 ( count_in_class U p s b idx hp |>.1 : ℝ ) ≤ Real.logb 2 ( b / p : ℝ ) + 1› n ( le_trans ( le_max_right _ _ ) hn ) ] ⟩ ⟩;
        have h_log_term : Asymptotics.IsBigO Filter.atTop (fun T => Real.logb 2 (T / p : ℝ) - Real.logb 2 (T : ℝ)) (fun _ => (1 : ℝ)) := by
          norm_num [ Real.logb_div, hp.ne' ];
          refine' ⟨ |Real.logb 2 ( 1 / p : ℝ ) - 0|, Filter.eventually_atTop.mpr ⟨ 1, fun x hx => _ ⟩ ⟩ ; norm_num [ Real.logb_div, hp.ne' ];
          rw [ Real.logb_div ( by positivity ) ( by positivity ) ] ; ring_nf ; norm_num [ abs_of_nonneg, Real.logb_nonneg ] ;
        have h_log_term : Asymptotics.IsBigO Filter.atTop (fun T => (Real.logb 2 ((count_in_class U p s T idx hp).1 : ℝ) - Real.logb 2 (T / p : ℝ)) + (Real.logb 2 (T / p : ℝ) - Real.logb 2 (T : ℝ))) (fun _ => (1 : ℝ)) := by
          exact Asymptotics.IsBigO.add ‹_› ( h_log_term.comp_tendsto tendsto_natCast_atTop_atTop );
        exact h_log_term.congr ( by intros; ring ) ( by intros; ring )
      have h_combined : Asymptotics.IsBigO Filter.atTop (fun T => (count_in_class U p s T idx hp).1 * h_b ((k_inf U p s T0 hp h_eventual idx : ℝ) / (count_in_class U p s T idx hp).1) - (k_inf U p s T0 hp h_eventual idx : ℝ) * Real.logb 2 (T : ℝ)) (fun _ => (1 : ℝ)) := by
        have h_combined : Asymptotics.IsBigO Filter.atTop (fun T => (count_in_class U p s T idx hp).1 * h_b ((k_inf U p s T0 hp h_eventual idx : ℝ) / (count_in_class U p s T idx hp).1) - (k_inf U p s T0 hp h_eventual idx : ℝ) * Real.logb 2 ((count_in_class U p s T idx hp).1 : ℝ) + (k_inf U p s T0 hp h_eventual idx : ℝ) * (Real.logb 2 ((count_in_class U p s T idx hp).1 : ℝ) - Real.logb 2 (T : ℝ))) (fun _ => (1 : ℝ)) := by
          exact h_entropic_term.add ( h_log_term.const_mul_left _ );
        convert h_combined using 2 ; ring
      exact h_combined.congr' (by
      filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by aesop;) (by
      rfl);
    have h_sum : (fun T => (∑ idx : (Fin p) × X, (if (count_in_class U p s T idx hp).1 = 0 then (0 : ℝ) else (count_in_class U p s T idx hp).1 * h_b ((k_inf U p s T0 hp h_eventual idx : ℝ) / (count_in_class U p s T idx hp).1))) - (∑ idx : (Fin p) × X, (k_inf U p s T0 hp h_eventual idx : ℝ)) * Real.logb 2 (T : ℝ)) =O[Filter.atTop] (fun _ => 1 : ℕ → ℝ) := by
      simpa [ Finset.sum_mul _ _ _ ] using Asymptotics.IsBigO.sum fun i _ => h_term i;
    refine' h_sum.congr' _ _;
    · filter_upwards [ Filter.eventually_gt_atTop T0 ] with T hT;
      simp +decide [ NLL, nll_term_eq_k_inf U p s T0 hp h_eventual _ T hT.le ];
    · rfl
/-
Theorem 5(ii): The NLL difference satisfies NLL(p, T) - NLL(p₀, T) = O(1).
-/
theorem theorem_5_ii {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0
  Asymptotics.IsBigO Filter.atTop (fun T => NLL U p s_p T hp - NLL U p0 s T hp0) (fun T => (1 : Real)) := by
    -- By Lemma `nll_asymptotic`, both `NLL(U, p, T)` and `NLL(U, p0, T)` are asymptotically `K * log2(T) + O(1)`.
    have h_asymptotic : ∀ p s hp h_eventual, Asymptotics.IsBigO Filter.atTop (fun T => NLL U p s T hp - (∑ idx : (Fin p) × X, (k_inf U p s T0 hp h_eventual idx : ℝ)) * Real.logb 2 T) (fun T => (1 : ℝ)) := by
      exact?;
    have h_coeff : (∑ idx : (Fin (m * p0)) × X, (k_inf U (m * p0) (m • s) T0 (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0) (eventually_periodic_multiple U p0 s T0 h_eventual m (Nat.lt_trans Nat.zero_lt_one hm)) idx : ℝ)) = (∑ idx0 : (Fin p0) × X, (k_inf U p0 s T0 hp0 h_eventual idx0 : ℝ)) := by
      exact_mod_cast k_inf_sum_eq U p0 s T0 hp0 h_eventual m hm;
    convert Asymptotics.IsBigO.sub ( h_asymptotic ( m * p0 ) ( m • s ) ( Nat.mul_pos ( Nat.lt_trans Nat.zero_lt_one hm ) hp0 ) ( eventually_periodic_multiple U p0 s T0 h_eventual m ( Nat.lt_trans Nat.zero_lt_one hm ) ) ) ( h_asymptotic p0 s hp0 h_eventual ) using 2 ; aesop
/-
Definition of COMP and its asymptotic behavior.
-/
noncomputable def COMP (U : Spacetime X) (p : ℕ) (s : X) (T : ℕ) (hp : p > 0) : Real :=
  Finset.univ.sum (fun (idx : (Fin p) × X) =>
    let (n, _) := count_in_class U p s T idx hp
    if n = 0 then 0 else 0.5 * Real.logb 2 n
  )
lemma comp_asymptotic (U : Spacetime X) (p : ℕ) (s : X) (hp : p > 0) :
  Asymptotics.IsBigO Filter.atTop (fun T => COMP U p s T hp - (p * Fintype.card X : ℝ) / 2 * Real.logb 2 T) (fun T => (1 : Real)) := by
    -- Let's simplify the expression for the complexity term.
    have h_simplify : ∀ T ≥ p, COMP U p s T hp = (p * Fintype.card X / 2) * Real.logb 2 T + (∑ idx : (Fin p) × X, 0.5 * Real.logb 2 ((count_in_class U p s T idx hp).1 / T)) := by
      unfold COMP;
      intro T hT
      have h_count : ∀ idx : (Fin p) × X, (count_in_class U p s T idx hp).1 = T / p + (if (idx.1 : ℕ) < T % p then 1 else 0) := by
        intro idx
        unfold count_in_class
        simp [orbitIndex];
        -- Let's simplify the sum by considering the condition $(⟨x % p, ⋯⟩, x_1 - (x / p) • s) = idx$.
        have h_sum : ∑ x ∈ Finset.range T, (Finset.card (Finset.filter (fun x_1 => (⟨x % p, Nat.mod_lt _ hp⟩, x_1 - (x / p) • s) = idx) Finset.univ)) = ∑ x ∈ Finset.range T, (if x % p = idx.1.val then 1 else 0) := by
          refine' Finset.sum_congr rfl fun x hx => _;
          split_ifs <;> simp_all +decide [ Fin.ext_iff, Prod.ext_iff ];
          exact Finset.card_eq_one.mpr ⟨ idx.2 + ( x / p ) • s, by ext; simp +decide [ sub_eq_iff_eq_add ] ⟩;
        simp_all +decide [ Finset.sum_ite ];
        have h_card : Finset.filter (fun x => x % p = idx.1.val) (Finset.range T) = Finset.image (fun k => k * p + idx.1.val) (Finset.range (T / p + if idx.1.val < T % p then 1 else 0)) := by
          ext x; simp [Finset.mem_image];
          constructor;
          · intro hx
            use x / p;
            exact ⟨ by split_ifs <;> nlinarith [ Nat.mod_add_div x p, Nat.mod_add_div T p, Nat.mod_lt x hp, Nat.mod_lt T hp ], by linarith [ Nat.mod_add_div x p ] ⟩;
          · rintro ⟨ a, ha, rfl ⟩ ; split_ifs at ha <;> simp_all +decide [ Nat.mod_eq_of_lt ] ; nlinarith [ Nat.div_add_mod T p, Nat.mod_lt T hp ] ;
            nlinarith [ Nat.div_mul_le_self T p, Fin.is_lt idx.1 ];
        rw [ h_card, Finset.card_image_of_injective ] <;> simp +decide [ Function.Injective, hp.ne' ];
      rw [ Finset.sum_congr rfl fun x hx => ?_ ];
      any_goals exact fun x => 0.5 * Real.logb 2 ( ( count_in_class U p s T x hp |>.1 ) / T ) + 0.5 * Real.logb 2 T;
      · simp +decide [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul, h_count ] ; ring;
      · by_cases h : ( count_in_class U p s T x hp |>.1 ) = 0 <;> simp +decide [ h, Real.logb_div ];
        · exact absurd h ( by rw [ h_count ] ; exact ne_of_gt ( add_pos_of_pos_of_nonneg ( Nat.div_pos ( by linarith ) hp ) ( Nat.zero_le _ ) ) );
        · rw [ Real.logb_div ( by positivity ) ( by norm_cast; linarith ) ] ; ring;
    -- Since each count_in_class U p s T idx hp.1 is asymptotically equivalent to T/p, the ratio (count_in_class U p s T idx hp.1) / T is asymptotically equivalent to 1/p.
    have h_ratio : ∀ idx : (Fin p) × X, Filter.Tendsto (fun T : ℕ => (count_in_class U p s T idx hp).1 / (T : ℝ)) Filter.atTop (nhds (1 / p)) := by
      intro idx
      have h_count : ∀ T ≥ p, (count_in_class U p s T idx hp).1 = Finset.card (Finset.filter (fun t => t % p = idx.1.val) (Finset.range T)) := by
        intro T hT
        simp [count_in_class, orbitIndex];
        rw [ Finset.card_filter ];
        refine' Finset.sum_congr rfl fun i hi => _;
        split_ifs <;> simp_all +decide [ Fin.ext_iff, Prod.ext_iff ];
        exact Finset.card_eq_one.mpr ⟨ idx.2 + ( i / p ) • s, by ext x; simp +decide [ sub_eq_iff_eq_add ] ⟩
      simp_all +decide [ Finset.card_range, Nat.div_eq_of_lt ];
      -- The number of integers $t$ in the range $0$ to $T-1$ such that $t \equiv idx.1 \pmod{p}$ is approximately $T/p$.
      have h_card_approx : ∀ T ≥ p, (Finset.card (Finset.filter (fun t => t % p = idx.1.val) (Finset.range T))) ≤ T / p + 1 ∧ (Finset.card (Finset.filter (fun t => t % p = idx.1.val) (Finset.range T))) ≥ T / p := by
        intro T hT
        have h_card_approx : Finset.card (Finset.filter (fun t => t % p = idx.1.val) (Finset.range T)) ≤ Finset.card (Finset.image (fun t => t * p + idx.1.val) (Finset.range (T / p + 1))) := by
          refine Finset.card_mono ?_;
          exact fun x hx => Finset.mem_image.mpr ⟨ x / p, Finset.mem_range.mpr ( Nat.lt_succ_of_le ( Nat.div_le_div_right ( Finset.mem_range_le ( Finset.mem_filter.mp hx |>.1 ) ) ) ), by linarith [ Nat.mod_add_div x p, Finset.mem_filter.mp hx |>.2 ] ⟩;
        refine' ⟨ h_card_approx.trans ( Finset.card_image_le.trans ( by simp +decide ) ), _ ⟩;
        refine' le_trans _ ( Finset.card_mono <| show Finset.image ( fun t => t * p + idx.1 ) ( Finset.range ( T / p ) ) ⊆ Finset.filter ( fun t => t % p = idx.1 ) ( Finset.range T ) from _ );
        · rw [ Finset.card_image_of_injective ] <;> norm_num [ Function.Injective, hp.ne' ];
        · simp +decide [ Finset.subset_iff ];
          exact fun a ha => ⟨ by nlinarith [ Nat.div_mul_le_self T p, Fin.is_lt idx.1 ], Nat.mod_eq_of_lt ( Fin.is_lt idx.1 ) ⟩;
      -- Using the approximation, we can bound the ratio.
      have h_ratio_bound : ∀ T ≥ p, abs ((count_in_class U p s T idx hp).1 / (T : ℝ) - 1 / p) ≤ 2 / (T : ℝ) := by
        intro T hT; rw [ h_count T hT ] ; rw [ abs_le ] ; constructor <;> ring_nf <;> norm_num [ hp.ne' ];
        · field_simp;
          rw [ le_div_iff₀ ] <;> norm_cast <;> nlinarith [ h_card_approx T hT, Nat.div_add_mod T p, Nat.mod_lt T hp ];
        · field_simp;
          rw [ div_add_one, div_le_div_iff_of_pos_right ] <;> norm_cast <;> nlinarith [ h_card_approx T hT, Nat.div_mul_le_self T p, Nat.div_add_mod T p, Nat.mod_lt T hp ];
      exact tendsto_iff_norm_sub_tendsto_zero.mpr ( squeeze_zero_norm' ( Filter.eventually_atTop.mpr ⟨ p, fun T hT => by simpa using h_ratio_bound T hT ⟩ ) ( tendsto_const_nhds.div_atTop tendsto_natCast_atTop_atTop ) ) |> fun h => h.trans ( by simp +decide );
    -- Since the logarithm function is continuous, the sum of the logarithms of the ratios is also asymptotically equivalent to the sum of the logarithms of 1/p.
    have h_log_ratio : Filter.Tendsto (fun T : ℕ => ∑ idx : (Fin p) × X, 0.5 * Real.logb 2 ((count_in_class U p s T idx hp).1 / T)) Filter.atTop (nhds (∑ idx : (Fin p) × X, 0.5 * Real.logb 2 (1 / p))) := by
      exact tendsto_finset_sum _ fun _ _ => Filter.Tendsto.mul tendsto_const_nhds ( Filter.Tendsto.div_const ( Filter.Tendsto.log ( h_ratio _ ) ( by positivity ) ) _ );
    rw [ Asymptotics.isBigO_iff ];
    obtain ⟨ c, hc ⟩ := h_log_ratio.abs.bddAbove_range;
    exact ⟨ c, Filter.eventually_atTop.mpr ⟨ p, fun T hT => by rw [ h_simplify T hT ] ; simpa using hc ⟨ T, rfl ⟩ ⟩ ⟩
/-
Theorem 5(iii): The NML score difference satisfies NML(p, T) - NML(p₀, T) = (m-1)·k_{p₀}/2 · log₂ T + O(1).
-/
theorem theorem_5_iii {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0
  let k_p0 := (p0 * Fintype.card X : ℝ)
  Asymptotics.IsBigO Filter.atTop (fun T => NML U p s_p T hp - NML U p0 s T hp0 - (m - 1 : ℝ) * k_p0 / 2 * Real.logb 2 T) (fun T => (1 : Real)) := by
    -- By combining the results from the previous lemmas, we can conclude the proof.
    have h_combined : (fun T => (NLL U (m * p0) (m • s) T (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0)) - (NLL U p0 s T hp0)) =O[Filter.atTop] (fun T : ℕ => 1 : ℕ → ℝ) ∧ (fun T => (COMP U (m * p0) (m • s) T (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0)) - (COMP U p0 s T hp0) - ((m - 1) * (p0 * Fintype.card X) / 2 : ℝ) * Real.logb 2 (T : ℝ)) =O[Filter.atTop] (fun T : ℕ => 1 : ℕ → ℝ) := by
      constructor;
      · exact?;
      · -- Apply the lemma comp_asymptotic to both p and p0 to express the differences in terms of the logarithmic terms.
        have h_comp_diff : (fun T => COMP U (m * p0) (m • s) T (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0) - (m * p0 * Fintype.card X / 2 : ℝ) * Real.logb 2 T) =O[Filter.atTop] (fun T : ℕ => 1 : ℕ → ℝ) ∧ (fun T => COMP U p0 s T hp0 - (p0 * Fintype.card X / 2 : ℝ) * Real.logb 2 T) =O[Filter.atTop] (fun T : ℕ => 1 : ℕ → ℝ) := by
          apply And.intro;
          · convert comp_asymptotic U ( m * p0 ) ( m • s ) ( Nat.mul_pos ( Nat.lt_trans Nat.zero_lt_one hm ) hp0 ) using 1;
            norm_num;
          · convert comp_asymptotic U p0 s hp0 using 1;
        convert h_comp_diff.1.sub h_comp_diff.2 using 2 ; ring;
    convert h_combined.1.add h_combined.2 using 2 ; unfold NML ; ring!
/-
Theorem 5(iv): NML selects p₀ over p for all sufficiently large T (i.e., NML(p) > NML(p0) eventually).
-/
theorem theorem_5_iv {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0
  ∀ᶠ T in Filter.atTop, NML U p s_p T hp > NML U p0 s T hp0 := by
    -- From theorem_5_iii, NML(p) - NML(p0) = C * log2(T) + O(1), where C = (m-1)*p0*|X|/2.
    have h_diff : ∃ C : ℝ, 0 < C ∧ Asymptotics.IsBigO Filter.atTop (fun T => NML U (m * p0) (m • s) T (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0) - NML U p0 s T hp0 - C * Real.logb 2 T) (fun T => (1 : Real)) := by
      use (m - 1) * (p0 * Fintype.card X) / 2;
      refine' ⟨ div_pos ( mul_pos ( sub_pos.mpr ( Nat.one_lt_cast.mpr hm ) ) ( mul_pos ( Nat.cast_pos.mpr hp0 ) ( Nat.cast_pos.mpr ( Fintype.card_pos_iff.mpr ⟨ 0 ⟩ ) ) ) ) zero_lt_two, _ ⟩;
      convert theorem_5_iii U p0 s T0 hp0 h_eventual m hm using 1;
    obtain ⟨ C, hC₀, hC ⟩ := h_diff;
    -- Since $C > 0$, we have $C * \log_2(T) \to \infty$ as $T \to \infty$.
    have h_log_inf : Filter.Tendsto (fun T : ℕ => C * Real.logb 2 T) Filter.atTop Filter.atTop := by
      exact Filter.Tendsto.const_mul_atTop hC₀ ( Real.tendsto_logb_atTop ( by norm_num ) |> Filter.Tendsto.comp <| tendsto_natCast_atTop_atTop );
    rw [ Asymptotics.isBigO_iff ] at hC;
    obtain ⟨ c, hc ⟩ := hC;
    filter_upwards [ hc, h_log_inf.eventually_gt_atTop ( c + 1 ) ] with T hT₁ hT₂ using by norm_num at *; linarith [ abs_le.mp hT₁ ] ;
/-
Theorem 5(i): The per-site NLL rates are equal to 0 (formalized as NLL being o(T)).
-/
theorem theorem_5_i_proved {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  Asymptotics.IsLittleO Filter.atTop (fun T => NLL U (m * p0) (m • s) T (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0)) (fun T : ℕ => (T : Real)) ∧
  Asymptotics.IsLittleO Filter.atTop (fun T => NLL U p0 s T hp0) (fun T : ℕ => (T : Real)) := by
    convert theorem_5_i U p0 s T0 hp0 h_eventual m hm using 1
/-
Theorem 5(i): The per-site NLL rates are equal to 0.
-/
theorem theorem_5_i_proof {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  Asymptotics.IsLittleO Filter.atTop (fun T => NLL U (m * p0) (m • s) T (Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0)) (fun T : ℕ => (T : Real)) ∧
  Asymptotics.IsLittleO Filter.atTop (fun T => NLL U p0 s T hp0) (fun T : ℕ => (T : Real)) := by
    convert theorem_5_i_proved U p0 s T0 hp0 h_eventual m hm using 1
/-
Theorem 5(ii): The NLL difference satisfies NLL(p, T) - NLL(p₀, T) = O(1).
-/
theorem theorem_5_ii_proof {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0
  Asymptotics.IsBigO Filter.atTop (fun T => NLL U p s_p T hp - NLL U p0 s T hp0) (fun T => (1 : Real)) := by
    -- Apply the lemma that states the NLL difference is O(1).
    apply theorem_5_ii U p0 s T0 hp0 h_eventual m hm
/-
Theorem 5(iii): The NML score difference satisfies NML(p, T) - NML(p₀, T) = (m-1)·k_{p₀}/2 · log₂ T + O(1).
-/
theorem theorem_5_iii_proof {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0
  let k_p0 := (p0 * Fintype.card X : ℝ)
  Asymptotics.IsBigO Filter.atTop (fun T => NML U p s_p T hp - NML U p0 s T hp0 - (m - 1 : ℝ) * k_p0 / 2 * Real.logb 2 T) (fun T => (1 : Real)) := by
    convert theorem_5_iii U p0 s T0 hp0 h_eventual m hm using 1
/-
Theorem 5(iv): NML selects p₀ over p for all sufficiently large T.
-/
theorem theorem_5_iv_proof {X : Type*} [AddCommGroup X] [Fintype X] [DecidableEq X]
  (U : Spacetime X) (p0 : ℕ) (s : X) (T0 : ℕ)
  (hp0 : p0 > 0)
  (h_eventual : EventuallyPeriodic U p0 s T0)
  (m : ℕ) (hm : m > 1) :
  let p := m * p0
  let s_p := m • s
  have hp : p > 0 := Nat.mul_pos (Nat.lt_trans Nat.zero_lt_one hm) hp0
  ∀ᶠ T in Filter.atTop, NML U p s_p T hp > NML U p0 s T hp0 := by
    convert theorem_5_iv U p0 s T0 hp0 h_eventual m hm using 1
