/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e9677485-57a8-4d79-b2db-275b02c80f54

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of Theorem 1: Optimal Hamming Projection.

We define the setting with a finite type `I` (representing the spacetime) and a setoid `S` (representing the orbit classes).
We define `count_ones` and `count_zeros` to count the number of 1s and 0s in a subset of indices.
We define `hamming_dist` as the number of positions where two binary fields differ.
We define `ModelClass` as the set of binary fields that are constant on each orbit class.
We define `is_majority_vote` for a field that follows the majority rule on each orbit class.

We prove the following results:
1. `majority_vote_minimizes_hamming_dist`: The majority vote minimizes the Hamming distance among all fields in the ModelClass.
2. `minimum_residual_count`: The minimum Hamming distance is the sum of the minimum of zeros and ones in each orbit class.
3. `unique_minimizer_iff`: The minimizer is unique if and only if no orbit class has equal counts of zeros and ones.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Define count_ones, count_zeros, hamming_dist, and is_constant_on.
-/
variable {I : Type*} [Fintype I] [DecidableEq I]

/-- The count of ones in a subset of indices for a binary field U. -/
def count_ones (U : I → Bool) (s : Set I) [Fintype s] : ℕ :=
  Fintype.card {i : s // U i = true}

/-- The count of zeros in a subset of indices for a binary field U. -/
def count_zeros (U : I → Bool) (s : Set I) [Fintype s] : ℕ :=
  Fintype.card {i : s // U i = false}

/-- The Hamming distance between two binary fields. -/
def hamming_dist (U V : I → Bool) : ℕ :=
  Fintype.card {i // U i ≠ V i}

/-- A field is constant on a set if it takes the same value for all elements in the set. -/
def is_constant_on (B : I → Bool) (s : Set I) : Prop :=
  ∀ i j, i ∈ s → j ∈ s → B i = B j

/-
Define ModelClass and is_majority_vote.
-/
variable {I : Type*} [Fintype I] [DecidableEq I]

/-- The class of binary fields constant on each orbit class of S. -/
def ModelClass (S : Setoid I) : Set (I → Bool) :=
  {B | ∀ c ∈ S.classes, is_constant_on B c}

/-- A field is a majority vote if it follows the majority rule on each class. -/
def is_majority_vote (U : I → Bool) (S : Setoid I) (B : I → Bool) : Prop :=
  B ∈ ModelClass S ∧
  ∀ c ∈ S.classes,
    (count_ones U c > count_zeros U c → ∀ i ∈ c, B i = true) ∧
    (count_zeros U c > count_ones U c → ∀ i ∈ c, B i = false)

/-
Define hamming_dist_on and prove that the total Hamming distance is the sum of Hamming distances on each orbit class.
-/
variable {I : Type*} [Fintype I] [DecidableEq I]

/-- The Hamming distance between two binary fields restricted to a set s. -/
def hamming_dist_on (U V : I → Bool) (s : Set I) [Fintype s] : ℕ :=
  Fintype.card {i : s // U i ≠ V i}

theorem hamming_dist_decomposition (U B : I → Bool) (S : Setoid I) :
  hamming_dist U B = ∑ c ∈ S.classes, hamming_dist_on U B c := by
    simp +decide only [hamming_dist, hamming_dist_on];
    simp +decide only [Finset.card_filter, Fintype.card_subtype];
    -- By definition of equivalence classes, every element in $I$ belongs to exactly one equivalence class.
    have h_partition : ∀ x : I, ∃! c : Set I, c ∈ S.classes ∧ x ∈ c := by
      exact fun x => Setoid.classes_eqv_classes x;
    choose f hf hf' using h_partition;
    have h_partition : ∑ x : I, (if U x ≠ B x then 1 else 0) = ∑ c ∈ S.classes.toFinset, ∑ x ∈ Finset.univ.filter (fun x => f x = c), (if U x ≠ B x then 1 else 0) := by
      rw [ ← Finset.sum_biUnion ];
      · congr with x ; aesop;
      · intro c hc d hd hcd; simp_all +decide [ Finset.disjoint_left ] ;
    convert h_partition using 2;
    refine' Finset.sum_bij ( fun x _ => x ) _ _ _ _ <;> simp +decide;
    · exact fun x hx => hf' x _ ⟨ by aesop, hx ⟩ ▸ rfl;
    · exact fun x hx => hx ▸ hf x |>.2

/-
If B is constant v on c, then the Hamming distance on c is count_zeros U c if v is true, and count_ones U c if v is false.
-/
variable {I : Type*} [Fintype I] [DecidableEq I]

lemma hamming_dist_on_constant (U : I → Bool) (c : Set I) [Fintype c] (v : Bool) :
  hamming_dist_on U (fun _ => v) c = if v then count_zeros U c else count_ones U c := by
    unfold hamming_dist_on count_zeros count_ones;
    split_ifs <;> simp +decide [ *, Fintype.card_subtype ]

/-
The minimum of the count of zeros and ones is a lower bound for the Hamming distance on c for any constant field.
-/
variable {I : Type*} [Fintype I] [DecidableEq I]

lemma min_hamming_dist_on_constant (U : I → Bool) (c : Set I) [Fintype c] (v : Bool) :
  min (count_zeros U c) (count_ones U c) ≤ hamming_dist_on U (fun _ => v) c := by
    cases v <;> rw [ hamming_dist_on_constant U c ] <;> aesop

/-
If B is a majority vote, then it minimizes the Hamming distance among all fields in the ModelClass.
-/
variable {I : Type*} [Fintype I] [DecidableEq I]

theorem majority_vote_minimizes_hamming_dist (U : I → Bool) (S : Setoid I) (B : I → Bool)
    (hB : is_majority_vote U S B) :
    ∀ B' ∈ ModelClass S, hamming_dist U B ≤ hamming_dist U B' := by
      intro B' hB';
      -- By definition of Hamming distance, we can split the sum into the sum over each orbit class.
      have h_split : hamming_dist U B = ∑ c ∈ S.classes, hamming_dist_on U B c ∧ hamming_dist U B' = ∑ c ∈ S.classes, hamming_dist_on U B' c := by
        constructor <;> rw [ hamming_dist_decomposition ];
      rw [ h_split.1, h_split.2 ];
      refine' Finset.sum_le_sum _;
      intro c hc
      have h_const : ∃ v : Bool, ∀ i ∈ c, B i = v := by
        have := hB.1 c ( by aesop );
        by_cases hc_empty : c.Nonempty;
        · exact ⟨ B hc_empty.some, fun i hi => this _ _ hi hc_empty.choose_spec ⟩;
        · exact ⟨ Bool.true, fun i hi => False.elim <| hc_empty ⟨ i, hi ⟩ ⟩
      obtain ⟨v, hv⟩ := h_const
      have h_const' : ∃ v' : Bool, ∀ i ∈ c, B' i = v' := by
        obtain ⟨ i, hi ⟩ := Set.mem_setOf.mp ( Setoid.mem_classes S |> fun h => by aesop : c ∈ S.classes ) ; use B' i; aesop;
      obtain ⟨v', hv'⟩ := h_const';
      have h_hamming_dist : hamming_dist_on U B c = if v then count_zeros U c else count_ones U c := by
        convert hamming_dist_on_constant U c v using 1;
        exact Fintype.card_congr ( Equiv.subtypeEquivRight fun i => by aesop )
      have h_hamming_dist' : hamming_dist_on U B' c = if v' then count_zeros U c else count_ones U c := by
        convert hamming_dist_on_constant U c v' using 1;
        exact Fintype.card_congr ( Equiv.subtypeEquivRight fun i => by aesop )
      rw [h_hamming_dist, h_hamming_dist'];
      split_ifs <;> simp_all +decide [ is_majority_vote ];
      · contrapose! hB;
        exact fun _ => ⟨ c, hc, fun _ => ⟨ hB, by obtain ⟨ i, hi ⟩ := Set.nonempty_iff_ne_empty.2 ( show c ≠ ∅ from by rintro rfl; exact absurd hB ( by simp +decide [ count_zeros, count_ones ] ) ) ; exact ⟨ i, hi, by simp +decide [ hv i hi ] ⟩ ⟩ ⟩;
      · contrapose! hB;
        exact fun _ => ⟨ c, hc, fun h => absurd ( h hB ) ( by rintro H; obtain ⟨ i, hi ⟩ := Set.nonempty_iff_ne_empty.2 ( show c ≠ ∅ by rintro rfl; simp_all +decide [ count_ones, count_zeros ] ) ; specialize H i hi; aesop ) ⟩

/-
The minimum residual count is the sum of the minimum of zeros and ones in each orbit class.
-/
variable {I : Type*} [Fintype I] [DecidableEq I]

theorem minimum_residual_count (U : I → Bool) (S : Setoid I) (B : I → Bool)
    (hB : is_majority_vote U S B) :
    hamming_dist U B = ∑ c ∈ S.classes, min (count_zeros U c) (count_ones U c) := by
      -- By definition of majority vote, for each orbit class $c$, the Hamming distance on $c$ is $\min(\text{count\_zeros}(U, c), \text{count\_ones}(U, c))$.
      have h_hamming_dist_on : ∀ c ∈ S.classes, hamming_dist_on U B c = min (count_zeros U c) (count_ones U c) := by
        intro c hc
        have h_const : ∀ i ∈ c, B i = if count_ones U c > count_zeros U c then true else if count_zeros U c > count_ones U c then false else B i := by
          split_ifs <;> simp_all +decide [ is_constant_on ];
          · have := hB.2 c hc; aesop;
          · have := hB.2 c hc; aesop;
        by_cases h : count_ones U c > count_zeros U c <;> by_cases h' : count_zeros U c > count_ones U c <;> simp +decide [ h, h' ] at h_const ⊢;
        · grind;
        · rw [ min_eq_left h.le ];
          exact Fintype.card_congr ( Equiv.subtypeEquivRight fun i => by aesop );
        · rw [ min_eq_right_of_lt h' ];
          exact Fintype.card_congr ( Equiv.subtypeEquivRight fun i => by aesop );
        · have := hB.1 c hc;
          -- Since B is constant on c, let v be the constant value. Then, the Hamming distance is the number of positions where U and B differ.
          obtain ⟨v, hv⟩ : ∃ v, ∀ i ∈ c, B i = v := by
            obtain ⟨ i, hi ⟩ := Set.mem_setOf.mp hc;
            exact ⟨ B i, fun j hj => this _ _ hj ( hi.symm ▸ Set.mem_setOf.mpr ( Setoid.refl _ ) ) ⟩;
          convert hamming_dist_on_constant U c v using 1;
          · exact Fintype.card_congr ( Equiv.subtypeEquivRight fun i => by aesop );
          · grind +ring;
      rw [ ← Finset.sum_congr rfl fun c hc => h_hamming_dist_on c <| by simpa using hc, hamming_dist_decomposition ]

/-
Define is_minimizer and prove that the minimizer is unique if and only if no orbit class has equal counts of zeros and ones.
-/
variable {I : Type*} [Fintype I] [DecidableEq I]

/-- A field B is a minimizer if it is in the ModelClass and minimizes the Hamming distance. -/
def is_minimizer (U : I → Bool) (S : Setoid I) (B : I → Bool) : Prop :=
  B ∈ ModelClass S ∧ ∀ B' ∈ ModelClass S, hamming_dist U B ≤ hamming_dist U B'

theorem unique_minimizer_iff (U : I → Bool) (S : Setoid I) :
  (∃! B, is_minimizer U S B) ↔ ∀ c ∈ S.classes, count_zeros U c ≠ count_ones U c := by
    refine' ⟨ _, fun h => _ ⟩;
    · intro h c hc
      by_contra h_eq;
      -- If there exists a class $c$ with equal counts of zeros and ones, then we can construct two different minimizers by choosing different values for $B$ on $c$.
      obtain ⟨B₁, hB₁⟩ : ∃ B₁ : I → Bool, is_majority_vote U S B₁ ∧ ∀ i ∈ c, B₁ i = true := by
        -- Define B₁ such that it is constant on each orbit class and follows the majority rule on each class.
        obtain ⟨B₁, hB₁⟩ : ∃ B₁ : I → Bool, B₁ ∈ ModelClass S ∧ ∀ c' ∈ S.classes, (count_ones U c' > count_zeros U c' → ∀ i ∈ c', B₁ i = true) ∧ (count_zeros U c' > count_ones U c' → ∀ i ∈ c', B₁ i = false) ∧ (count_zeros U c' = count_ones U c' → ∀ i ∈ c', B₁ i = true) := by
          refine' ⟨ fun i => if ∃ c' ∈ S.classes, i ∈ c' ∧ count_zeros U c' < count_ones U c' then Bool.true else if ∃ c' ∈ S.classes, i ∈ c' ∧ count_zeros U c' = count_ones U c' then Bool.true else Bool.false, _, _ ⟩ <;> simp +decide [ ModelClass ];
          · intro c hc i j hi hj; simp_all +decide [ is_constant_on ] ;
            -- Since $c$ is an orbit class, for any $i, j \in c$, we have $i \sim j$.
            have h_orbit : ∀ i j : I, i ∈ c → j ∈ c → i ≈ j := by
              intro i j hi hj; exact (by
              obtain ⟨ k, hk ⟩ := hc;
              exact Setoid.trans ( hk.subset hi ) ( Setoid.symm ( hk.subset hj ) ));
            have h_orbit_eq : ∀ c' ∈ S.classes, i ∈ c' ↔ j ∈ c' := by
              rintro c' hc';
              obtain ⟨ k, hk ⟩ := hc';
              subst hk;
              simp only [Set.mem_setOf_eq];
              exact ⟨ fun h => Setoid.trans (Setoid.symm (h_orbit i j hi hj)) h,
                      fun h => Setoid.trans (h_orbit i j hi hj) h ⟩;
            grind;
          · intro c' hc';
            refine' ⟨ _, _, _ ⟩;
            · exact fun h i hi => Or.inl ⟨ c', hc', hi, h ⟩;
            · intro h_lt i hi
              have h_eq : ∀ x ∈ S.classes, i ∈ x → x = c' := by
                intro x hx hx'; rw [ Setoid.eq_of_mem_classes hx, Setoid.eq_of_mem_classes hc' ] ; aesop;
                exact x;
                exacts [ hx, hx', hx', hx, hx' ]
              simp [h_eq] at *;
              exact ⟨ fun x hx hx' => by rw [ h_eq x hx hx' ] ; exact le_of_lt h_lt, fun x hx hx' => by rw [ h_eq x hx hx' ] ; exact ne_of_gt h_lt ⟩;
            · exact fun h i hi => Or.inr ⟨ c', hc', hi, h ⟩;
        exact ⟨ B₁, ⟨ hB₁.1, fun c' hc' => ⟨ hB₁.2 c' hc' |>.1, hB₁.2 c' hc' |>.2.1 ⟩ ⟩, hB₁.2 c hc |>.2.2 h_eq ⟩
      obtain ⟨B₂, hB₂⟩ : ∃ B₂ : I → Bool, is_majority_vote U S B₂ ∧ ∀ i ∈ c, B₂ i = false := by
        refine' ⟨ fun i => if i ∈ c then Bool.false else B₁ i, _, _ ⟩ <;> simp_all +decide [ is_majority_vote ];
        refine' ⟨ _, _ ⟩;
        · intro d hd; intro i j hi hj; by_cases hi' : i ∈ c <;> by_cases hj' : j ∈ c <;> simp_all +decide ;
          · obtain ⟨ k, hk ⟩ := hc; obtain ⟨ l, hl ⟩ := hd; simp_all +decide [ Setoid.mem_classes ] ;
            exact False.elim ( hj' ( by exact Setoid.trans hj ( Setoid.symm hi ) |> Setoid.trans <| hi' ) );
          · -- Since $d$ and $c$ are both classes in $S.classes$, they must be equal because $S$ is an equivalence relation.
            have h_eq_classes : d = c := by
              exact Setoid.eq_of_mem_classes hd hj hc hj';
            aesop;
          · exact hB₁.1.1 d hd i j hi hj;
        · intro d hd;
          by_cases hcd : c = d;
          · aesop;
          · have h_disjoint : Disjoint c d := by
              rw [ Set.disjoint_left ];
              intro i hi hj;
              refine' hcd _;
              exact Setoid.eq_of_mem_classes hc hi hd hj;
            simp_all +decide [ Set.disjoint_left ];
            grind;
      have h_neq : B₁ ≠ B₂ := by
        rcases Set.eq_empty_or_nonempty c with ( rfl | ⟨ i, hi ⟩ ) <;> simp_all +decide;
        · obtain ⟨ x, hx ⟩ := Set.mem_setOf.mp hc;
          exact absurd hx.symm ( Set.Nonempty.ne_empty ⟨ x, Setoid.refl x ⟩ );
        · exact fun h => by have := congr_fun h i; simp +decide [ hB₁.2 i hi, hB₂.2 i hi ] at this;
      refine' h_neq ( h.unique _ _ ) <;> simp_all +decide [ is_minimizer ];
      · exact ⟨ hB₁.1.1, fun B' hB' => majority_vote_minimizes_hamming_dist U S B₁ hB₁.1 B' hB' ⟩;
      · exact ⟨ hB₂.1.1, fun B' hB' => majority_vote_minimizes_hamming_dist U S B₂ hB₂.1 B' hB' ⟩;
    · -- By definition of model class, there exists a unique majority vote B.
      obtain ⟨B, hB⟩ : ∃! B : I → Bool, is_majority_vote U S B := by
        -- Let's choose any majority vote $B$.
        obtain ⟨B, hB⟩ : ∃ B : I → Bool, is_majority_vote U S B := by
          refine' ⟨ fun i => if ∃ c ∈ S.classes, i ∈ c ∧ count_ones U c > count_zeros U c then Bool.true else Bool.false, _, _ ⟩ <;> simp_all +decide [ is_majority_vote ];
          · intro c hc i j hi hj; simp_all +decide [ Setoid.mem_classes ] ;
            -- Since $i$ and $j$ are in the same orbit class $c$, any orbit class containing $i$ must also contain $j$, and vice versa.
            have h_orbit : ∀ c' ∈ S.classes, i ∈ c' ↔ j ∈ c' := by
              intro c' hc';
              obtain ⟨ k, hk ⟩ := Set.mem_setOf.mp hc';
              obtain ⟨ l, hl ⟩ := Set.mem_setOf.mp hc; simp_all +decide [ Setoid.refl, Setoid.symm, Setoid.trans ] ;
              exact ⟨ fun h => by exact Setoid.trans hj ( Setoid.symm hi ) |> Setoid.trans <| h, fun h => by exact Setoid.trans hi ( Setoid.symm hj ) |> Setoid.trans <| h ⟩;
            exact ⟨ fun ⟨ c', hc', hi', hj' ⟩ => ⟨ c', hc', h_orbit c' hc' |>.1 hi', hj' ⟩, fun ⟨ c', hc', hj', hj'' ⟩ => ⟨ c', hc', h_orbit c' hc' |>.2 hj', hj'' ⟩ ⟩;
          · intro c hc
            constructor
            intro h_gt i hi
            use c, hc, hi, h_gt
            intro h_lt i hi x hx hx_i
            have h_eq : x = c := by
              exact Setoid.eq_of_mem_classes hx hx_i hc hi
            rw [h_eq]
            exact le_of_lt h_lt;
        refine' ⟨ B, hB, _ ⟩;
        intro B' hB'
        have h_eq : ∀ c ∈ S.classes, ∀ i ∈ c, B' i = B i := by
          intro c hc i hi
          have h_eq : (count_ones U c > count_zeros U c → B' i = true ∧ B i = true) ∧ (count_zeros U c > count_ones U c → B' i = false ∧ B i = false) := by
            exact ⟨ fun h => ⟨ hB'.2 c hc |>.1 h i hi, hB.2 c hc |>.1 h i hi ⟩, fun h => ⟨ hB'.2 c hc |>.2 h i hi, hB.2 c hc |>.2 h i hi ⟩ ⟩;
          cases lt_or_gt_of_ne ( h c hc ) <;> aesop;
        ext i;
        exact h_eq _ ( Set.mem_setOf.mpr ⟨ i, rfl ⟩ ) _ ( Setoid.refl _ );
      refine' ⟨ B, _, _ ⟩;
      · refine' ⟨ hB.1.1, fun B' hB' => _ ⟩;
        apply majority_vote_minimizes_hamming_dist U S B hB.1 B' hB';
      · intro y hy
        have hy_model : y ∈ ModelClass S := by
          exact hy.1
        have hy_majority : is_majority_vote U S y := by
          refine' ⟨ hy_model, fun c hc => _ ⟩;
          have hy_majority : hamming_dist U y = ∑ c ∈ S.classes, min (count_zeros U c) (count_ones U c) := by
            convert minimum_residual_count U S B hB.1 using 1;
            have := hy.2 B hB.1.1;
            exact le_antisymm this ( majority_vote_minimizes_hamming_dist U S B hB.1 y hy_model );
          have hy_majority : ∀ c ∈ S.classes, hamming_dist_on U y c = min (count_zeros U c) (count_ones U c) := by
            have hy_majority : ∑ c ∈ S.classes, hamming_dist_on U y c = ∑ c ∈ S.classes, min (count_zeros U c) (count_ones U c) := by
              rw [ ← hy_majority, hamming_dist_decomposition ];
            have hy_majority : ∀ c ∈ S.classes, hamming_dist_on U y c ≥ min (count_zeros U c) (count_ones U c) := by
              intro c hc
              have hy_majority : hamming_dist_on U y c ≥ min (count_zeros U c) (count_ones U c) := by
                have hy_const : ∃ v : Bool, ∀ i ∈ c, y i = v := by
                  have := hy_model c hc;
                  obtain ⟨i, hi⟩ : ∃ i, i ∈ c := by
                    obtain ⟨ i, hi ⟩ := Set.mem_setOf.mp hc;
                    exact ⟨ i, hi.symm ▸ Setoid.refl i ⟩;
                  exact ⟨ y i, fun j hj => this j i hj hi ⟩
                obtain ⟨ v, hv ⟩ := hy_const;
                have hy_majority : hamming_dist_on U y c = hamming_dist_on U (fun _ => v) c := by
                  exact Fintype.card_congr ( Equiv.subtypeEquivRight fun i => by aesop );
                exact hy_majority.symm ▸ min_hamming_dist_on_constant U c v;
              exact hy_majority;
            intro c hc
            by_contra h_contra;
            have hy_majority : ∑ c ∈ S.classes.toFinset, hamming_dist_on U y c > ∑ c ∈ S.classes.toFinset, min (count_zeros U c) (count_ones U c) := by
              exact Finset.sum_lt_sum ( fun x hx => by aesop ) ⟨ c, by aesop, lt_of_le_of_ne ( hy_majority c hc ) ( Ne.symm h_contra ) ⟩;
            grind;
          have hy_majority : ∀ c ∈ S.classes, ∀ i ∈ c, y i = if count_zeros U c < count_ones U c then true else false := by
            intro c hc i hi
            have hy_majority_i : hamming_dist_on U y c = if y i then count_zeros U c else count_ones U c := by
              have hy_majority_i : ∀ j ∈ c, y j = y i := by
                exact fun j hj => hy_model c hc j i hj hi;
              convert hamming_dist_on_constant U c ( y i ) using 1;
              exact Fintype.card_congr ( Equiv.subtypeEquivRight fun j => by aesop );
            grind +ring;
          grind +ring
        exact hB.right y hy_majority

