/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: bcd009bf-1603-43e6-acf8-ccf407b0a67b

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of Theorem 3 from the paper.
We define the candidate set, the NLL rate `lambda`, and the minimum rate `lambda_star`.
We formalize the assumptions (i) and properties of N(T) as definitions.
We prove parts (ii), (iii), and (iv) of the theorem:
(ii) If λ_{c₁} < λ_{c₂}, then NML(c₁, T) < NML(c₂, T) for sufficiently large T.
(iii) Every candidate c with λ_c > λ* is eventually excluded.
(iv) If λ* is achieved by a unique candidate c*, then NML selection stabilizes to c*.
We use a helper lemma `eventually_pos_of_isLittleO` to handle the asymptotic inequalities.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

variable {Candidate : Type} [Fintype Candidate] [Nonempty Candidate] [DecidableEq Candidate]

open Filter Asymptotics Topology

/-- The minimum NLL rate -/
noncomputable def lambda_star (lambda : Candidate → ℝ) : ℝ :=
  (Finset.image lambda Finset.univ).min' (Finset.image_nonempty.mpr Finset.univ_nonempty)

/-- Assumption (i): NML expansion -/
def assumption_i (NML : Candidate → ℕ → ℝ) (lambda : Candidate → ℝ) (k : Candidate → ℝ) (N : ℕ → ℝ) : Prop :=
  ∀ c, (fun T => NML c T - (lambda c * N T + (k c / 2) * Real.logb 2 T)) =o[atTop] N

/-- Assumption on N: N(T) goes to infinity -/
def assumption_N_tendsto (N : ℕ → ℝ) : Prop :=
  Tendsto N atTop atTop

/-- Assumption on N: N(T) is eventually positive -/
def assumption_N_pos (N : ℕ → ℝ) : Prop :=
  ∀ᶠ T in atTop, 0 < N T

/-- Definition of stabilization -/
def stabilizes_to (NML : Candidate → ℕ → ℝ) (c : Candidate) : Prop :=
  ∀ᶠ T in atTop, ∀ c' ≠ c, NML c T < NML c' T

/-
If f is o(g) and g is eventually positive, then c*g + f is eventually positive for c > 0.
-/
lemma eventually_pos_of_isLittleO
  {f g : ℕ → ℝ} (h_o : f =o[atTop] g) (c : ℝ) (hc : 0 < c) (hg_pos : ∀ᶠ T in atTop, 0 < g T) :
  ∀ᶠ T in atTop, 0 < c * g T + f T := by
    -- Since $f = o(g)$, eventually $|f(T)| < c \cdot g(T)$.
    have h_abs_lt : ∀ᶠ T in Filter.atTop, |f T| < c * g T := by
      have := h_o;
      rw [ Asymptotics.isLittleO_iff ] at this;
      filter_upwards [ this ( half_pos hc ), hg_pos ] with T hT₁ hT₂ using lt_of_le_of_lt hT₁ ( by rw [ Real.norm_of_nonneg hT₂.le ] ; nlinarith );
    filter_upwards [ h_abs_lt ] with T hT using by linarith [ abs_lt.mp hT ] ;

#check Real.logb
#check Real.log

/-
If λ_{c₁} < λ_{c₂}, then NML(c₁, T) < NML(c₂, T) for all sufficiently large T, assuming log T = o(N(T)).
-/
theorem part_ii
  (NML : Candidate → ℕ → ℝ) (lambda : Candidate → ℝ) (k : Candidate → ℝ) (N : ℕ → ℝ)
  (h_i : assumption_i NML lambda k N)
  (h_N_tendsto : assumption_N_tendsto N)
  (h_N_pos : assumption_N_pos N)
  (h_log_o_N : (fun (T : ℕ) => Real.logb 2 (T : ℝ)) =o[atTop] N)
  (c1 c2 : Candidate) (h_lambda : lambda c1 < lambda c2) :
  ∀ᶠ T in atTop, NML c1 T < NML c2 T := by
    -- Applying the definition of NML from assumption_i, we have NML c2 T - NML c1 T = (lambda c2 - lambda c1) * N T + ((k c2 / 2) - (k c1 / 2)) * log T + (o(N) - o(N)).
    have h_diff : (fun T => NML c2 T - NML c1 T - ((lambda c2 - lambda c1) * N T + (((k c2 / 2) - (k c1 / 2)) * Real.logb 2 T))) =o[atTop] N := by
      convert Asymptotics.IsLittleO.sub ( h_i c2 ) ( h_i c1 ) using 2 ; ring_nf;
    have h_diff_pos : (fun T => NML c2 T - NML c1 T - ((lambda c2 - lambda c1) * N T)) =o[atTop] N := by
      convert h_diff.add ( h_log_o_N.const_mul_left ( k c2 / 2 - k c1 / 2 ) ) using 1 ; ext ; ring;
    have := eventually_pos_of_isLittleO h_diff_pos ( lambda c2 -lambda c1 ) ( sub_pos.2 h_lambda ) h_N_pos; aesop;

/-
Every candidate c with λ_c > λ* is eventually excluded (specifically, beaten by an optimal candidate).
-/
theorem part_iii
  (NML : Candidate → ℕ → ℝ) (lambda : Candidate → ℝ) (k : Candidate → ℝ) (N : ℕ → ℝ)
  (h_i : assumption_i NML lambda k N)
  (h_N_tendsto : assumption_N_tendsto N)
  (h_N_pos : assumption_N_pos N)
  (h_log_o_N : (fun (T : ℕ) => Real.logb 2 (T : ℝ)) =o[atTop] N)
  (c : Candidate) (h_gt : lambda c > lambda_star lambda) :
  ∃ c', ∀ᶠ T in atTop, NML c' T < NML c T := by
    obtain ⟨c', hc'⟩ : ∃ c' : Candidate, lambda c' = lambda_star lambda ∧ lambda c' < lambda c := by
      have := Finset.min'_mem ( Finset.image lambda Finset.univ ) ; aesop;
    use c' ; have := part_ii NML lambda k N h_i h_N_tendsto h_N_pos h_log_o_N c' c ; aesop;

/-
If λ* is achieved by a unique candidate c*, then NML selection stabilizes to c* for all sufficiently large T.
-/
theorem part_iv
  (NML : Candidate → ℕ → ℝ) (lambda : Candidate → ℝ) (k : Candidate → ℝ) (N : ℕ → ℝ)
  (h_i : assumption_i NML lambda k N)
  (h_N_tendsto : assumption_N_tendsto N)
  (h_N_pos : assumption_N_pos N)
  (h_log_o_N : (fun (T : ℕ) => Real.logb 2 (T : ℝ)) =o[atTop] N)
  (c_star : Candidate)
  (h_unique : ∀ c, lambda c = lambda_star lambda ↔ c = c_star) :
  stabilizes_to NML c_star := by
    -- Apply (ii) to c_star and each candidate c ≠ c_star.
    have h_eventually : ∀ c ≠ c_star, ∀ᶠ T in Filter.atTop, NML c_star T < NML c T := by
      -- Apply part (ii) to c_star and each candidate c ≠ c_star.
      intro c hc_ne_c_star
      have h_lambda_c_gt_lambda_star : lambda c > lambda_star lambda := by
        -- Since $c \neq c_star$, by the uniqueness part of $h_unique$, we have $\lambda c \neq \lambda_star \lambda$.
        have h_lambda_c_ne_lambda_star : lambda c ≠ lambda_star lambda := by
          exact fun h => hc_ne_c_star <| h_unique c |>.1 h ▸ rfl;
        exact lt_of_le_of_ne ( Finset.min'_le _ _ <| Finset.mem_image_of_mem _ <| Finset.mem_univ c ) h_lambda_c_ne_lambda_star.symm;
      have := part_ii NML lambda k N h_i h_N_tendsto h_N_pos h_log_o_N c_star c
        (show lambda c_star < lambda c from by
          have h_star : lambda c_star = lambda_star lambda := (h_unique c_star).2 rfl
          linarith)
      aesop;
    exact Filter.eventually_all.mpr fun c => by by_cases hc : c = c_star <;> aesop;
