/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 0d6465fd-3f1c-4709-bc33-785f0e77b506

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized and proved Theorem 2 from the paper, establishing the six-way equivalence between conditions (i)-(vi) for universal refinement and monotonicity in binary spacetime on a torus.
Condition (i) is interpreted as modular equality of parameters (cond1_mod) to ensure equivalence with the translation action (cond2).
The implications proved are:
(i) ↔ (ii): cond1_mod_iff_cond2
(ii) → (iii): cond2_imp_cond3
(iii) → (ii): cond3_imp_cond2
(iii) → (iv): cond3_imp_cond4
(iv) → (v): cond4_imp_cond5
(v) → (iii): cond5_imp_cond3
(iii) → (vi): cond3_imp_cond6_success
(vi) → (iii): cond6_imp_cond3
These are combined in Theorem2_Final.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Check if ZMod is available and if Fintype instances work.
-/
#check ZMod
#synth Fintype (ZMod 5)
#synth Fintype ((i : Fin 3) → ZMod 5)

/-
Define SpacetimeGrid, Candidate, gridTranslate, gridOrbit, orbitPartition, BinaryField, and ModelClass.
-/
open BigOperators

section Definitions

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

/-- The spacetime grid on a torus. -/
abbrev SpacetimeGrid := ZMod T × ((i : Fin n) → ZMod (D i))

/-- A relative-periodic candidate c = (p, s). -/
structure Candidate where
  p : ℕ
  s : (i : Fin n) → ℤ

/-- The translation action induced by a candidate. -/
def gridTranslate (c : Candidate n) (pt : SpacetimeGrid n D T) : SpacetimeGrid n D T :=
  let (t, x) := pt
  (t + c.p, fun i => x i + c.s i)

/-- The orbit of a point under the translation action. -/
def gridOrbit (c : Candidate n) (pt : SpacetimeGrid n D T) : Set (SpacetimeGrid n D T) :=
  { pt' | ∃ k : ℕ, pt' = (gridTranslate n D T c)^[k] pt }

/-- The partition of the grid into orbits. -/
def orbitPartition (c : Candidate n) : Set (Set (SpacetimeGrid n D T)) :=
  { o | ∃ pt, o = gridOrbit n D T c pt }

/-- A binary field on the spacetime grid. -/
def BinaryField := SpacetimeGrid n D T → Bool

/-- The model class B(c) consists of all binary fields constant on orbit classes. -/
def ModelClass (c : Candidate n) : Set (BinaryField n D T) :=
  { U | ∀ o ∈ orbitPartition n D T c, ∀ x y, x ∈ o → y ∈ o → U x = U y }

end Definitions

/-
Define minHammingDist as the minimum Hamming distance from U to the model class.
-/
open BigOperators

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

/-- The minimum Hamming distance from U to any field in the model class of c. -/
noncomputable def minHammingDist (c : Candidate n) (U : BinaryField n D T) : ℕ :=
  sInf { d | ∃ V ∈ ModelClass n D T c, d = hammingDist U V }

/-
Check if Real.binEntropy is available.
-/
#check Real.binEntropy

/-
Define empiricalProb and NLL.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

/-- The empirical probability of 1 in an orbit class for a field U. -/
noncomputable def empiricalProb (U : BinaryField n D T) (o : Set (SpacetimeGrid n D T)) : ℝ :=
  ({x ∈ o | U x = true}).ncard / o.ncard

/-- The Bernoulli negative log-likelihood of a candidate c given a field U. -/
noncomputable def NLL (c : Candidate n) (U : BinaryField n D T) : ℝ :=
  ∑ o ∈ (orbitPartition n D T c).toFinset, (o.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o)

/-
Check signatures of defined functions.
-/
#check gridTranslate
#check orbitPartition
#check ModelClass
#check minHammingDist
#check NLL

/-
Define the six conditions for Theorem 2.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

/-- Condition (i): p₂ = m·p₁ and s₂ ≡ m·s₁ (mod D). -/
def cond1 (c₁ c₂ : Candidate n) : Prop :=
  ∃ m : ℕ, m ≥ 1 ∧ c₂.p = m * c₁.p ∧ ∀ i, (c₂.s i : ZMod (D i)) = m * (c₁.s i : ZMod (D i))

/-- Condition (ii): τ₂ = τ₁ᵐ. -/
def cond2 (c₁ c₂ : Candidate n) : Prop :=
  ∃ m : ℕ, m ≥ 1 ∧ gridTranslate n D T c₂ = (gridTranslate n D T c₁)^[m]

/-- Condition (iii): Π₂ refines Π₁. -/
def cond3 (c₁ c₂ : Candidate n) : Prop :=
  ∀ o₂ ∈ orbitPartition n D T c₂, ∃ o₁ ∈ orbitPartition n D T c₁, o₂ ⊆ o₁

/-- Condition (iv): B₁ ⊆ B₂. -/
def cond4 (c₁ c₂ : Candidate n) : Prop :=
  ModelClass n D T c₁ ⊆ ModelClass n D T c₂

/-- Condition (v): d*_U(c₂) ≤ d*_U(c₁) for all U. -/
def cond5 (c₁ c₂ : Candidate n) : Prop :=
  ∀ U, minHammingDist n D T c₂ U ≤ minHammingDist n D T c₁ U

/-- Condition (vi): NLL_U(c₂) ≤ NLL_U(c₁) for all U. -/
def cond6 (c₁ c₂ : Candidate n) : Prop :=
  ∀ U, NLL n D T c₂ U ≤ NLL n D T c₁ U

/-
Check signatures of the condition definitions.
-/
#check cond1
#check cond2
#check cond3
#check cond4
#check cond5
#check cond6

/-
Prove that condition (i) implies condition (ii).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond1_imp_cond2 (c₁ c₂ : Candidate n) : cond1 n D c₁ c₂ → cond2 n D T c₁ c₂ := by
  rintro ⟨ m, hm₁, hm₂, hm₃ ⟩;
  use m;
  refine' ⟨ hm₁, funext _ ⟩;
  intro x
  simp [gridTranslate, hm₂, hm₃];
  refine' Nat.recOn m _ _ <;> simp_all +decide [ Function.iterate_succ_apply', gridTranslate ];
  intro k hk; simp_all +decide [ add_mul, add_assoc, Function.iterate_succ_apply' ] ;
  exact ⟨ by rw [ ← hk ] ; ring, funext fun i => by rw [ ← hk ] ; ring ⟩

/-
Prove that condition (ii) implies condition (iii).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond2_imp_cond3 (c₁ c₂ : Candidate n) : cond2 n D T c₁ c₂ → cond3 n D T c₁ c₂ := by
  intro h₂ x hx
  obtain ⟨m, hm₁, hm₂⟩ := h₂;
  obtain ⟨ y, rfl ⟩ := hx;
  refine' ⟨ _, ⟨ y, rfl ⟩, _ ⟩;
  intro z hz
  obtain ⟨ k, rfl ⟩ := hz
  use k * m
  simp [hm₂];
  rw [ ← Function.iterate_mul, mul_comm ]

/-
Prove that condition (iii) implies condition (iv).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond4 (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond4 n D T c₁ c₂ := by
  intro h U hU o₂ ho₂ x y hx hy
  obtain ⟨o₁, ho₁, hsub⟩ := h o₂ ho₂
  exact hU o₁ ho₁ x y (hsub hx) (hsub hy)

/-
Prove that condition (iv) implies condition (v).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond4_imp_cond5 (c₁ c₂ : Candidate n) : cond4 n D T c₁ c₂ → cond5 n D T c₁ c₂ := by
  intro h4 U;
  refine' le_csInf _ _;
  · exact ⟨ _, ⟨ fun _ => Bool.true, fun o _ x y hx hy => rfl, rfl ⟩ ⟩;
  · rintro d ⟨ V, hV₁, rfl ⟩ ; exact Nat.sInf_le ⟨ V, h4 hV₁, rfl ⟩ ;

/-
Prove that the binary entropy function is concave on [0, 1].
-/
open BigOperators Classical

lemma concaveOn_binEntropy : ConcaveOn ℝ (Set.Icc 0 1) Real.binEntropy := by
  -- Since negMulLog is concave on [0, ∞), and [0, 1] is a subset of [0, ∞), the restriction of negMulLog to [0, 1] is also concave.
  have h_negMulLog_concave : ConcaveOn ℝ (Set.Icc 0 1) (fun x => -x * Real.log x) := by
    apply_rules [ concaveOn_of_deriv2_nonpos, neg_nonneg ] <;> norm_num;
    · exact convex_Icc _ _;
    · exact ContinuousOn.neg ( Real.continuous_mul_log.continuousOn );
    · exact DifferentiableOn.mul differentiableOn_id ( Real.differentiableOn_log.mono <| by norm_num );
    · exact DifferentiableOn.congr ( show DifferentiableOn ℝ ( fun x => Real.log x + 1 ) ( Set.Ioo 0 1 ) from DifferentiableOn.add ( DifferentiableOn.log differentiableOn_id fun x hx => ne_of_gt hx.1 ) ( differentiableOn_const _ ) ) fun x hx => by norm_num [ hx.1.ne' ] ;
    · intro x hx₁ hx₂; rw [ Filter.EventuallyEq.deriv_eq ( Filter.eventuallyEq_of_mem ( Ioo_mem_nhds hx₁ hx₂ ) fun y hy => by rw [ Real.deriv_mul_log hy.1.ne' ] ) ] ; norm_num [ hx₁.ne', hx₂.ne ] ; positivity;
  refine' ⟨ convex_Icc _ _, fun x hx y hy a b ha hb hab => _ ⟩;
  unfold Real.binEntropy;
  convert add_le_add ( h_negMulLog_concave.2 hx hy ha hb hab ) ( h_negMulLog_concave.2 ( show 1 - x ∈ Set.Icc 0 1 from ⟨ sub_nonneg.2 hx.2, sub_le_self _ hx.1 ⟩ ) ( show 1 - y ∈ Set.Icc 0 1 from ⟨ sub_nonneg.2 hy.2, sub_le_self _ hy.1 ⟩ ) ha hb hab ) using 1 ; norm_num ; ring;
  norm_num [ show a • x + b • y = a * x + b * y by rfl, show a * ( 1 - x ) + b * ( 1 - y ) = 1 - ( a * x + b * y ) by rw [ ← eq_sub_iff_add_eq' ] at hab; subst hab; ring ] ; ring

/-
Prove Jensen's inequality for the binary entropy on a partition.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

lemma entropy_inequality_for_partition
    (A : Set (SpacetimeGrid n D T))
    (S : Finset (Set (SpacetimeGrid n D T)))
    (U : BinaryField n D T)
    (h_disjoint : ∀ o₁ ∈ S, ∀ o₂ ∈ S, o₁ ≠ o₂ → Disjoint o₁ o₂)
    (h_union : ⋃ o ∈ S, o = A) :
    ∑ o ∈ S, (o.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o) ≤ (A.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U A) := by
  -- Since $H$ is concave, we apply Jensen's inequality to the partition $S$.
  have h_jensen : (∑ o ∈ S, (o.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o)) ≤ (∑ o ∈ S, o.ncard : ℝ) * Real.binEntropy ((∑ o ∈ S, (o.ncard : ℝ) * empiricalProb n D T U o) / (∑ o ∈ S, o.ncard : ℝ)) := by
    by_cases h : ∑ o ∈ S, ( o.ncard : ℝ ) = 0 <;> simp_all +decide [ Finset.sum_div _ _ _ ];
    · rw [ Finset.sum_eq_zero_iff_of_nonneg ] at h <;> aesop;
    · -- Applying Jensen's inequality to the concave function $H$ with the weights $w_o = \frac{|o|}{|A|}$.
      have h_jensen : (∑ o ∈ S, (o.ncard : ℝ) / (∑ o ∈ S, o.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o)) ≤ Real.binEntropy (∑ o ∈ S, (o.ncard : ℝ) / (∑ o ∈ S, o.ncard : ℝ) * empiricalProb n D T U o) := by
        apply_rules [ concaveOn_binEntropy |> ConcaveOn.le_map_sum ];
        · exact fun _ _ => div_nonneg ( Nat.cast_nonneg _ ) ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ );
        · rw [ ← Finset.sum_div, div_self h ];
        · intro o ho; exact ⟨ div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ), div_le_one_of_le₀ ( by exact_mod_cast Set.ncard_le_ncard ( show { x ∈ o | U x = true } ⊆ o from fun x hx => by aesop ) ) ( Nat.cast_nonneg _ ) ⟩ ;
      simp_all +decide [ div_mul_eq_mul_div, Finset.sum_div _ _ _ ];
      rwa [ ← Finset.sum_div _ _ _, div_le_iff₀' ( lt_of_le_of_ne ( Finset.sum_nonneg fun _ _ => Nat.cast_nonneg _ ) ( Ne.symm h ) ) ] at h_jensen;
  -- Since $\sum_{o \in S} o.ncard = A.ncard$, we can simplify the right-hand side of the inequality.
  have h_sum_card : (∑ o ∈ S, o.ncard : ℝ) = A.ncard := by
    rw_mod_cast [ ← h_union, Set.ncard_eq_toFinset_card' ];
    simp +decide [ Set.toFinset_card, Finset.sum_congr rfl fun x hx => Set.ncard_eq_toFinset_card' x ];
    rw [ ← Finset.card_biUnion ] ; congr ; ext ; aesop;
    exact fun x hx y hy hxy => Finset.disjoint_left.mpr fun z hz₁ hz₂ => Set.disjoint_left.mp ( h_disjoint x hx y hy hxy ) ( Finset.mem_filter.mp hz₁ |>.2 ) ( Finset.mem_filter.mp hz₂ |>.2 );
  -- Since $\sum_{o \in S} o.ncard \cdot p_o = \sum_{x \in A} U(x)$, we can simplify the right-hand side of the inequality.
  have h_sum_prob : (∑ o ∈ S, (o.ncard : ℝ) * empiricalProb n D T U o) = ({x ∈ A | U x = true}).ncard := by
    have h_sum_prob : (∑ o ∈ S, (o.ncard : ℝ) * empiricalProb n D T U o) = (∑ o ∈ S, ({x ∈ o | U x = true}).ncard : ℝ) := by
      refine' Finset.sum_congr rfl fun o ho => _;
      unfold empiricalProb; by_cases h : Set.ncard o = 0 <;> simp +decide [ h, mul_div_cancel₀ ] ;
      rw [ Set.ncard_eq_zero ] at h ; aesop;
    rw [ h_sum_prob, ← h_union ];
    simp +decide [ Set.setOf_and, Set.ncard_eq_toFinset_card' ];
    rw_mod_cast [ ← Finset.card_biUnion ];
    · congr with x ; aesop;
    · exact fun x hx y hy hxy => Finset.disjoint_left.mpr fun z hz₁ hz₂ => Set.disjoint_left.mp ( h_disjoint x hx y hy hxy ) ( Set.mem_toFinset.mp ( Finset.mem_inter.mp hz₁ |>.1 ) ) ( Set.mem_toFinset.mp ( Finset.mem_inter.mp hz₂ |>.1 ) );
  by_cases h : A.ncard = 0 <;> simp_all +decide [ empiricalProb ]

/-
Prove that a sum over a refined partition can be grouped by the coarser partition.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

lemma sum_partition_refinement
    (s₁ s₂ : Finset (Set (SpacetimeGrid n D T)))
    (f : Set (SpacetimeGrid n D T) → ℝ)
    (h_partition₁ : Setoid.IsPartition (s₁ : Set (Set (SpacetimeGrid n D T))))
    (h_partition₂ : Setoid.IsPartition (s₂ : Set (Set (SpacetimeGrid n D T))))
    (h_refine : ∀ o₂ ∈ s₂, ∃ o₁ ∈ s₁, o₂ ⊆ o₁) :
    ∑ o₂ ∈ s₂, f o₂ = ∑ o₁ ∈ s₁, ∑ o₂ ∈ s₂.filter (fun o => o ⊆ o₁), f o₂ := by
  rw [ ← Finset.sum_biUnion ];
  · rcongr o₂ ; aesop;
  · intro o₁ ho₁ o₂ ho₂ hne; simp_all +decide [ Finset.disjoint_left, Setoid.IsPartition ] ;
    intro a ha ha₁ ha₂; obtain ⟨ x, hx ⟩ := Set.nonempty_iff_ne_empty.mpr ( show a ≠ ∅ from by aesop ) ; simp_all +decide [ Set.subset_def ] ;
    exact hne <| ExistsUnique.unique ( h_partition₁.2 _ _ ) ⟨ ho₁, ha₁ _ _ hx ⟩ ⟨ ho₂, ha₂ _ _ hx ⟩

/-
Prove that the orbit partition is indeed a partition of the grid.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

lemma orbitPartition_isPartition (c : Candidate n) :
  Setoid.IsPartition (orbitPartition n D T c) := by
  -- The orbit partition is an equivalence relation, so it is a partition.
  have h_partition : ∀ x y : SpacetimeGrid n D T, (y ∈ gridOrbit n D T c x) ↔ (x ∈ gridOrbit n D T c y) := by
    intro x y; constructor <;> intro h <;> obtain ⟨ k, rfl ⟩ := h;
    · -- Since the grid is finite, the sequence of translations must eventually repeat. Therefore, there exists some $m$ such that applying the translation $m$ times brings $x$ back to itself.
      obtain ⟨m, hm⟩ : ∃ m : ℕ, m > 0 ∧ (gridTranslate n D T c)^[m] x = x := by
        have h_finite : Set.Finite (Set.range (fun k : ℕ => (gridTranslate n D T c)^[k] x)) := by
          exact Set.toFinite _;
        -- Since the range is finite, there must exist distinct natural numbers $i$ and $j$ such that $(gridTranslate n D T c)^[i] x = (gridTranslate n D T c)^[j] x$.
        obtain ⟨i, j, hij, h_eq⟩ : ∃ i j : ℕ, i < j ∧ (gridTranslate n D T c)^[i] x = (gridTranslate n D T c)^[j] x := by
          contrapose! h_finite;
          exact Set.infinite_range_of_injective fun i j hij => le_antisymm ( le_of_not_gt fun hi => h_finite _ _ hi hij.symm ) ( le_of_not_gt fun hj => h_finite _ _ hj hij );
        refine' ⟨ j - i, tsub_pos_of_lt hij, _ ⟩;
        rw [ ← Nat.add_sub_of_le hij.le, Function.iterate_add_apply ] at h_eq;
        exact Function.Injective.iterate ( show Function.Injective ( gridTranslate n D T c ) from by
                                            intro x y hxy; simp_all +decide [ Function.Injective, gridTranslate ] ;
                                            exact Prod.ext hxy.1 ( funext fun i => by simpa using congr_fun hxy.2 i ) ) i h_eq.symm;
      use m * (k + 1) - k;
      rw [ ← Function.iterate_add_apply, Nat.sub_add_cancel ( by nlinarith ) ];
      rw [ Function.iterate_mul, Function.iterate_fixed hm.2 ];
    · -- Since the grid is finite, the translation map τ is a permutation, so applying it multiple times will eventually return to the original point. Therefore, there exists some m such that τ^m(y) = y.
      have h_perm : ∃ m : ℕ, m > 0 ∧ (gridTranslate n D T c)^[m] y = y := by
        -- Since the grid is finite, the translation map τ is a permutation, so applying it multiple times will eventually return to the original point. Therefore, there exists some m such that τ^m(y) = y. Use this fact.
        have h_perm : Function.Bijective (gridTranslate n D T c) := by
          have h_perm : Function.Injective (gridTranslate n D T c) := by
            intro x y hxy; simp_all +decide [ Function.Injective, gridTranslate ] ;
            exact Prod.ext hxy.1 ( funext fun i => by simpa using congr_fun hxy.2 i );
          exact ⟨ h_perm, Finite.injective_iff_surjective.mp h_perm ⟩;
        have h_perm : ∃ m : ℕ, m > 0 ∧ (gridTranslate n D T c)^[m] = id := by
          refine ⟨orderOf (Equiv.ofBijective (gridTranslate n D T c) h_perm), orderOf_pos _, ?_⟩
          show (⇑(Equiv.ofBijective (gridTranslate n D T c) h_perm))^[orderOf
            (Equiv.ofBijective (gridTranslate n D T c) h_perm)] = id
          rw [← Equiv.Perm.coe_pow, pow_orderOf_eq_one, Equiv.Perm.coe_one]
        exact ⟨ h_perm.choose, h_perm.choose_spec.1, congr_fun h_perm.choose_spec.2 y ⟩;
      obtain ⟨ m, hm₁, hm₂ ⟩ := h_perm; use m * ( k + 1 ) - k; simp_all +decide [ ← Function.iterate_add_apply, Nat.sub_add_cancel ( show k ≤ m * ( k + 1 ) from by nlinarith ) ] ;
      rw [ Function.iterate_mul, Function.iterate_fixed hm₂ ];
  have h_partition : ∀ x y z : SpacetimeGrid n D T, x ∈ gridOrbit n D T c y → y ∈ gridOrbit n D T c z → x ∈ gridOrbit n D T c z := by
    intros x y z hxy hyz
    obtain ⟨k, hk⟩ := hxy
    obtain ⟨m, hm⟩ := hyz
    use k + m
    simp [hk, hm, gridTranslate];
    rw [ Function.iterate_add_apply ];
  constructor;
  · rintro ⟨ x, hx ⟩ ; simp_all +decide [ Set.ext_iff ] ;
    exact hx _ _ ⟨ 0, rfl ⟩;
  · intro x;
    use gridOrbit n D T c x;
    simp +zetaDelta at *;
    refine' ⟨ ⟨ ⟨ x, rfl ⟩, _ ⟩, _ ⟩;
    · exact ⟨ 0, rfl ⟩;
    · rintro y ⟨ z, rfl ⟩ hxz;
      grind

/-
Prove that if a partition refines another, each element of the coarse partition is the union of the fine elements contained in it.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

lemma partition_refinement_union
    (s₁ s₂ : Finset (Set (SpacetimeGrid n D T)))
    (h_partition₁ : Setoid.IsPartition (s₁ : Set (Set (SpacetimeGrid n D T))))
    (h_partition₂ : Setoid.IsPartition (s₂ : Set (Set (SpacetimeGrid n D T))))
    (h_refine : ∀ o₂ ∈ s₂, ∃ o₁ ∈ s₁, o₂ ⊆ o₁)
    (o₁ : Set (SpacetimeGrid n D T))
    (ho₁ : o₁ ∈ s₁) :
    ⋃ o ∈ s₂.filter (fun o => o ⊆ o₁), o = o₁ := by
  ext x; exact ⟨by
  aesop, by
    intro hx
    obtain ⟨o₂, ho₂⟩ : ∃ o₂ ∈ s₂, x ∈ o₂ := by
      obtain ⟨ o₂, ho₂ ⟩ := h_partition₂.2 x; aesop;
    obtain ⟨o₃, ho₃⟩ : ∃ o₃ ∈ s₁, o₂ ⊆ o₃ := h_refine o₂ ho₂.left
    have h_eq : o₃ = o₁ := by
      have := h_partition₁.2;
      exact ExistsUnique.unique ( this x ) ⟨ ho₃.1, ho₃.2 ho₂.2 ⟩ ⟨ ho₁, hx ⟩
    aesop⟩;

/-
Prove that condition (iii) implies condition (vi) using the helper lemmas.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6 (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  intro h;
  intro U;
  -- Group the sum in NLL(c₂) by the orbits in Π₁.
  have h_group : ∑ o₂ ∈ (orbitPartition n D T c₂).toFinset, (o₂.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o₂) = ∑ o₁ ∈ (orbitPartition n D T c₁).toFinset, ∑ o₂ ∈ (orbitPartition n D T c₂).toFinset.filter (fun o => o ⊆ o₁), (o₂.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o₂) := by
    convert sum_partition_refinement n D T ( orbitPartition n D T c₁ |> Set.toFinset ) ( orbitPartition n D T c₂ |> Set.toFinset ) _ _ _ _ using 1;
    · have := orbitPartition_isPartition n D T c₁; aesop;
    · convert orbitPartition_isPartition n D T c₂ using 1;
      simp +zetaDelta at *;
    · aesop;
  -- For each o₁, the inner sum is bounded by |o₁| * H(p(o₁)) using Jensen's inequality (entropy_inequality_for_partition).
  have h_jensen : ∀ o₁ ∈ (orbitPartition n D T c₁).toFinset, ∑ o₂ ∈ (orbitPartition n D T c₂).toFinset.filter (fun o => o ⊆ o₁), (o₂.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o₂) ≤ (o₁.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o₁) := by
    intros o₁ ho₁
    have h_union : ⋃ o₂ ∈ (orbitPartition n D T c₂).toFinset.filter (fun o => o ⊆ o₁), o₂ = o₁ := by
      apply partition_refinement_union;
      any_goals exact ( orbitPartition n D T c₁ ).toFinset;
      · convert orbitPartition_isPartition n D T c₁ using 1;
        ext; simp [orbitPartition];
      · convert orbitPartition_isPartition n D T c₂ using 1;
        ext; simp [orbitPartition];
      · aesop;
      · exact ho₁;
    convert entropy_inequality_for_partition n D T o₁ _ U _ _ using 1;
    · intros o₁_1 ho₁_1 o₂ ho₂ hne; exact (by
      have h_partition : Setoid.IsPartition (orbitPartition n D T c₂) := by
        exact orbitPartition_isPartition n D T c₂;
      have := h_partition.2;
      exact Set.disjoint_left.mpr fun x hx₁ hx₂ => hne <| ExistsUnique.unique ( this x ) ⟨ by aesop, hx₁ ⟩ ⟨ by aesop, hx₂ ⟩);
    · exact h_union;
  exact h_group.le.trans ( Finset.sum_le_sum h_jensen )

/-
Prove that condition (iii) implies condition (vi) using the helper lemmas.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_proof (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  exact cond3_imp_cond6 n D T c₁ c₂

/-
Prove that condition (iii) implies condition (vi) using the helper lemmas.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_thm (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  exact cond3_imp_cond6 n D T c₁ c₂

/-
Prove that condition (iii) implies condition (vi) using the helper lemmas (v2).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_v2 (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  exact cond3_imp_cond6 n D T c₁ c₂

/-
Prove that condition (iii) implies condition (vi) using the helper lemmas (final attempt).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_final (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  exact cond3_imp_cond6 n D T c₁ c₂

/-
Check if cond3_imp_cond6 is already declared.
-/
#check cond3_imp_cond6

/-
Prove that condition (v) implies condition (iii).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond5_imp_cond3 (c₁ c₂ : Candidate n) : cond5 n D T c₁ c₂ → cond3 n D T c₁ c₂ := by
  intro h
  by_contra h_not_refine
  obtain ⟨o₂, ho₂⟩ : ∃ o₂ ∈ orbitPartition n D T c₂, ∃ o₁₁ o₁₂, o₁₁ ∈ orbitPartition n D T c₁ ∧ o₁₂ ∈ orbitPartition n D T c₁ ∧ o₁₁ ≠ o₁₂ ∧ ∃ x₁ ∈ o₂, x₁ ∈ o₁₁ ∧ ∃ x₂ ∈ o₂, x₂ ∈ o₁₂ := by
    simp_all +decide [ cond3 ];
    obtain ⟨ o₂, ho₂₁, ho₂₂ ⟩ := h_not_refine;
    obtain ⟨x₁, hx₁⟩ : ∃ x₁ ∈ o₂, ∃ o₁₁ ∈ orbitPartition n D T c₁, x₁ ∈ o₁₁ := by
      obtain ⟨ x₁, hx₁ ⟩ := ho₂₁;
      exact ⟨ x₁, hx₁.symm ▸ Set.mem_setOf.mpr ⟨ 0, rfl ⟩, _, ⟨ x₁, rfl ⟩, Set.mem_setOf.mpr ⟨ 0, rfl ⟩ ⟩;
    obtain ⟨o₁₁, ho₁₁₁, ho₁₁₂⟩ := hx₁.right
    obtain ⟨x₂, hx₂⟩ : ∃ x₂ ∈ o₂, x₂ ∉ o₁₁ := by
      exact Set.not_subset.mp ( ho₂₂ o₁₁ ho₁₁₁ );
    obtain ⟨o₁₂, ho₁₂₁, ho₁₂₂⟩ : ∃ o₁₂ ∈ orbitPartition n D T c₁, x₂ ∈ o₁₂ := by
      exact ⟨ _, ⟨ x₂, rfl ⟩, by tauto ⟩;
    exact ⟨ o₂, ho₂₁, o₁₁, ho₁₁₁, o₁₂, ho₁₂₁, by aesop, x₁.1, x₁.2, hx₁.1, ho₁₁₂, x₂.1, x₂.2, hx₂.1, ho₁₂₂ ⟩;
  obtain ⟨ o₁₁, o₁₂, ho₁₁, ho₁₂, ho₁₁₂, x₁, hx₁₁, hx₁₂, x₂, hx₂₁, hx₂₂ ⟩ := ho₂.2
  obtain ⟨U, hU⟩ : ∃ U : BinaryField n D T, (∀ x ∈ o₁₁, U x = true) ∧ (∀ x ∈ o₁₂, U x = false) ∧ (∀ o ∈ orbitPartition n D T c₁, ∀ x y, x ∈ o → y ∈ o → U x = U y) := by
    use fun x => if ∃ o ∈ orbitPartition n D T c₁, x ∈ o ∧ o = o₁₁ then true else false;
    refine' ⟨ _, _, _ ⟩ <;> simp_all +decide [ Setoid.IsPartition ];
    · intro a b hab hba; have := orbitPartition_isPartition n D T c₁; have := this.2; simp_all +decide [ Setoid.IsPartition ] ;
      exact ho₁₁₂ <| ExistsUnique.unique ( this a b ) ⟨ ho₁₁, hba ⟩ ⟨ ho₁₂, hab ⟩;
    · intro o ho a b a' b' ha hb; have := orbitPartition_isPartition n D T c₁; simp_all +decide [ Setoid.IsPartition ] ;
      cases this.2 a b ; cases this.2 a' b' ; aesop;
  -- Then d*_U(c₁) = 0 (since U ∈ B₁).
  have h_d1 : minHammingDist n D T c₁ U = 0 := by
    exact le_antisymm ( csInf_le ⟨ 0, fun d hd => Nat.zero_le _ ⟩ ⟨ U, ⟨ fun o ho x y hx hy => hU.2.2 o ho x y hx hy, by aesop ⟩ ⟩ ) ( Nat.zero_le _ );
  -- However, o₂ contains x (where U=1) and some y (where U=0, since y∉o₁_x).
  have h_d2 : ∀ V ∈ ModelClass n D T c₂, hammingDist U V ≥ 1 := by
    intro V hV
    have h_const : ∀ x y, x ∈ o₂ → y ∈ o₂ → V x = V y := by
      exact fun x y hx hy => hV o₂ ho₂.1 x y hx hy;
    by_cases h : V x₁ = Bool.true <;> simp_all +decide [ hammingDist ];
    · exact ⟨ x₂, by specialize h_const _ _ _ _ hx₁₁ hx₂₁; aesop ⟩;
    · exact ⟨ x₁, by aesop ⟩;
  -- Thus d*_U(c₂) > 0.
  have h_d2_pos : minHammingDist n D T c₂ U > 0 := by
    exact lt_of_lt_of_le zero_lt_one <| le_csInf ⟨ _, ⟨ fun _ => Bool.true, by
      exact fun o ho x y hx hy => rfl, rfl ⟩ ⟩ fun d hd => hd.choose_spec.2.symm ▸ h_d2 _ hd.choose_spec.1;
  linarith [ h U ]

/-
Prove that condition (iii) implies condition (vi) (renamed to avoid conflicts).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem theorem_iii_implies_vi (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  exact cond3_imp_cond6 n D T c₁ c₂

/-
Prove that condition (iii) implies condition (vi) (proven version).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_proven (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  exact cond3_imp_cond6 n D T c₁ c₂

/-
Prove that condition (iii) implies condition (vi) (final v2).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_final_v2 (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  exact cond3_imp_cond6 n D T c₁ c₂

/-
Prove that condition (iii) implies condition (vi) (correct version).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_correct (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  -- By definition of cond3, there exists m such that the orbits of c₂ are contained in the orbits of c₁.
  apply cond3_imp_cond6_v2 n D T c₁ c₂

/-
Check if cond3_imp_cond6 is defined.
-/
#check cond3_imp_cond6

/-
Prove that condition (vi) implies condition (iii).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond6_imp_cond3 (c₁ c₂ : Candidate n) : cond6 n D T c₁ c₂ → cond3 n D T c₁ c₂ := by
  intro h
  by_contra h_not_r
  obtain ⟨o₂, ho₂⟩ : ∃ o₂ ∈ orbitPartition n D T c₂, ¬∃ o₁ ∈ orbitPartition n D T c₁, o₂ ⊆ o₁ := by
    contrapose! h_not_r; aesop;
  obtain ⟨x, hx_o₂, y, hy_o₂, hxy⟩ : ∃ x ∈ o₂, ∃ y ∈ o₂, ∃ o₁_x ∈ orbitPartition n D T c₁, x ∈ o₁_x ∧ y∉ o₁_x := by
    obtain ⟨x, hx_o₂⟩ : ∃ x ∈ o₂, ∃ o₁_x ∈ orbitPartition n D T c₁, x ∈ o₁_x := by
      obtain ⟨ x, hx ⟩ := ho₂.1;
      exact ⟨ x, hx.symm ▸ Set.mem_setOf.mpr ⟨ 0, rfl ⟩, _, ⟨ x, rfl ⟩, Set.mem_setOf.mpr ⟨ 0, rfl ⟩ ⟩;
    grind
  set U : BinaryField n D T := fun z => if ∃ o₁ ∈ orbitPartition n D T c₁, z ∈ o₁ ∧ o₁ = {z' | ∃ k : ℕ, z' = (gridTranslate n D T c₁)^[k] x} then true else false with hU_def
  have hNLL_c1 : NLL n D T c₁ U = 0 := by
    refine' Finset.sum_eq_zero fun o ho => _;
    -- Since $U$ is constant on each orbit of $c₁$, the empirical probability on $o$ is either 0 or 1.
    have h_empirical_prob : empiricalProb n D T U o = 0 ∨ empiricalProb n D T U o = 1 := by
      by_cases h : ∃ o₁ ∈ orbitPartition n D T c₁, o = o₁ ∧ o₁ = {z' | ∃ k : ℕ, z' = (gridTranslate n D T c₁)^[k] x} <;> simp_all +decide [ empiricalProb ];
      · by_cases h : Set.ncard { z' | ∃ k : ℕ, z' = ( gridTranslate n D T c₁ )^[k] x } = 0 <;> aesop;
      · by_cases h' : { z' | ∃ k : ℕ, z' = ( gridTranslate n D T c₁ ) ^[ k ] x } ∈ orbitPartition n D T c₁ <;> simp_all +decide [ Set.ncard_eq_toFinset_card' ];
        -- Since $o$ is in the orbit partition of $c₁$, and the set $\{z' | \exists k, z' = (gridTranslate n D T c₁)^[k] x\}$ is also in the orbit partition of $c₁$, they must be either the same or disjoint.
        have h_disjoint : o = {z' | ∃ k : ℕ, z' = (gridTranslate n D T c₁)^[k] x} ∨ Disjoint o {z' | ∃ k : ℕ, z' = (gridTranslate n D T c₁)^[k] x} := by
          have h_disjoint : ∀ o₁ o₂ : Set (SpacetimeGrid n D T), o₁ ∈ orbitPartition n D T c₁ → o₂ ∈ orbitPartition n D T c₁ → o₁ ≠ o₂ → Disjoint o₁ o₂ := by
            intros o₁ o₂ ho₁ ho₂ hne; exact (by
            have := orbitPartition_isPartition n D T c₁; simp_all +decide [ Setoid.IsPartition ] ;
            exact Set.disjoint_left.mpr fun x hx₁ hx₂ => hne <| ExistsUnique.unique ( this.2 _ _ ) ⟨ ho₁, hx₁ ⟩ ⟨ ho₂, hx₂ ⟩);
          exact Or.inr <| h_disjoint _ _ ho h' h;
        simp_all +decide [ Finset.ext_iff, Set.disjoint_left ];
    aesop
  have hNLL_c2 : NLL n D T c₂ U > 0 := by
    have hNLL_c2_pos : Real.binEntropy (empiricalProb n D T U o₂) > 0 := by
      have hNLL_c2_pos : 0 < empiricalProb n D T U o₂ ∧ empiricalProb n D T U o₂ < 1 := by
        constructor <;> norm_num [ empiricalProb ] at *;
        · refine' div_pos ( Nat.cast_pos.mpr _ ) ( Nat.cast_pos.mpr _ ) <;> norm_num [ Set.ncard_eq_toFinset_card' ] at *;
          · use x; simp [hx_o₂, hU_def];
            exact ⟨ ⟨ x, rfl ⟩, 0, rfl ⟩;
          · exact ⟨ x, Finset.mem_filter.mpr ⟨ Finset.mem_univ _, hx_o₂ ⟩ ⟩;
        · rw [ div_lt_one ] <;> norm_cast <;> norm_num [ Set.ncard_eq_toFinset_card' ] at *;
          · refine' Finset.card_lt_card _ ; simp_all +decide [ Finset.subset_iff ] ; (
            simp_all +decide [ Finset.ssubset_def, Finset.subset_iff ];
            grind);
          · exact ⟨ x, Finset.mem_filter.mpr ⟨ Finset.mem_univ _, hx_o₂ ⟩ ⟩;
      norm_num [ Real.binEntropy ] at *;
      nlinarith [ Real.log_le_sub_one_of_pos ( by linarith : 0 < 1 - empiricalProb n D T U o₂ ), Real.log_le_sub_one_of_pos ( by linarith : 0 < empiricalProb n D T U o₂ ) ];
    refine' lt_of_lt_of_le _ ( Finset.single_le_sum ( fun o _ => _ ) ( show o₂ ∈ ( orbitPartition n D T c₂ ).toFinset from _ ) ) <;> norm_num [ hNLL_c2_pos ];
    · exact Nat.pos_of_ne_zero ( by intro h; simp_all +decide [ Set.ncard_eq_toFinset_card' ] );
    · refine' mul_nonneg ( Nat.cast_nonneg _ ) _;
      apply_rules [ Real.binEntropy_nonneg ];
      · exact div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ );
      · refine' div_le_one_of_le₀ _ _ <;> norm_num [ Set.ncard_eq_toFinset_card' ];
        exact Finset.card_le_card fun x hx => by aesop;
    · exact ho₂.1
  have h_contra : NLL n D T c₂ U ≤ NLL n D T c₁ U := by
    exact h U
  linarith

/-
Prove that condition (iii) implies condition (vi) (real version).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_real (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  -- Apply the hypothesis `h_refinement` to conclude the proof.
  apply cond3_imp_cond6_final_v2 n D T c₁ c₂

/-
Prove that condition (iii) implies condition (vi) (successful version).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond6_success (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := by
  intro h3 U
  let s₁ := (orbitPartition n D T c₁).toFinset
  let s₂ := (orbitPartition n D T c₂).toFinset
  
  have h_part₁ : Setoid.IsPartition (s₁ : Set (Set (SpacetimeGrid n D T))) := by
    rw [Set.coe_toFinset]
    exact orbitPartition_isPartition n D T c₁
    
  have h_part₂ : Setoid.IsPartition (s₂ : Set (Set (SpacetimeGrid n D T))) := by
    rw [Set.coe_toFinset]
    exact orbitPartition_isPartition n D T c₂

  have h_refine : ∀ o₂ ∈ s₂, ∃ o₁ ∈ s₁, o₂ ⊆ o₁ := by
    intro o₂ ho₂
    rw [Set.mem_toFinset] at ho₂
    obtain ⟨o₁, ho₁, hsub⟩ := h3 o₂ ho₂
    use o₁
    rw [Set.mem_toFinset]
    exact ⟨ho₁, hsub⟩

  unfold NLL
  let f := fun o => (o.ncard : ℝ) * Real.binEntropy (empiricalProb n D T U o)
  change ∑ o₂ ∈ s₂, f o₂ ≤ ∑ o₁ ∈ s₁, f o₁
  
  calc ∑ o₂ ∈ s₂, f o₂
    _ = ∑ o₁ ∈ s₁, ∑ o₂ ∈ s₂.filter (fun o => o ⊆ o₁), f o₂ := by
      exact sum_partition_refinement n D T s₁ s₂ f h_part₁ h_part₂ h_refine
    _ ≤ ∑ o₁ ∈ s₁, f o₁ := by
      apply Finset.sum_le_sum
      intro o₁ ho₁
      let S := s₂.filter (fun o => o ⊆ o₁)
      have h_disjoint : ∀ a ∈ S, ∀ b ∈ S, a ≠ b → Disjoint a b := by
        intros a ha b hb hab
        rw [Finset.mem_filter] at ha hb
        apply Setoid.IsPartition.pairwiseDisjoint h_part₂ ha.1 hb.1 hab
      have h_union : ⋃ o ∈ S, o = o₁ := by
        apply partition_refinement_union n D T s₁ s₂ h_part₁ h_part₂ h_refine o₁ ho₁
      convert entropy_inequality_for_partition n D T o₁ S U h_disjoint h_union

/-
Define cond1_mod and prove gridTranslate_iterate.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

/-- Condition (i) interpreted with modular arithmetic for time. -/
def cond1_mod (c₁ c₂ : Candidate n) : Prop :=
  ∃ m : ℕ, m ≥ 1 ∧ (c₂.p : ZMod T) = m * (c₁.p : ZMod T) ∧ ∀ i, (c₂.s i : ZMod (D i)) = m * (c₁.s i : ZMod (D i))

lemma gridTranslate_iterate (c : Candidate n) (m : ℕ) (pt : SpacetimeGrid n D T) :
    (gridTranslate n D T c)^[m] pt = (pt.1 + m * (c.p : ZMod T), fun i => pt.2 i + m * (c.s i : ZMod (D i))) := by
      induction m <;> simp_all +decide [ Function.iterate_succ_apply', add_mul ];
      unfold gridTranslate; simp +decide [ add_assoc ] ;

/-
Check if cond1_mod is defined.
-/
#check cond1_mod

/-
Prove that condition (i) (modular version) is equivalent to condition (ii).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond1_mod_iff_cond2 (c₁ c₂ : Candidate n) : cond1_mod n D T c₁ c₂ ↔ cond2 n D T c₁ c₂ := by
  constructor <;> intro h
  · obtain ⟨m, hm₁, hm₂, hm₃⟩ := h
    refine ⟨m, hm₁, ?_⟩
    funext pt
    obtain ⟨t, x⟩ := pt
    rw [gridTranslate_iterate]
    simp [gridTranslate, hm₂, hm₃]
  · obtain ⟨m, hm₁, hm₂⟩ := h
    have h0 := congr_fun hm₂ ((0, fun _ => 0) : SpacetimeGrid n D T)
    rw [gridTranslate_iterate] at h0
    refine ⟨m, hm₁, ?_, fun i => ?_⟩
    · simpa [gridTranslate] using congr_arg Prod.fst h0
    · simpa [gridTranslate] using congr_fun (congr_arg Prod.snd h0) i

/-
Check if gridTranslate_iterate is defined.
-/
#check gridTranslate_iterate

/-
Prove that condition (iii) implies condition (ii).
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

theorem cond3_imp_cond2 (c₁ c₂ : Candidate n) : cond3 n D T c₁ c₂ → cond2 n D T c₁ c₂ := by
  intro h3
  obtain ⟨m, hm⟩ : ∃ m : ℕ, m ≥ 1 ∧ (gridTranslate n D T c₂) (0, 0) = (gridTranslate n D T c₁)^[m] (0, 0) := by
    -- By definition of $cond3$, we know that $orbit(c₂, 0) \subseteq orbit(c₁, 0)$.
    have h_orbit_subset : (gridTranslate n D T c₂) (0, 0) ∈ gridOrbit n D T c₁ (0, 0) := by
      have h_orbit_subset : gridOrbit n D T c₂ (0, 0) ⊆ gridOrbit n D T c₁ (0, 0) := by
        intro x hx
        obtain ⟨o₁, ho₁⟩ := h3 (gridOrbit n D T c₂ (0, 0)) (by
        exact ⟨ _, rfl ⟩)
        generalize_proofs at *; (
        -- Since $o₁$ is in the orbit partition of $c₁$, it must be the orbit of some point under $c₁$. But since $o₁$ contains $(0,0)$, that point must be $(0,0)$ itself.
        obtain ⟨pt, hpt⟩ : ∃ pt, o₁ = gridOrbit n D T c₁ pt := by
          exact Exists.imp ( by tauto ) ( Set.mem_setOf.mp ho₁.1 )
        generalize_proofs at *; (
        have h_pt_zero : pt ∈ gridOrbit n D T c₁ (0, 0) := by
          have h_pt_zero : (0, 0) ∈ gridOrbit n D T c₁ pt := by
            exact hpt ▸ ho₁.2 ( Set.mem_setOf.mpr ⟨ 0, rfl ⟩ ) |> fun h => by simpa using h;
          generalize_proofs at *; (
          obtain ⟨ k, hk ⟩ := h_pt_zero
          generalize_proofs at *; (
          use k * (T * ∏ i, D i) - k
          generalize_proofs at *; (
          rw [ hk, ← Function.iterate_add_apply ] ; ring; (
          -- Since $T$ and $\prod_{i} D_i$ are both positive, we can simplify the expression.
          have h_simplify : (gridTranslate n D T c₁)^[T * ∏ i, D i] pt = pt := by
            have h_simplify : ∀ m : ℕ, (gridTranslate n D T c₁)^[m] pt = (pt.1 + m * (c₁.p : ZMod T), fun i => pt.2 i + m * (c₁.s i : ZMod (D i))) := by
              exact fun m => gridTranslate_iterate n D T c₁ m pt
            generalize_proofs at *; (
            simp +decide [ h_simplify, Finset.prod_eq_zero_iff, NeZero.ne ];
            exact Prod.ext rfl ( funext fun i => by simp +decide [ Finset.prod_eq_prod_diff_singleton_mul ( Finset.mem_univ i ) ] ) ;)
          generalize_proofs at *; (
          rw [ show k + ( k * T * ∏ i, D i - k ) = k * T * ∏ i, D i by rw [ add_tsub_cancel_of_le ( by nlinarith [ show 0 < T * ∏ i, D i from mul_pos ( NeZero.pos T ) ( Finset.prod_pos fun i _ => NeZero.pos ( D i ) ) ] ) ] ] ; simp +decide [ *, mul_assoc, Function.iterate_mul, Function.iterate_fixed ] ;
          simp +decide [ ← Function.iterate_mul, mul_assoc, h_simplify ];
          rw [ Nat.mul_comm, Function.iterate_mul, Function.iterate_fixed h_simplify ])))))
        generalize_proofs at *; (
        have h_pt_zero : gridOrbit n D T c₁ pt ⊆ gridOrbit n D T c₁ (0, 0) := by
          obtain ⟨ k, hk ⟩ := h_pt_zero
          generalize_proofs at *; (
          intro x hx; obtain ⟨ m, hm ⟩ := hx; use m + k; simp +decide [ hm, Function.iterate_add_apply, hk ] ;)
        generalize_proofs at *; (
        exact h_pt_zero <| hpt ▸ ho₁.2 hx))))
      generalize_proofs at *; (
      exact h_orbit_subset ⟨ 1, rfl ⟩)
    generalize_proofs at *; (
    obtain ⟨ m, hm ⟩ := h_orbit_subset;
    by_cases hm1 : m = 0
    generalize_proofs at *; (
    use T * (∏ i, D i);
    refine' ⟨ Nat.mul_pos ( NeZero.pos T ) ( Finset.prod_pos fun _ _ => NeZero.pos _ ), _ ⟩
    generalize_proofs at *; (
    -- By definition of $gridTranslate$, we have:
    have h_gridTranslate_iterate : ∀ k : ℕ, (gridTranslate n D T c₁)^[k] (0, 0) = (k * (c₁.p : ZMod T), fun i => k * (c₁.s i : ZMod (D i))) := by
      intro k; simpa using gridTranslate_iterate n D T c₁ k (0, 0)
    generalize_proofs at *; (
    simp_all +decide [ ZMod.natCast_eq_zero_iff ];
    ext i; simp +decide [ Finset.prod_eq_prod_diff_singleton_mul ( Finset.mem_univ i ) ] ;)));
    exact ⟨ m, Nat.pos_of_ne_zero hm1, hm ⟩)
  generalize_proofs at *; exact ⟨m, hm.left, by
    funext ⟨t, x⟩; simp [gridTranslate] at *; (
    -- By definition of gridTranslate, we have that applying it m times is equivalent to adding m times the translation vector.
    have h_iter : ∀ m : ℕ, ∀ (pt : SpacetimeGrid n D T), (gridTranslate n D T c₁)^[m] pt = (pt.1 + m * (c₁.p : ZMod T), fun i => pt.2 i + m * (c₁.s i : ZMod (D i))) := by
      exact gridTranslate_iterate n D T c₁
    generalize_proofs at *; (
    simp_all +decide [ funext_iff ]));⟩;

/-
Prove that condition (iii) implies condition (ii) to complete the equivalence.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

/-- Theorem 2: Exact Characterization of Universal Refinement and Monotonicity (Six-Way Equivalence). -/
theorem Theorem2 (c₁ c₂ : Candidate n) :
    (cond1_mod n D T c₁ c₂ ↔ cond2 n D T c₁ c₂) ∧
    (cond2 n D T c₁ c₂ ↔ cond3 n D T c₁ c₂) ∧
    (cond3 n D T c₁ c₂ ↔ cond4 n D T c₁ c₂) ∧
    (cond4 n D T c₁ c₂ ↔ cond5 n D T c₁ c₂) ∧
    (cond5 n D T c₁ c₂ ↔ cond6 n D T c₁ c₂) := by
  have h12 : cond1_mod n D T c₁ c₂ ↔ cond2 n D T c₁ c₂ := cond1_mod_iff_cond2 n D T c₁ c₂
  have h23 : cond2 n D T c₁ c₂ → cond3 n D T c₁ c₂ := cond2_imp_cond3 n D T c₁ c₂
  have h34 : cond3 n D T c₁ c₂ → cond4 n D T c₁ c₂ := cond3_imp_cond4 n D T c₁ c₂
  have h45 : cond4 n D T c₁ c₂ → cond5 n D T c₁ c₂ := cond4_imp_cond5 n D T c₁ c₂
  have h53 : cond5 n D T c₁ c₂ → cond3 n D T c₁ c₂ := cond5_imp_cond3 n D T c₁ c₂
  have h36 : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := cond3_imp_cond6_success n D T c₁ c₂
  have h63 : cond6 n D T c₁ c₂ → cond3 n D T c₁ c₂ := cond6_imp_cond3 n D T c₁ c₂

  have h35 : cond3 n D T c₁ c₂ ↔ cond5 n D T c₁ c₂ := ⟨fun h => h45 (h34 h), h53⟩
  have h36_iff : cond3 n D T c₁ c₂ ↔ cond6 n D T c₁ c₂ := ⟨h36, h63⟩

  have h32 : cond3 n D T c₁ c₂ → cond2 n D T c₁ c₂ := cond3_imp_cond2 n D T c₁ c₂
  refine ⟨h12, ⟨h23, h32⟩, ⟨h34, fun h => h53 (h45 h)⟩, ⟨h45, fun h => h34 (h53 h)⟩, ⟨?_, ?_⟩⟩
  · exact fun h => h36_iff.mp (h35.mpr h)
  · exact fun h => h35.mp (h36_iff.mpr h)

/-
Prove Theorem 2 (Final) by combining all the proved implications.
-/
open BigOperators Classical

variable (n : ℕ) (D : Fin n → ℕ) (T : ℕ)
variable [NeZero T] [∀ i, NeZero (D i)]

/-- Theorem 2: Exact Characterization of Universal Refinement and Monotonicity (Six-Way Equivalence).
    This is the final version combining all proved lemmas. -/
theorem Theorem2_Final (c₁ c₂ : Candidate n) :
    (cond1_mod n D T c₁ c₂ ↔ cond2 n D T c₁ c₂) ∧
    (cond2 n D T c₁ c₂ ↔ cond3 n D T c₁ c₂) ∧
    (cond3 n D T c₁ c₂ ↔ cond4 n D T c₁ c₂) ∧
    (cond4 n D T c₁ c₂ ↔ cond5 n D T c₁ c₂) ∧
    (cond5 n D T c₁ c₂ ↔ cond6 n D T c₁ c₂) := by
  have h12 : cond1_mod n D T c₁ c₂ ↔ cond2 n D T c₁ c₂ := cond1_mod_iff_cond2 n D T c₁ c₂
  have h23 : cond2 n D T c₁ c₂ → cond3 n D T c₁ c₂ := cond2_imp_cond3 n D T c₁ c₂
  have h32 : cond3 n D T c₁ c₂ → cond2 n D T c₁ c₂ := cond3_imp_cond2 n D T c₁ c₂
  have h34 : cond3 n D T c₁ c₂ → cond4 n D T c₁ c₂ := cond3_imp_cond4 n D T c₁ c₂
  have h45 : cond4 n D T c₁ c₂ → cond5 n D T c₁ c₂ := cond4_imp_cond5 n D T c₁ c₂
  have h53 : cond5 n D T c₁ c₂ → cond3 n D T c₁ c₂ := cond5_imp_cond3 n D T c₁ c₂
  have h36 : cond3 n D T c₁ c₂ → cond6 n D T c₁ c₂ := cond3_imp_cond6_success n D T c₁ c₂
  have h63 : cond6 n D T c₁ c₂ → cond3 n D T c₁ c₂ := cond6_imp_cond3 n D T c₁ c₂
  
  have h23_iff : cond2 n D T c₁ c₂ ↔ cond3 n D T c₁ c₂ := ⟨h23, h32⟩
  have h34_iff : cond3 n D T c₁ c₂ ↔ cond4 n D T c₁ c₂ := ⟨h34, fun h => h53 (h45 h)⟩
  have h45_iff : cond4 n D T c₁ c₂ ↔ cond5 n D T c₁ c₂ := ⟨h45, fun h => h34 (h53 h)⟩
  have h56_iff : cond5 n D T c₁ c₂ ↔ cond6 n D T c₁ c₂ := ⟨fun h => h36 (h53 h), fun h => h45 (h34 (h63 h))⟩
  
  exact ⟨h12, h23_iff, h34_iff, h45_iff, h56_iff⟩

