/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 55d8f9ef-88de-47e3-9094-247814dd72da

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalization of Theorem 2 condition (vi) from the paper "Model Selection Stabilization for Relative-Periodic Decomposition of Cellular Automaton Spacetimes".

Definitions:
- `Spacetime`: A binary spacetime as a function from indices to Booleans.
- `empiricalProb`: The empirical probability of 1s in a subset of the spacetime.
- `partNLL`: The NLL contribution of a single part of the partition, using binary entropy.
- `totalNLL`: The total NLL of a spacetime with respect to a partition.
- `isConstantOn`: Predicate for a spacetime being constant on the parts of a partition.

Theorems:
- `refinement_implies_NLL_le`: Proves that if partition P₂ refines P₁, then NLL_U(P₂) ≤ NLL_U(P₁) for all binary spacetimes U. This relies on the concavity of the binary entropy function (Jensen's inequality).
- `not_refinement_implies_exists_counterexample`: Proves the necessity direction. If P₂ does not refine P₁, there exists a spacetime U constant on P₁ (NLL = 0) such that NLL_U(P₂) > 0. This is constructed by finding a part in P₂ that intersects multiple parts of P₁ (or is not contained in any single part of P₁) and assigning different values to the intersections.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
A binary spacetime is a function from indices to Booleans.
-/
def Spacetime (ι : Type*) := ι → Bool

/-
The empirical probability of 1s in a subset of the spacetime.
-/
noncomputable def empiricalProb {ι : Type*} [Fintype ι] [DecidableEq ι] (U : Spacetime ι) (s : Finset ι) : ℝ :=
  (s.filter (fun i => U i)).card / s.card

/-
The NLL contribution of a single part of the partition.
-/
noncomputable def partNLL {ι : Type*} [Fintype ι] [DecidableEq ι] (U : Spacetime ι) (s : Finset ι) : ℝ :=
  s.card * Real.binEntropy (empiricalProb U s)

/-
The total NLL of a spacetime with respect to a partition.
-/
noncomputable def totalNLL {ι : Type*} [Fintype ι] [DecidableEq ι] (U : Spacetime ι) (P : Finpartition (Finset.univ : Finset ι)) : ℝ :=
  ∑ s ∈ P.parts, partNLL U s

/-
A spacetime is constant on a partition if it takes the same value for all elements in each part.
-/
def isConstantOn {ι : Type*} [Fintype ι] [DecidableEq ι] (U : Spacetime ι) (P : Finpartition (Finset.univ : Finset ι)) : Prop :=
  ∀ s ∈ P.parts, ∀ i j, i ∈ s → j ∈ s → U i = U j

/-
If partition P₂ refines P₁, then the total NLL of any spacetime U with respect to P₂ is less than or equal to the total NLL with respect to P₁.
-/
theorem refinement_implies_NLL_le {ι : Type*} [Fintype ι] [DecidableEq ι]
  (P₁ P₂ : Finpartition (Finset.univ : Finset ι)) (h : P₂ ≤ P₁) (U : Spacetime ι) :
  totalNLL U P₂ ≤ totalNLL U P₁ := by
    -- By Lemma 2, the concavity of H_b implies that n * H_b(θ) ≥ Σ n_α * H_b(θ_α) for each coarse orbit class O ∈ P₁.
    have h_concave : ∀ s ∈ P₁.parts, ∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), partNLL U s' ≤ partNLL U s := by
      intro s hs
      have h_split : s = Finset.biUnion (P₂.parts.filter (fun s' => s' ⊆ s)) id := by
        ext x;
        obtain ⟨ t, ht, hx ⟩ := P₂.exists_mem ( Finset.mem_univ x );
        have := h ht; simp_all +decide [ Finset.subset_iff ] ;
        obtain ⟨ c, hc, hc' ⟩ := this; have := P₁.disjoint hc hs; simp_all +decide [ Finset.disjoint_left ] ;
        by_cases h : c = s <;> aesop
      have h_card : s.card = ∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), s'.card := by
        rw [ ← Finset.card_biUnion ];
        · exact congr_arg Finset.card h_split;
        · exact fun x hx y hy hxy => P₂.disjoint ( Finset.mem_filter.mp hx |>.1 ) ( Finset.mem_filter.mp hy |>.1 ) hxy
      have h_filter : s.filter (fun i => U i) = Finset.biUnion (P₂.parts.filter (fun s' => s' ⊆ s)) (fun s' => s'.filter (fun i => U i)) := by
        grind
      have h_filter_card : (s.filter (fun i => U i)).card = ∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), (s'.filter (fun i => U i)).card := by
        rw [ h_filter, Finset.card_biUnion ] ; simp +contextual [ Finset.disjoint_left ] ; (
        intro x hx y hy hxy; simp +contextual [ Finset.disjoint_left ] at hx hy hxy ⊢; ( contrapose! hxy; ) ; ( have := P₂.disjoint hx.1 hy.1; simp +decide [ Finset.disjoint_left ] at this ⊢; ) ; (
        exact Classical.not_not.1 fun h => this h hxy.choose_spec.1 hxy.choose_spec.2.2; ) ;)
      have h_prob : empiricalProb U s = (∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), s'.card * empiricalProb U s') / s.card := by
        unfold empiricalProb; simp +decide [ h_card, h_filter_card ] ; ring;
        rw [ mul_comm ] ; refine' congr_arg _ ( Finset.sum_congr rfl fun x hx => _ ) ; by_cases hx' : x = ∅ <;> simp +decide [ hx', mul_comm ] ;
      have h_partNLL : partNLL U s = s.card * Real.binEntropy (∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), s'.card * empiricalProb U s' / s.card) := by
        rw [ ← Finset.sum_div _ _ _, partNLL, h_prob ]
      have h_partNLL_le : ∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), partNLL U s' ≤ s.card * Real.binEntropy (∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), s'.card * empiricalProb U s' / s.card) := by
        have h_concave : ConcaveOn ℝ (Set.Icc 0 1) Real.binEntropy := by
          apply_rules [ StrictConcaveOn.concaveOn ];
          exact?;
        have h_jensen : ∀ {w : Finset ι → ℝ}, (∀ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), 0 ≤ w s') → (∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), w s') = 1 → ∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), w s' * Real.binEntropy (empiricalProb U s') ≤ Real.binEntropy (∑ s' ∈ P₂.parts.filter (fun s' => s' ⊆ s), w s' * empiricalProb U s') := by
          intros w hw_nonneg hw_sum
          apply h_concave.le_map_sum
          all_goals norm_num [ hw_nonneg, hw_sum ];
          · exact fun s' hs' hs'_sub => hw_nonneg s' ( Finset.mem_filter.mpr ⟨ hs', hs'_sub ⟩ );
          · exact fun i hi hi' => ⟨ div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ), div_le_one_of_le₀ ( mod_cast Finset.card_le_card ( Finset.filter_subset _ _ ) ) ( Nat.cast_nonneg _ ) ⟩;
        by_cases h : s = ∅ <;> simp +decide [ h, partNLL ] at *;
        convert mul_le_mul_of_nonneg_left ( h_jensen ( fun s' hs' hs'' => show ( 0 : ℝ ) ≤ s'.card / s.card by positivity ) ( show ∑ s' ∈ P₂.parts with s' ⊆ s, ( s'.card : ℝ ) / s.card = 1 by rw [ ← Finset.sum_div, div_eq_iff ] <;> norm_cast <;> linarith [ Finset.card_pos.mpr ( Finset.nonempty_of_ne_empty ( show s ≠ ∅ by rintro rfl; simp +decide at hs ) ) ] ) ) ( Nat.cast_nonneg s.card ) using 1 <;> norm_num [ Finset.sum_div _ _ _, mul_div_cancel₀ ] ; ring!;
        · simp +decide [ mul_assoc, mul_comm, mul_left_comm, Finset.mul_sum _ _ _, ne_of_gt ( show 0 < s.card from Finset.card_pos.mpr ( Finset.nonempty_of_ne_empty ( show s ≠ ∅ by rintro rfl; simp +decide at hs ) ) ) ];
        · exact Or.inl ( by congr; ext; ring )
      exact (by
      convert h_partNLL_le using 1);
    convert Finset.sum_le_sum h_concave using 1;
    rw [ ← Finset.sum_biUnion ];
    · refine' Finset.sum_subset _ _ <;> intro s' hs' <;> aesop;
    · intro s hs t ht hst; simp_all +decide [ Finset.disjoint_left ] ;
      intro a ha has hat; have := P₁.disjoint hs ht hst; simp_all +decide [ Finset.disjoint_left ] ;
      exact this ( has ( Classical.choose_spec ( Finset.nonempty_of_ne_empty ( by aesop_cat ) ) ) ) ( hat ( Classical.choose_spec ( Finset.nonempty_of_ne_empty ( by aesop_cat ) ) ) )

/-
If P₂ does not refine P₁, there exists a spacetime U that is constant on P₁ (so NLL is 0) but has positive NLL on P₂.
-/
theorem not_refinement_implies_exists_counterexample {ι : Type*} [Fintype ι] [DecidableEq ι]
  (P₁ P₂ : Finpartition (Finset.univ : Finset ι)) (h : ¬ P₂ ≤ P₁) :
  ∃ U : Spacetime ι, isConstantOn U P₁ ∧ totalNLL U P₁ = 0 ∧ totalNLL U P₂ > 0 := by
    -- Let's choose any part $A \in P₂$ that is not contained in any part of $P₁$.
    obtain ⟨A, hA₁, hA₂⟩ : ∃ A ∈ P₂.parts, ∃ B C : Finset ι, B ∈ P₁.parts ∧ C ∈ P₁.parts ∧ B ≠ C ∧ (A ∩ B).Nonempty ∧ (A ∩ C).Nonempty := by
      contrapose! h with h_contra
      generalize_proofs at *; (
      intro A hA
      obtain ⟨B, hB₁, hB₂⟩ : ∃ B ∈ P₁.parts, (A ∩ B).Nonempty := by
        have h_inter : ∃ i ∈ A, ∃ B ∈ P₁.parts, i ∈ B := by
          obtain ⟨ i, hi ⟩ := Finset.nonempty_of_ne_empty ( show A ≠ ∅ from by intro h; have := P₂.ne_bot hA; aesop ) ; exact ⟨ i, hi, by have := P₁.exists_mem ( Finset.mem_univ i ) ; aesop ⟩ ;
        generalize_proofs at *; (
        exact ⟨ _, h_inter.choose_spec.2.choose_spec.1, ⟨ _, Finset.mem_inter.2 ⟨ h_inter.choose_spec.1, h_inter.choose_spec.2.choose_spec.2 ⟩ ⟩ ⟩)
      generalize_proofs at *; (
      refine' ⟨ B, hB₁, fun x hx => _ ⟩
      generalize_proofs at *; (
      obtain ⟨C, hC₁, hC₂⟩ : ∃ C ∈ P₁.parts, x ∈ C := by
        have := P₁.exists_mem ( Finset.mem_univ x ) ; aesop;
      generalize_proofs at *; (
      specialize h_contra A hA B C hB₁ hC₁ ; simp_all +decide [ Finset.Nonempty ] ; contrapose! h_contra ; aesop;))));
    obtain ⟨ B, C, hB, hC, hBC, ⟨ i, hi ⟩, ⟨ j, hj ⟩ ⟩ := hA₂; use fun x => if x ∈ B then Bool.true else Bool.false; simp_all +decide [ isConstantOn ] ;
    refine' ⟨ _, _, _ ⟩;
    · intro s hs i j hi hj; have := P₁.disjoint hs hB; have := P₁.disjoint hs hC; simp_all +decide [ Finset.disjoint_left ] ;
      by_cases h : s = B <;> by_cases h' : s = C <;> aesop;
    · refine' Finset.sum_eq_zero fun s hs => _;
      by_cases h : s = B <;> simp_all +decide [ partNLL ];
      · unfold empiricalProb; simp +decide [ Finset.filter_mem_eq_inter, Finset.inter_comm ] ;
        by_cases h : B = ∅ <;> simp +decide [ h ];
      · -- Since $s \neq B$, we have $s \cap B = \emptyset$.
        have h_inter_empty : s ∩ B = ∅ := by
          exact Finset.disjoint_iff_inter_eq_empty.mp ( P₁.disjoint hs hB h );
        simp_all +decide [ Finset.ext_iff, empiricalProb ];
        rw [ Finset.card_eq_zero.mpr ] <;> aesop;
    · refine' lt_of_lt_of_le _ ( Finset.single_le_sum ( fun x _ => _ ) hA₁ ) <;> simp_all +decide [ totalNLL, partNLL ];
      · refine' mul_pos ( Nat.cast_pos.mpr ( Finset.card_pos.mpr ⟨ i, hi.1 ⟩ ) ) ( Real.binEntropy_pos _ _ ) <;> simp_all +decide [ empiricalProb ];
        · exact div_pos ( Nat.cast_pos.mpr ( Finset.card_pos.mpr ⟨ i, by aesop ⟩ ) ) ( Nat.cast_pos.mpr ( Finset.card_pos.mpr ⟨ i, by aesop ⟩ ) );
        · rw [ div_lt_one ] <;> norm_cast <;> norm_num [ Finset.card_pos ];
          · refine' Finset.card_lt_card _;
            simp_all +decide [ Finset.ssubset_def, Finset.subset_iff ];
            exact ⟨ j, hj.1, fun hj' => hBC <| by have := P₁.disjoint hB hC; simp_all +decide [ Finset.disjoint_left ] ⟩;
          · exact ⟨ i, hi.1 ⟩;
      · refine' mul_nonneg ( Nat.cast_nonneg _ ) ( _ );
        refine' add_nonneg _ _ <;> by_cases h : empiricalProb ( fun x => Decidable.decide ( x ∈ B ) ) x = 0 <;> simp_all +decide [ Real.binEntropy ];
        · exact mul_nonpos_of_nonneg_of_nonpos ( by exact div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( Real.log_nonpos ( by exact div_nonneg ( Nat.cast_nonneg _ ) ( Nat.cast_nonneg _ ) ) ( by exact div_le_one_of_le₀ ( by exact_mod_cast Finset.card_le_card ( Finset.filter_subset _ _ ) ) ( Nat.cast_nonneg _ ) ) );
        · refine' mul_nonpos_of_nonneg_of_nonpos _ _ <;> norm_num [ empiricalProb ] at *;
          · exact div_le_one_of_le₀ ( mod_cast Finset.card_filter_le _ _ ) ( Nat.cast_nonneg _ );
          · exact Real.log_nonpos ( sub_nonneg.2 <| div_le_one_of_le₀ ( mod_cast Finset.card_le_card <| Finset.filter_subset _ _ ) <| Nat.cast_nonneg _ ) <| sub_le_self _ <| div_nonneg ( Nat.cast_nonneg _ ) <| Nat.cast_nonneg _