/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: d490d84d-12ca-4724-ab38-21e45e8df18c

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes the theory of model selection stabilization for relative-periodic decomposition of cellular automaton spacetimes.
It includes:
1. Definitions of relative-periodic models, orbit classes, and Hamming distance.
2. Theorem 1: Optimal Hamming projection via majority vote on orbit classes (`OptimalProjection_minimizes_HammingDistance`).
3. Theorem 2: Monotonicity of residual counts under velocity-matched refinement (`Monotonicity_Under_Refinement`).
4. Definition of Bernoulli NML score and its asymptotic decomposition (Theorem 3(i): `NML_decomposition`).
5. Theorem 3(ii) & (iii): Stabilization of NML selection, proving that suboptimal candidates are eliminated (`Elimination_of_Suboptimal`) and the selection locks to a unique minimizer (`Stabilization_Unique_Minimizer`).
6. Theorem 4: Nonidentifiability of the "true" background period in general, demonstrated via a `MixedSpacetime` construction where a higher period model is preferred (`Nonidentifiability`).
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check Real.binEntropy

/-
Definition of Spacetime and IsRelativePeriodic.
-/
/-- A cellular automaton spacetime is a function from time and space to booleans. -/
def Spacetime (S : Type*) := ℕ → S → Bool

variable {S : Type*} [AddCommGroup S]

/-- The relative-periodic model class B(p, s). -/
def IsRelativePeriodic (B : Spacetime S) (p : ℕ) (s : S) : Prop :=
  ∀ t x, B (t + p) (x + s) = B t x

/-
Definitions for OrbitRel, HammingDistance, Count1, and Count0.
-/
open BigOperators Classical

variable {S : Type*} [AddCommGroup S] [Fintype S] [DecidableEq S]

/-- The orbit relation generated by a model (p, s). -/
def OrbitRel (p : ℕ) (s : S) (pt1 pt2 : ℕ × S) : Prop :=
  ∃ k : ℤ, (pt2.1 : ℤ) = (pt1.1 : ℤ) + k * (p : ℤ) ∧ pt2.2 = pt1.2 + k • s

/-- The Hamming distance between two spacetimes over a window T. -/
def HammingDistance (U B : Spacetime S) (T : ℕ) : ℕ :=
  ∑ t ∈ Finset.range T, ∑ x : S, if U t x ≠ B t x then 1 else 0

/-- The count of 1s in a set of points within a window T. -/
def Count1 (U : Spacetime S) (T : ℕ) (Points : Set (ℕ × S)) : ℕ :=
  ∑ t ∈ Finset.range T, ∑ x : S, if (t, x) ∈ Points ∧ U t x = true then 1 else 0

/-- The count of 0s in a set of points within a window T. -/
def Count0 (U : Spacetime S) (T : ℕ) (Points : Set (ℕ × S)) : ℕ :=
  ∑ t ∈ Finset.range T, ∑ x : S, if (t, x) ∈ Points ∧ U t x = false then 1 else 0

/-
OrbitRel is reflexive.
-/
theorem OrbitRel_refl (p : ℕ) (s : S) : Reflexive (OrbitRel p s) := by
  exact fun x => ⟨ 0, by simp +decide ⟩

/-
OrbitRel is symmetric.
-/
theorem OrbitRel_symm (p : ℕ) (s : S) : Symmetric (OrbitRel p s) := by
  intro x y hxy
  obtain ⟨k, hk⟩ := hxy
  use -k
  simp [hk]

/-
OrbitRel is transitive.
-/
theorem OrbitRel_trans (p : ℕ) (s : S) : Transitive (OrbitRel p s) := by
  -- To prove transitivity, assume there exist integers $k$ and $m$ such that $(t2, x2) = (t1 + k*p, x1 + k*s)$ and $(t3, x3) = (t2 + m*p, x2 + m*s)$.
  intro t1 t2 t3 h1 h2
  obtain ⟨k, hk⟩ := h1
  obtain ⟨m, hm⟩ := h2
  use k + m
  simp [hk, hm];
  exact ⟨ by ring, by rw [ add_assoc, add_smul ] ⟩

/-
Definition of OrbitMap and OrbitClass. OrbitMap maps a spacetime point to a canonical representative in `Fin p × S`. OrbitClass is the fiber of this map.
-/
variable {S : Type*} [AddCommGroup S] [Fintype S] [DecidableEq S]

/-- The canonical representative map for the orbit relation. -/
def OrbitMap (p : ℕ) (s : S) (hp : p > 0) (pt : ℕ × S) : Fin p × S :=
  let t := pt.1
  let x := pt.2
  (⟨t % p, Nat.mod_lt t hp⟩, x - (t / p) • s)

/-- The orbit class corresponding to an index. -/
def OrbitClass (p : ℕ) (s : S) (hp : p > 0) (idx : Fin p × S) : Set (ℕ × S) :=
  { pt | OrbitMap p s hp pt = idx }

/-
Definitions for OrbitCount1_idx, OrbitCount0_idx, and OptimalProjection. OptimalProjection uses majority voting with ties broken to 1.
-/
/-- The count of 1s in an orbit class specified by an index. -/
def OrbitCount1_idx (U : Spacetime S) (T : ℕ) (p : ℕ) (s : S) (hp : p > 0) (idx : Fin p × S) : ℕ :=
  Count1 U T (OrbitClass p s hp idx)

/-- The count of 0s in an orbit class specified by an index. -/
def OrbitCount0_idx (U : Spacetime S) (T : ℕ) (p : ℕ) (s : S) (hp : p > 0) (idx : Fin p × S) : ℕ :=
  Count0 U T (OrbitClass p s hp idx)

/-- The optimal projection B* constructed by majority vote on orbit classes. Ties broken to 1. -/
def OptimalProjection (U : Spacetime S) (T : ℕ) (p : ℕ) (s : S) (hp : p > 0) : Spacetime S :=
  fun t x =>
    let idx := OrbitMap p s hp (t, x)
    let n1 := OrbitCount1_idx U T p s hp idx
    let n0 := OrbitCount0_idx U T p s hp idx
    n1 ≥ n0

/-
The optimal projection is relative-periodic.
-/
theorem OptimalProjection_is_RelativePeriodic (U : Spacetime S) (T : ℕ) (p : ℕ) (s : S) (hp : p > 0) :
  IsRelativePeriodic (OptimalProjection U T p s hp) p s := by
    intro t x; simp +decide [ *, OptimalProjection ] ; ring;
    simp +decide [ OrbitMap, Nat.add_mod, Nat.mod_eq_of_lt hp ];
    simp +decide [ Nat.add_div, hp ] ; ring;
    simp +decide [ add_smul, sub_add_eq_sub_sub ]

/-
Theorem 1: The optimal projection minimizes the Hamming distance among all relative-periodic models with parameters (p, s).
-/
theorem OptimalProjection_minimizes_HammingDistance (U : Spacetime S) (T : ℕ) (p : ℕ) (s : S) (hp : p > 0) :
  ∀ B, IsRelativePeriodic B p s → HammingDistance U B T ≥ HammingDistance U (OptimalProjection U T p s hp) T := by
    -- Since we have the inequality for each orbit's Hamming distance, we can apply `Finset.sum_le_sum` to combine these inequalities.
    have h_sum : ∀ (B : Spacetime S), IsRelativePeriodic B p s → ∀ i : Fin p × S, HammingDistance U B T ≥ HammingDistance U (OptimalProjection U T p s hp) T := by
      intro B hB a
      have h_orbit : ∀ t x, B t x = B (t % p) (x - (t / p) • s) := by
        intro t x
        have h_orbit_step : ∀ k : ℕ, B (t % p + k * p) (x - (t / p) • s + k • s) = B (t % p) (x - (t / p) • s) := by
          intro k
          induction' k with k ih
          generalize_proofs at *; (
          simp +decide [ hB ]);
          have := hB ( t % p + k * p ) ( x - ( t / p ) • s + k • s ) ; simp_all +decide [ add_mul, ← add_assoc ] ;
          simpa only [ add_smul, one_smul, add_assoc ] using this
        generalize_proofs at *; (
        convert h_orbit_step ( t / p ) using 1 ; simp +decide [ Nat.mod_add_div' ]);
      -- Since $B$ is relative-periodic, we can express its Hamming distance in terms of the counts of 1s and 0s in each orbit class.
      have h_hamming : HammingDistance U B T = ∑ i : Fin p × S, (if B (i.1.val) (i.2) then Count0 U T (OrbitClass p s hp i) else Count1 U T (OrbitClass p s hp i)) := by
        have h_hamming : HammingDistance U B T = ∑ t ∈ Finset.range T, ∑ x : S, (if B t x then if U t x = false then 1 else 0 else if U t x = true then 1 else 0) := by
          exact Finset.sum_congr rfl fun t ht => Finset.sum_congr rfl fun x hx => by by_cases h : B t x <;> by_cases h' : U t x <;> simp +decide [ h, h' ] ;
        have h_hamming : HammingDistance U B T = ∑ i : Fin p × S, ∑ t ∈ Finset.range T, ∑ x : S, (if (t, x) ∈ OrbitClass p s hp i then (if B (i.1.val) (i.2) then if U t x = false then 1 else 0 else if U t x = true then 1 else 0) else 0) := by
          rw [ h_hamming, Finset.sum_comm ];
          rw [ Finset.sum_comm, Finset.sum_congr rfl ];
          rw [ Finset.sum_comm ];
          intro t ht;
          rw [ ← Finset.sum_comm, Finset.sum_congr rfl ];
          intro x hx
          simp [OrbitClass];
          rw [ Finset.sum_eq_single ( OrbitMap p s hp ( t, x ) ) ] <;> simp +decide [ OrbitMap ];
          · rw [ h_orbit t x ];
          · grind +ring;
        convert h_hamming using 2;
        split_ifs <;> simp +decide [ *, Count0, Count1 ];
        · simp +decide [ Finset.sum_ite ];
          simp +decide only [Finset.filter_filter];
        · simp +decide [ Finset.sum_ite ];
          simp +decide only [Finset.filter_filter];
      -- Similarly, we can express the Hamming distance of the optimal projection in terms of the counts of 1s and 0s in each orbit class.
      have h_hamming_optimal : HammingDistance U (OptimalProjection U T p s hp) T = ∑ i : Fin p × S, (if OrbitCount1_idx U T p s hp i ≥ OrbitCount0_idx U T p s hp i then Count0 U T (OrbitClass p s hp i) else Count1 U T (OrbitClass p s hp i)) := by
        -- By definition of `OptimalProjection`, we can split the sum into two parts: one where the optimal projection is 1 and one where it is 0.
        have h_split : ∑ t ∈ Finset.range T, ∑ x : S, (if U t x ≠ OptimalProjection U T p s hp t x then 1 else 0) = ∑ i : Fin p × S, ∑ t ∈ Finset.range T, ∑ x : S, (if (t, x) ∈ OrbitClass p s hp i then (if U t x ≠ (if OrbitCount1_idx U T p s hp i ≥ OrbitCount0_idx U T p s hp i then true else false) then 1 else 0) else 0) := by
          rw [ Finset.sum_comm, Finset.sum_congr rfl ];
          rw [ Finset.sum_comm ];
          exact?;
          intro x hx
          apply Finset.sum_congr rfl
          intro y hy
          simp [OrbitClass];
          unfold OptimalProjection; simp +decide [ OrbitMap ] ;
        convert h_split using 2;
        split_ifs <;> simp +decide [ *, Count0, Count1 ];
        · simp +decide [ Finset.sum_ite ];
          simp +decide only [Finset.filter_filter];
        · simp +decide [ Finset.sum_ite ];
          simp +decide only [Finset.filter_filter];
      rw [ h_hamming, h_hamming_optimal ];
      refine' Finset.sum_le_sum fun i _ => _;
      split_ifs <;> norm_num;
      · exact?;
      · exact le_of_not_ge ‹_›;
    exact fun B hB => h_sum B hB ⟨ ⟨ 0, hp ⟩, 0 ⟩

/-
If (p2, s2) is a velocity-matched multiple of (p1, s1), then the orbit relation of (p2, s2) implies the orbit relation of (p1, s1).
-/
theorem OrbitRel_refinement (p1 p2 : ℕ) (s1 s2 : S) (m : ℕ) (h_p : p2 = m * p1) (h_s : s2 = m • s1) :
  ∀ x y, OrbitRel p2 s2 x y → OrbitRel p1 s1 x y := by
    rintro ⟨ t, x ⟩ ⟨ u, y ⟩ ⟨ k, hk ⟩ ; use k * m; simp_all +decide [ mul_assoc, mul_left_comm, mul_comm ] ;
    simp +decide [ mul_comm, MulAction.mul_smul ]

/-
Theorem 2: If (p2, s2) is a velocity-matched multiple of (p1, s1), then the minimum Hamming distance for (p2, s2) is less than or equal to that for (p1, s1).
-/
/-- The minimum Hamming distance achievable by a relative-periodic model with parameters (p, s). -/
def MinHammingDistance (U : Spacetime S) (T : ℕ) (p : ℕ) (s : S) (hp : p > 0) : ℕ :=
  HammingDistance U (OptimalProjection U T p s hp) T

/-- Theorem 2: Monotonicity under Velocity-Matched Refinement. -/
theorem Monotonicity_Under_Refinement (U : Spacetime S) (T : ℕ) (p1 p2 : ℕ) (s1 s2 : S) (m : ℕ)
  (hp1 : p1 > 0) (hp2 : p2 > 0) (h_p : p2 = m * p1) (h_s : s2 = m • s1) :
  MinHammingDistance U T p2 s2 hp2 ≤ MinHammingDistance U T p1 s1 hp1 := by
    -- Since $p2 = m * p1$ and $s2 = m • s1$, any relative-periodic model with $(p1, s1)$ is also relative-periodic with $(p2, s2)$.
    have h_rel_periodic : ∀ B : Spacetime S, IsRelativePeriodic B p1 s1 → IsRelativePeriodic B p2 s2 := by
      intro B hB;
      intro t x; subst_vars; induction' m with m ih <;> simp_all +decide [ mul_assoc, add_mul ] ;
      by_cases hm : 0 < m <;> simp_all +decide [ add_smul, ← add_assoc ];
      · rw [ ← ih, hB ];
      · exact hB t x;
    apply le_trans (OptimalProjection_minimizes_HammingDistance U T p2 s2 hp2 (OptimalProjection U T p1 s1 hp1) (h_rel_periodic _ (OptimalProjection_is_RelativePeriodic U T p1 s1 hp1))) (by
    rfl)

/-
Definition of OrbitSize.
-/
/-- The total size of an orbit class within a window T. -/
def OrbitSize (T : ℕ) (O : Set (ℕ × S)) : ℕ :=
  ∑ t ∈ Finset.range T, ∑ x : S, if (t, x) ∈ O then 1 else 0

/-
Definition of NLL and NML score. NLL is the sum of binary entropies of orbit classes weighted by their size. NML adds a complexity penalty proportional to the number of orbit classes and log T.
-/
noncomputable def NLL (U : Spacetime S) (T : ℕ) (p : ℕ) (s : S) (hp : p > 0) : ℝ :=
  let k := p * Fintype.card S
  ∑ i : Fin p × S,
    let n := OrbitSize T (OrbitClass p s hp i)
    let n1 := OrbitCount1_idx U T p s hp i
    let theta := (n1 : ℝ) / n
    (n : ℝ) * Real.binEntropy theta

noncomputable def NML (U : Spacetime S) (T : ℕ) (p : ℕ) (s : S) (hp : p > 0) : ℝ :=
  let k := p * Fintype.card S
  NLL U T p s hp + (k : ℝ) / 2 * Real.logb 2 T

/-
Definition of ConvergentFrequencies and AsymptoticRate. ConvergentFrequencies states that the empirical frequency of 1s in each orbit class converges to a limit theta_star. AsymptoticRate is the average binary entropy of these limits.
-/
/-- Assumption A1: Convergent orbit-class frequencies. -/
def ConvergentFrequencies (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0) (theta_star : Fin p × S → ℝ) : Prop :=
  ∀ i : Fin p × S, Filter.Tendsto (fun T => (OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i))) Filter.atTop (nhds (theta_star i))

/-- The asymptotic per-site NLL rate lambda_c. -/
noncomputable def AsymptoticRate (p : ℕ) (s : S) (theta_star : Fin p × S → ℝ) : ℝ :=
  (1 / (p * Fintype.card S : ℝ)) * ∑ i : Fin p × S, Real.binEntropy (theta_star i)

/-
Definitions for N_sites, Candidate structure, and IsNMLMinimizer.
-/
/-- The total number of spacetime sites in a window of length T. -/
def N_sites (T : ℕ) : ℕ := T * Fintype.card S

/-- A candidate model is a pair (p, s). -/
structure Candidate (S : Type*) where
  p : ℕ
  s : S
  hp : p > 0

/-- Predicate: c is an NML minimizer at time T among a set of candidates. -/
def IsNMLMinimizer (U : Spacetime S) (Cs : List (Candidate S)) (T : ℕ) (c : Candidate S) : Prop :=
  c ∈ Cs ∧ ∀ c' ∈ Cs, NML U T c.p c.s c.hp ≤ NML U T c'.p c'.s c'.hp

/-
Under convergent frequencies, the per-site NLL converges to the asymptotic rate lambda_c.
-/
/-- Lemma for Theorem 3(i): The per-site NLL converges to the asymptotic rate. -/
theorem NLL_convergence (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0) (theta_star : Fin p × S → ℝ)
  (h_conv : ConvergentFrequencies U p s hp theta_star) :
  Filter.Tendsto (fun T => NLL U T p s hp / (T * Fintype.card S : ℝ)) Filter.atTop (nhds (AsymptoticRate p s theta_star)) := by
    -- By definition of $NLL$, we can write
    have h_NLL_def : Filter.Tendsto (fun T : ℕ => (∑ i : Fin p × S,
         (OrbitSize T (OrbitClass p s hp i) : ℝ) * Real.binEntropy ((OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i)))) / (T * Fintype.card S : ℝ)) Filter.atTop
         (nhds ((1 / (p * Fintype.card S : ℝ)) * ∑ i : Fin p × S, Real.binEntropy (theta_star i))) := by
           -- By definition of $OrbitSize$, we know that $OrbitSize T (OrbitClass p s hp i) = T / p$ for each $i$.
           have h_orbit_size : ∀ i : Fin p × S, Filter.Tendsto (fun T : ℕ => (OrbitSize T (OrbitClass p s hp i) : ℝ) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds (1 / (p * Fintype.card S : ℝ))) := by
             intro i
             have h_orbit_size : ∀ t x, (t, x) ∈ OrbitClass p s hp i ↔ (t % p = i.1.val ∧ x = i.2 + (t / p) • s) := by
               unfold OrbitClass OrbitMap; aesop;
             -- The number of times $t \equiv i.1.val \pmod{p}$ in the range $0$ to $T-1$ is approximately $T/p$.
             have h_count : ∀ T : ℕ, (Finset.filter (fun t => t % p = i.1.val) (Finset.range T)).card = T / p + (if T % p > i.1.val then 1 else 0) := by
               intro T
               have h_count : Finset.filter (fun t => t % p = i.1.val) (Finset.range T) = Finset.image (fun k => k * p + i.1.val) (Finset.range (T / p + (if T % p > i.1.val then 1 else 0))) := by
                 ext t; simp [Finset.mem_image];
                 constructor <;> intro h
                 all_goals generalize_proofs at *;
                 · use t / p;
                   exact ⟨ by split_ifs <;> nlinarith [ Nat.mod_add_div t p, Nat.mod_add_div T p, Nat.mod_lt t hp, Nat.mod_lt T hp ], by linarith [ Nat.mod_add_div t p ] ⟩;
                 · rcases h with ⟨ a, ha, rfl ⟩ ; split_ifs at ha <;> simp_all +decide [ Nat.add_mod, Nat.mod_eq_of_lt ] ; nlinarith [ Nat.div_add_mod T p, Nat.mod_lt T hp ] ;
                   nlinarith [ Nat.div_mul_le_self T p, Nat.mod_add_div T p, Fin.is_lt i.1 ];
               rw [ h_count, Finset.card_image_of_injective ] <;> simp +decide [ Function.Injective, hp.ne' ];
             -- Using the count result, we can bound the orbit size.
             have h_orbit_size_bound : ∀ T : ℕ, (OrbitSize T (OrbitClass p s hp i)) = (Finset.filter (fun t => t % p = i.1.val) (Finset.range T)).card := by
               intro T; rw [ OrbitSize ] ; simp +decide [ h_orbit_size, Finset.sum_ite ] ;
               rw [ Finset.card_filter ];
               exact Finset.sum_congr rfl fun x hx => by split_ifs <;> simp_all +decide [ Finset.filter_eq', Finset.filter_and ] ;
             -- Using the count result, we can bound the orbit size and show that it converges to $T/p$.
             have h_orbit_size_converge : Filter.Tendsto (fun T : ℕ => ((T / p : ℕ) : ℝ) / T) Filter.atTop (nhds (1 / p)) := by
               -- We can use the fact that $T / p$ is approximately $T / p$ for large $T$.
               have h_approx : Filter.Tendsto (fun T : ℕ => ((T : ℝ) / p - 1) / T) Filter.atTop (nhds (1 / p)) := by
                 ring_nf;
                 exact le_trans ( Filter.Tendsto.sub ( tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with T hT; rw [ mul_right_comm, mul_inv_cancel₀ ( Nat.cast_ne_zero.mpr hT ), one_mul ] ) ) ( tendsto_inverse_atTop_nhds_zero_nat ) ) ( by norm_num );
               refine' tendsto_of_tendsto_of_tendsto_of_le_of_le' h_approx tendsto_const_nhds _ _;
               · filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by rw [ div_le_div_iff_of_pos_right ( by positivity ) ] ; exact sub_le_iff_le_add.mpr ( by rw [ div_le_iff₀ ( by positivity ) ] ; norm_cast; linarith [ Nat.div_add_mod T p, Nat.mod_lt T hp ] ) ;
               · filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by rw [ div_le_div_iff₀ ] <;> norm_cast ; nlinarith [ Nat.div_mul_le_self T p ] ;
             have h_orbit_size_converge : Filter.Tendsto (fun T : ℕ => ((Finset.filter (fun t => t % p = i.1.val) (Finset.range T)).card : ℝ) / T) Filter.atTop (nhds (1 / p)) := by
               simp_all +decide [ add_div ];
               exact le_trans ( Filter.Tendsto.add h_orbit_size_converge <| squeeze_zero ( fun _ => by positivity ) ( fun T => by split_ifs <;> norm_num ) <| tendsto_inverse_atTop_nhds_zero_nat ) ( by norm_num );
             convert h_orbit_size_converge.div_const ( Fintype.card S : ℝ ) using 2 <;> push_cast [ h_orbit_size_bound ] <;> ring;
           have h_limit : ∀ i : Fin p × S, Filter.Tendsto (fun T : ℕ => (OrbitSize T (OrbitClass p s hp i) : ℝ) * Real.binEntropy ((OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i))) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds ((1 / (p * Fintype.card S : ℝ)) * Real.binEntropy (theta_star i))) := by
             intro i
             have h_cont : ContinuousAt (fun x => Real.binEntropy x) (theta_star i) := by
               fun_prop (disch := norm_num)
             generalize_proofs at *; (
             convert Filter.Tendsto.mul ( h_orbit_size i ) ( h_cont.tendsto.comp ( h_conv i ) ) using 2 ; ring!;);
           simpa only [ Finset.mul_sum _ _ _, Finset.sum_div ] using tendsto_finset_sum _ fun i _ => h_limit i;
    convert h_NLL_def using 1

/-
The per-site complexity penalty (k/2 * log2 T) / N(T) converges to 0 as T -> infinity.
-/
/-- Lemma for Theorem 3(i): The per-site complexity penalty vanishes asymptotically. -/
theorem Complexity_convergence (p : ℕ) (s : S) (hp : p > 0) :
  let k := p * Fintype.card S
  Filter.Tendsto (fun T => ((k : ℝ) / 2 * Real.logb 2 T) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds 0) := by
    suffices h_zero : Filter.Tendsto (fun T => ((Real.logb 2 T) / T)) Filter.atTop (nhds 0) by
      convert h_zero.const_mul ( p * Fintype.card S / 2 * ( Fintype.card S : ℝ ) ⁻¹ ) using 2 <;> ring;
      push_cast; ring;
    -- Let's use the change of variables $u = \frac{1}{T}$ to transform the limit expression.
    suffices h_subst : Filter.Tendsto (fun u : ℝ => Real.logb 2 (1 / u) * u) (Filter.map (fun T => 1 / T) Filter.atTop) (nhds 0) by
      exact h_subst.congr ( by simp +contextual [ div_eq_mul_inv ] );
    norm_num [ Real.logb, mul_comm ];
    exact tendsto_nhdsWithin_of_tendsto_nhds ( by simpa [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ] using Filter.Tendsto.neg ( Real.continuous_mul_log.tendsto 0 |> Filter.Tendsto.mul_const ( Real.log 2 ) ⁻¹ ) )

/-
Theorem 3(i): The NML score decomposes as lambda_c * N(T) + (k_c/2) * log2 T + o(N(T)).
-/
/-- Theorem 3(i): NML score decomposition. -/
theorem NML_decomposition (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0) (theta_star : Fin p × S → ℝ)
  (h_conv : ConvergentFrequencies U p s hp theta_star) :
  let k := p * Fintype.card S
  let lambda := AsymptoticRate p s theta_star
  Filter.Tendsto (fun T => (NML U T p s hp - (lambda * (T * Fintype.card S : ℝ) + (k : ℝ) / 2 * Real.logb 2 T)) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds 0) := by
    convert Filter.Tendsto.sub ( NLL_convergence U p s hp theta_star h_conv ) ( ( show Filter.Tendsto ( fun T : ℕ ↦ ( AsymptoticRate p s theta_star * ( T * ( Fintype.card S ) ) : ℝ ) / ( T * ( Fintype.card S ) ) ) Filter.atTop ( nhds ( AsymptoticRate p s theta_star ) ) from ?_ ) ) using 2 <;> norm_num [ mul_div_assoc ];
    · unfold NML; ring;
      by_cases h : Fintype.card S = 0 <;> simp_all +decide [ mul_assoc, mul_comm, mul_left_comm ] ; ring;
    · by_cases h : Fintype.card S = 0 <;> simp_all +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ];
      exact tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with T hT; simp +decide [ hT ] )

/-
Theorem 3(ii): Every candidate c with lambda_c > lambda* is eventually excluded.
-/
/-- The minimum asymptotic rate among a list of candidates. -/
noncomputable def MinAsymptoticRate (Cs : List (Candidate S)) (theta_stars : (c : Candidate S) → Fin c.p × S → ℝ) : ℝ :=
  match (Cs.map (fun c => AsymptoticRate c.p c.s (theta_stars c))).minimum with
  | ⊤ => 0
  | (x : ℝ) => x

/-- Theorem 3(ii): Elimination of suboptimal candidates. -/
theorem Elimination_of_Suboptimal (U : Spacetime S) (Cs : List (Candidate S))
  (theta_stars : (c : Candidate S) → Fin c.p × S → ℝ)
  (h_conv : ∀ c ∈ Cs, ConvergentFrequencies U c.p c.s c.hp (theta_stars c))
  (c : Candidate S) (hc : c ∈ Cs)
  (h_subopt : AsymptoticRate c.p c.s (theta_stars c) > MinAsymptoticRate Cs theta_stars) :
  Filter.Eventually (fun T => ¬ IsNMLMinimizer U Cs T c) Filter.atTop := by
    obtain ⟨c_star, hc_star⟩ : ∃ c_star ∈ Cs, AsymptoticRate c_star.p c_star.s (theta_stars c_star) = MinAsymptoticRate Cs theta_stars := by
      unfold MinAsymptoticRate;
      rcases h : List.minimum ( List.map ( fun c => AsymptoticRate c.p c.s ( theta_stars c ) ) Cs ) with ( _ | x ) <;> simp_all +decide [ List.minimum ];
      · rw [ List.argmin_eq_none ] at h ; aesop;
      · rw [ List.argmin_eq_some_iff ] at h ; aesop;
    -- By definition of asymptotic rate, we know that the per-site NML score converges to the asymptotic rate.
    have h_per_site_NML_converge : ∀ c ∈ Cs, Filter.Tendsto (fun T => (NML U T c.p c.s c.hp) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds (AsymptoticRate c.p c.s (theta_stars c))) := by
      intro c hc
      have h_per_site_NML_converge : Filter.Tendsto (fun T => (NLL U T c.p c.s c.hp) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds (AsymptoticRate c.p c.s (theta_stars c))) := by
        exact NLL_convergence U c.p c.s c.hp ( theta_stars c ) ( h_conv c hc );
      have h_per_site_NML_converge : Filter.Tendsto (fun T => ((c.p * Fintype.card S : ℝ) / 2 * Real.logb 2 T) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds 0) := by
        convert Complexity_convergence c.p c.s c.hp using 1;
        norm_num;
      convert ‹Filter.Tendsto ( fun T : ℕ => NLL U T c.p c.s c.hp / ( T * Fintype.card S : ℝ ) ) Filter.atTop ( nhds ( AsymptoticRate c.p c.s ( theta_stars c ) ) ) ›.add ( h_per_site_NML_converge.comp tendsto_natCast_atTop_atTop ) using 2 <;> norm_num [ NML ] ; ring;
    -- Since the asymptotic rate of $c$ is greater than that of $c^*$, there exists some $T_0$ such that for all $T \geq T_0$, the per-site NML score of $c$ is greater than that of $c^*$.
    obtain ⟨T₀, hT₀⟩ : ∃ T₀ : ℕ, ∀ T ≥ T₀, (NML U T c.p c.s c.hp) / (T * Fintype.card S : ℝ) > (NML U T c_star.p c_star.s c_star.hp) / (T * Fintype.card S : ℝ) := by
      have := h_per_site_NML_converge c hc |> Filter.Tendsto.sub <| h_per_site_NML_converge c_star hc_star.1;
      exact Filter.eventually_atTop.mp ( this.eventually ( lt_mem_nhds ( sub_pos.mpr ( by linarith ) ) ) ) |> fun ⟨ T₀, hT₀ ⟩ ↦ ⟨ T₀, fun T hT ↦ by linarith [ hT₀ T hT ] ⟩;
    refine' Filter.eventually_atTop.mpr ⟨ T₀ + 1, fun T hT => _ ⟩ ; intro h ; have := hT₀ T ( by linarith ) ; simp_all +decide [ IsNMLMinimizer ] ; (
    contrapose! this; gcongr ; aesop;);

/-
Definition of UniqueRateMinimizer.
-/
/-- Predicate: c_star is the unique rate minimizer among candidates Cs. -/
def UniqueRateMinimizer (Cs : List (Candidate S)) (theta_stars : (c : Candidate S) → Fin c.p × S → ℝ) (c_star : Candidate S) : Prop :=
  c_star ∈ Cs ∧
  AsymptoticRate c_star.p c_star.s (theta_stars c_star) = MinAsymptoticRate Cs theta_stars ∧
  ∀ c ∈ Cs, c ≠ c_star → AsymptoticRate c.p c.s (theta_stars c) > MinAsymptoticRate Cs theta_stars

/-
Theorem 3(iii): If c* is the unique rate-minimizer, then for large T, c* is the unique NML minimizer.
-/
/-- Theorem 3(iii): Stabilization under unique rate-minimizer. -/
theorem Stabilization_Unique_Minimizer (U : Spacetime S) (Cs : List (Candidate S))
  (theta_stars : (c : Candidate S) → Fin c.p × S → ℝ)
  (h_conv : ∀ c ∈ Cs, ConvergentFrequencies U c.p c.s c.hp (theta_stars c))
  (c_star : Candidate S)
  (h_unique : UniqueRateMinimizer Cs theta_stars c_star) :
  Filter.Eventually (fun T => IsNMLMinimizer U Cs T c_star ∧ ∀ c ∈ Cs, IsNMLMinimizer U Cs T c → c = c_star) Filter.atTop := by
    have h_unique : ∀ᶠ T in Filter.atTop, ∀ c ∈ Cs, c ≠ c_star → ¬IsNMLMinimizer U Cs T c := by
      have h_elim : ∀ c ∈ Cs, c ≠ c_star → Filter.Eventually (fun T => ¬IsNMLMinimizer U Cs T c) Filter.atTop := by
        intro c hc hc_ne;
        apply Elimination_of_Suboptimal U Cs theta_stars h_conv c hc (by
        exact h_unique.2.2 c hc hc_ne);
      simp +zetaDelta at *;
      choose! a ha using h_elim; use Finset.sup (Cs.toFinset.filter (fun c => c ≠ c_star)) a; aesop;
    have h_unique : ∀ᶠ T in Filter.atTop, ∃ c ∈ Cs, IsNMLMinimizer U Cs T c := by
      simp_all +decide [ IsNMLMinimizer ];
      exact ⟨ 0, fun T hT => by simpa using Finset.exists_min_image ( List.toFinset Cs ) ( fun c => NML U T c.p c.s c.hp ) ⟨ c_star, List.mem_toFinset.mpr ( ‹UniqueRateMinimizer Cs theta_stars c_star›.1 ) ⟩ ⟩;
    filter_upwards [ h_unique, ‹∀ᶠ T in Filter.atTop, ∀ c ∈ Cs, c ≠ c_star → ¬IsNMLMinimizer U Cs T c› ] with T hT₁ hT₂;
    grind

/-
Definition of MixedSpacetime. It switches between B and B' based on the block index (t / p0) mod q.
-/
/-- A spacetime constructed by mixing two fields B and B' with period p0 and block size q. -/
def MixedSpacetime (B B' : Spacetime S) (p0 : ℕ) (q : ℕ) : Spacetime S :=
  fun t x =>
    if (t / p0) % q == 0 then B' t x else B t x

/-
MixedSpacetime is relative-periodic with period q*p0 and shift q*s.
-/
theorem MixedSpacetime_is_RelativePeriodic (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hq : q > 0) (hp0 : p0 > 0)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s) :
  IsRelativePeriodic (MixedSpacetime B B' p0 q) (q * p0) (q • s) := by
    intro t x; simp +decide [ MixedSpacetime ] ; ring;
    split_ifs <;> simp_all +decide [ Nat.add_mul_div_right _ _ hp0 ];
    · have := hB' t x; simp_all +decide [ IsRelativePeriodic ] ;
      refine' Nat.recOn q _ _ <;> simp_all +decide [ Nat.succ_mul, ← add_assoc ];
      simp_all +decide [ add_smul, ← add_assoc ];
    · -- Apply the relative-periodicity of B with period p0 and shift s.
      have hB_periodic : ∀ k : ℕ, B (t + k * p0) (x + k • s) = B t x := by
        intro k; induction' k with k ih <;> simp_all +decide [ Nat.succ_mul, ← add_assoc ] ;
        have := hB ( t + k * p0 ) ( x + k • s ) ; simp_all +decide [ add_smul, ← add_assoc ] ;
      exact hB_periodic q

/-
If U is exactly relative-periodic, its asymptotic rate is 0.
-/
/-- Lemma: If U is exactly relative-periodic with (p, s), then its asymptotic rate is 0. -/
theorem Exact_Periodicity_Implies_Zero_Rate (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0)
  (h_rel : IsRelativePeriodic U p s) :
  ∃ theta_star : Fin p × S → ℝ,
    ConvergentFrequencies U p s hp theta_star ∧ AsymptoticRate p s theta_star = 0 := by
      -- Since U is relative-periodic, each orbit class has a number of 1s that is a constant. Therefore, the empirical frequency of 1s in each orbit class is a constant.
      have h_const_freq : ∀ i : Fin p × S, ∃ theta_i : ℝ, Filter.Tendsto (fun T => (OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i))) Filter.atTop (nhds theta_i) ∧ Real.binEntropy theta_i = 0 := by
        -- Since U is relative-periodic, each orbit class has a number of 1s that is a constant. Therefore, the empirical frequency of 1s in each orbit class is a constant. Use this fact.
        intros i
        obtain ⟨theta_i, htheta_i⟩ : ∃ theta_i : Bool, ∀ T : ℕ, (OrbitCount1_idx U T p s hp i : ℝ) = (if theta_i then (OrbitSize T (OrbitClass p s hp i) : ℝ) else 0) := by
          -- Since U is relative-periodic, each orbit class has a number of 1s that is a constant. Therefore, the empirical frequency of 1s in each orbit class is a constant. Use this fact to find theta_i.
          have h_const_freq : ∀ t x, (t, x) ∈ OrbitClass p s hp i → U t x = U (i.1.val) (i.2) := by
            intro t x hx
            obtain ⟨k, hk⟩ : ∃ k : ℤ, t = i.1.val + k * p ∧ x = i.2 + k • s := by
              unfold OrbitClass at hx
              generalize_proofs at *; (
              unfold OrbitMap at hx
              generalize_proofs at *; (
              use t / p
              generalize_proofs at *; (
              rw [ ← hx ] ; norm_num [ Nat.mod_add_div ] ; ring;
              exact ⟨ by linarith [ Int.emod_add_mul_ediv t p ], by norm_cast; simp +decide ⟩)))
            generalize_proofs at *; (
            have h_ind : ∀ k : ℕ, U (i.1.val + k * p) (i.2 + k • s) = U i.1.val i.2 := by
              intro k; induction' k with k ih <;> simp_all +decide [ Nat.succ_mul, ← add_assoc ] ;
              have := h_rel ( i.1 + k * p ) ( i.2 + k • s ) ; simp_all +decide [ add_smul, ← add_assoc ] ;
            generalize_proofs at *; (
            rcases k with ( _ | k ) <;> simp_all +decide [ add_mul, ← add_assoc ];
            · norm_cast at hk ; aesop;
            · nlinarith [ Int.negSucc_lt_zero k, Fin.is_lt i.1 ]));
          use U (i.1.val) i.2;
          intro T; split_ifs <;> simp_all +decide [ OrbitCount1_idx, OrbitSize ] ;
          · simp +decide [ Count1, Finset.sum_ite ];
            exact Finset.sum_congr rfl fun x hx => congr_arg _ ( congr_arg _ ( Finset.filter_congr fun y hy => by aesop ) );
          · exact Finset.sum_eq_zero fun t ht => Finset.sum_eq_zero fun x hx => by aesop;
        by_cases h : ∃ T : ℕ, (OrbitSize T (OrbitClass p s hp i) : ℝ) ≠ 0 <;> simp_all +decide [ Real.binEntropy ];
        by_cases htheta_i : theta_i <;> simp_all +decide [ div_eq_mul_inv ];
        refine' ⟨ 1, _, _ ⟩ <;> norm_num;
        refine' tendsto_const_nhds.congr' _;
        filter_upwards [ Filter.eventually_gt_atTop h.choose ] with T hT using by rw [ mul_inv_cancel₀ ( Nat.cast_ne_zero.mpr <| ne_of_gt <| Nat.pos_of_ne_zero <| by exact fun h' => h.choose_spec <| by linarith [ show OrbitSize T ( OrbitClass p s hp i ) ≥ OrbitSize h.choose ( OrbitClass p s hp i ) from by exact Finset.sum_le_sum_of_subset ( Finset.range_mono hT.le ) |> le_trans ( Finset.sum_le_sum fun _ _ => Finset.sum_le_sum fun _ _ => by aesop ) ] ) ] ;
      choose theta_star htheta_star htheta_star' using h_const_freq;
      exact ⟨ theta_star, htheta_star, by unfold AsymptoticRate; simp +decide [ htheta_star' ] ⟩

/-
The fraction of t in [0, T) with t % p0 = r such that (t / p0) % q = 0 converges to 1/q as T -> infinity.
-/
/-- Lemma: Asymptotic density of the condition (t / p0) % q == 0 within a residue class modulo p0. -/
theorem Density_Mod_Div_Mod (p0 q r : ℕ) (hp0 : p0 > 0) (hq : q > 0) (hr : r < p0) :
  Filter.Tendsto (fun T => ((Finset.filter (fun t => t % p0 = r ∧ (t / p0) % q = 0) (Finset.range T)).card : ℝ) /
                           ((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card : ℝ))
                 Filter.atTop (nhds (1 / (q : ℝ))) := by
                   -- Let's simplify the expression by factoring out common terms and using the fact that $p0$ and $q$ are constants.
                   suffices h_suff : Filter.Tendsto (fun T => ((Finset.filter (fun t => t % p0 = r ∧ t / p0 % q = 0) (Finset.range T)).card : ℝ) / T) Filter.atTop (nhds (1 / (p0 * q))) by
                     -- The set {t ∈ Finset.range T | t % p0 = r} has cardinality approximately T / p0.
                     have h_card : Filter.Tendsto (fun T => ((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card : ℝ) / T) Filter.atTop (nhds (1 / p0)) := by
                       -- The number of times $t \equiv r \pmod{p0}$ in the range $[0, T)$ is approximately $T / p0$.
                       have h_card_approx : ∀ T : ℕ, ((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card : ℝ) ≤ T / p0 + 1 ∧ ((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card : ℝ) ≥ T / p0 - 1 := by
                         intro T;
                         -- The set {t ∈ Finset.range T | t % p0 = r} is in bijection with the set {k ∈ Finset.range (T / p0 + 1) | k * p0 + r < T}.
                         have h_bij : Finset.filter (fun t => t % p0 = r) (Finset.range T) = Finset.image (fun k => k * p0 + r) (Finset.filter (fun k => k * p0 + r < T) (Finset.range (T / p0 + 1))) := by
                           ext t;
                           simp +zetaDelta at *;
                           exact ⟨ fun h => ⟨ t / p0, ⟨ Nat.lt_succ_of_le ( Nat.div_le_div_right h.1.le ), by linarith [ Nat.mod_add_div t p0 ] ⟩, by linarith [ Nat.mod_add_div t p0 ] ⟩, by rintro ⟨ a, ⟨ ha₁, ha₂ ⟩, rfl ⟩ ; exact ⟨ by nlinarith [ Nat.div_mul_le_self T p0 ], by norm_num [ Nat.add_mod, Nat.mod_eq_of_lt hr ] ⟩ ⟩;
                         rw [ h_bij, Finset.card_image_of_injective ] <;> norm_num [ Function.Injective, hp0.ne' ];
                         rw [ div_add_one, le_div_iff₀, div_le_iff₀ ] <;> norm_cast;
                         · constructor;
                           · exact le_trans ( mul_le_mul_of_nonneg_right ( Finset.card_filter_le _ _ ) hp0.le ) ( by norm_num; nlinarith [ Nat.div_mul_le_self T p0 ] );
                           · have h_card_filter : Finset.card (Finset.filter (fun k => k * p0 + r < T) (Finset.range (T / p0 + 1))) ≥ T / p0 := by
                               refine' le_trans _ ( Finset.card_mono <| show Finset.range ( T / p0 ) ⊆ Finset.filter ( fun k => k * p0 + r < T ) ( Finset.range ( T / p0 + 1 ) ) from fun x hx => Finset.mem_filter.mpr ⟨ Finset.mem_range.mpr <| by linarith [ Finset.mem_range.mp hx ], by nlinarith [ Finset.mem_range.mp hx, Nat.div_mul_le_self T p0 ] ⟩ ) ; norm_num;
                             nlinarith [ Nat.div_add_mod T p0, Nat.mod_lt T hp0 ];
                         · linarith;
                       -- Using the approximation, we can bound the ratio.
                       have h_bound : ∀ T : ℕ, T > 0 → abs (((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card : ℝ) / T - 1 / p0) ≤ 2 / T := by
                         intro T hT; rw [ abs_le ] ; constructor <;> ring_nf at * <;> nlinarith [ inv_pos.mpr ( by positivity : 0 < ( T : ℝ ) ), mul_inv_cancel₀ ( by positivity : ( T : ℝ ) ≠ 0 ), h_card_approx T ] ;
                       exact tendsto_iff_norm_sub_tendsto_zero.mpr <| squeeze_zero_norm' ( Filter.eventually_atTop.mpr ⟨ 1, fun T hT => by simpa using h_bound T <| pos_of_gt hT ⟩ ) <| tendsto_const_nhds.div_atTop <| tendsto_natCast_atTop_atTop;
                     convert h_suff.div h_card _ using 1 <;> norm_num [ hp0.ne', hq.ne' ];
                     ext T; by_cases hT : T = 0 <;> simp +decide [ hT, div_div_eq_mul_div ] ;
                   -- We'll use the fact that the number of elements in the set $\{ t \in [0, T) \mid t \equiv r \pmod{p0} \text{ and } t / p0 \equiv 0 \pmod{q} \}$ is approximately $T / (p0 * q)$.
                   have h_card_approx : ∀ T : ℕ, (Finset.card (Finset.filter (fun t => t % p0 = r ∧ t / p0 % q = 0) (Finset.range T)) : ℝ) ≤ (T : ℝ) / (p0 * q) + 1 := by
                     intro T
                     have h_card_approx : (Finset.card (Finset.filter (fun t => t % p0 = r ∧ t / p0 % q = 0) (Finset.range T)) : ℝ) ≤ (T / (p0 * q) : ℝ) + 1 := by
                       have : Finset.filter (fun t => t % p0 = r ∧ t / p0 % q = 0) (Finset.range T) ⊆ Finset.image (fun k => p0 * (q * k) + r) (Finset.range (T / (p0 * q) + 1)) := by
                         intro t ht; simp_all +decide [ Nat.div_mul_le_self ] ;
                         obtain ⟨ k, hk ⟩ := Nat.modEq_zero_iff_dvd.mp ht.2.2;
                         exact ⟨ k, Nat.lt_succ_of_le ( Nat.le_div_iff_mul_le ( by positivity ) |>.2 <| by nlinarith [ Nat.mod_add_div t p0 ] ), by nlinarith [ Nat.mod_add_div t p0 ] ⟩
                       refine' le_trans ( Nat.cast_le.mpr <| Finset.card_le_card this ) _;
                       rw [ Finset.card_image_of_injective ] <;> norm_num [ Function.Injective, hp0.ne', hq.ne' ];
                       rw [ le_div_iff₀ ] <;> norm_cast <;> nlinarith [ Nat.div_mul_le_self T ( p0 * q ) ];
                     convert h_card_approx using 1;
                   -- Similarly, we'll use the fact that the number of elements in the set $\{ t \in [0, T) \mid t \equiv r \pmod{p0} \text{ and } t / p0 \equiv 0 \pmod{q} \}$ is at least $T / (p0 * q) - 1$.
                   have h_card_approx_lower : ∀ T : ℕ, (Finset.card (Finset.filter (fun t => t % p0 = r ∧ t / p0 % q = 0) (Finset.range T)) : ℝ) ≥ (T : ℝ) / (p0 * q) - 1 := by
                     intro T
                     have h_card_lower : (Finset.card (Finset.filter (fun t => t % p0 = r ∧ t / p0 % q = 0) (Finset.range T)) : ℝ) ≥ (Finset.card (Finset.image (fun k => p0 * (q * k) + r) (Finset.range (T / (p0 * q)))) : ℝ) := by
                       refine' Nat.cast_le.mpr ( Finset.card_le_card _ );
                       norm_num [ Finset.image_subset_iff ];
                       intro x hx; refine' ⟨ _, _, _ ⟩ <;> try rw [ Nat.mod_eq_of_lt hr ];
                       · rw [ Nat.lt_iff_add_one_le, Nat.le_div_iff_mul_le ] at hx <;> nlinarith [ mul_pos hp0 hq ];
                       · norm_num [ Nat.add_div, Nat.mul_div_assoc, hp0, hq ];
                         rw [ Nat.div_eq_of_lt hr, if_neg ( by linarith [ Nat.mod_lt r hp0 ] ) ] ; norm_num [ Nat.add_mod, Nat.mul_mod ];
                     refine le_trans ?_ h_card_lower ; norm_num [ Finset.card_image_of_injective, Function.Injective, hp0.ne', hq.ne' ];
                     rw [ div_le_iff₀ ] <;> norm_cast <;> nlinarith [ Nat.div_add_mod T ( p0 * q ), Nat.mod_lt T ( mul_pos hp0 hq ) ];
                   -- Using the bounds, we can show that the limit of the ratio is $1 / (p0 * q)$ by the squeeze theorem.
                   have h_squeeze : Filter.Tendsto (fun T : ℕ => ((T : ℝ) / (p0 * q) - 1) / T) Filter.atTop (nhds (1 / (p0 * q))) ∧ Filter.Tendsto (fun T : ℕ => ((T : ℝ) / (p0 * q) + 1) / T) Filter.atTop (nhds (1 / (p0 * q))) := by
                     ring_nf;
                     exact ⟨ by simpa using Filter.Tendsto.sub ( tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with T hT; simp +decide [ mul_assoc, mul_comm, mul_left_comm, hT ] ) ) ( tendsto_inverse_atTop_nhds_zero_nat ), by simpa using Filter.Tendsto.add ( tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with T hT; simp +decide [ mul_assoc, mul_comm, mul_left_comm, hT ] ) ) ( tendsto_inverse_atTop_nhds_zero_nat ) ⟩;
                   exact tendsto_of_tendsto_of_tendsto_of_le_of_le h_squeeze.1 h_squeeze.2 ( fun T => div_le_div_of_nonneg_right ( h_card_approx_lower T ) ( Nat.cast_nonneg _ ) ) ( fun T => div_le_div_of_nonneg_right ( h_card_approx T ) ( Nat.cast_nonneg _ ) )

/-
Definition of theta_mixed.
-/
/-- The expected limiting frequencies for MixedSpacetime. -/
noncomputable def theta_mixed (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (i : Fin p0 × S) : ℝ :=
  if B i.1 i.2 = B' i.1 i.2 then
    (if B i.1 i.2 then 1 else 0)
  else
    (if B' i.1 i.2 then 1 / (q : ℝ) else 1 - 1 / (q : ℝ))

/-
On an orbit class i, MixedSpacetime reduces to B' or B depending on the block index.
-/
/-- Lemma: Value of MixedSpacetime on an orbit class. -/
theorem MixedSpacetime_Value_on_Orbit (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s)
  (i : Fin p0 × S) (t : ℕ) (ht : t % p0 = i.1) :
  MixedSpacetime B B' p0 q t (i.2 + (t / p0) • s) =
    if (t / p0) % q == 0 then B' i.1 i.2 else B i.1 i.2 := by
      have h_orbit_periodic : ∀ a : ℕ, B (i.1.val + a * p0) (i.2 + a • s) = B i.1.val i.2 ∧ B' (i.1.val + a * p0) (i.2 + a • s) = B' i.1.val i.2 := by
        intro a
        induction' a with a ih;
        · simp +decide;
        · have := hB ( i.1 + a * p0 ) ( i.2 + a • s ) ; have := hB' ( i.1 + a * p0 ) ( i.2 + a • s ) ; simp_all +decide [ add_mul, ← add_assoc ] ;
          simp_all +decide [ add_smul, add_assoc ];
      unfold MixedSpacetime; simp +decide [ ← ht, h_orbit_periodic ] ;
      rw [ ← Nat.mod_add_div t p0, ht ] ; simp +decide [ h_orbit_periodic ] ;
      simp +decide [ Nat.add_mul_div_left _ _ hp0 ];
      simp +decide [ Nat.mod_eq_of_lt i.1.2, mul_comm p0 ];
      simp +decide [ Nat.div_eq_of_lt i.1.2, h_orbit_periodic ]

#check theta_mixed

/-
The orbit count decomposes into counts of time steps where B' is active and B is active.
-/
/-- Lemma: Decomposition of OrbitCount1 for MixedSpacetime. -/
theorem MixedSpacetime_OrbitCount_Decomposition (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s)
  (i : Fin p0 × S) (T : ℕ) :
  OrbitCount1_idx (MixedSpacetime B B' p0 q) T p0 s hp0 i =
    (if B' i.1 i.2 then (Finset.filter (fun t => t % p0 = i.1.val ∧ (t / p0) % q = 0) (Finset.range T)).card else 0) +
    (if B i.1 i.2 then (Finset.filter (fun t => t % p0 = i.1.val ∧ (t / p0) % q ≠ 0) (Finset.range T)).card else 0) := by
      unfold OrbitCount1_idx;
      unfold Count1 OrbitClass;
      -- By definition of `OrbitMap`, we know that `(t, x) ∈ {pt : ℕ × S | OrbitMap p0 s hp0 pt = i}` if and only if `t % p0 = i.1` and `x = i.2 + (t / p0) • s`.
      have h_orbit_map : ∀ t x, (t, x) ∈ {pt : ℕ × S | OrbitMap p0 s hp0 pt = i} ↔ t % p0 = i.1 ∧ x = i.2 + (t / p0) • s := by
        unfold OrbitMap; aesop;
      -- Apply the definition of `MixedSpacetime` to split the sum into two parts.
      have h_split : ∀ t x, (t, x) ∈ {pt : ℕ × S | OrbitMap p0 s hp0 pt = i} → (MixedSpacetime B B' p0 q t x = if (t / p0) % q == 0 then B' i.1 i.2 else B i.1 i.2) := by
        intro t x htx
        rw [h_orbit_map] at htx
        rcases htx with ⟨ht, hx⟩
        rw [hx];
        exact?;
      split_ifs <;> simp_all +decide [ Finset.sum_ite ];
      · rw [ Finset.card_filter, Finset.card_filter ];
        rw [ ← Finset.sum_add_distrib ] ; refine' Finset.sum_congr rfl fun t ht => _ ; by_cases h : t % p0 = i.1 <;> simp_all +decide [ Finset.filter_eq', Finset.filter_and ] ;
        split_ifs <;> simp_all +decide [ Nat.mod_eq_of_lt ];
      · rw [ Finset.card_filter ];
        refine' Finset.sum_congr rfl fun t ht => _;
        split_ifs <;> simp_all +decide [ Finset.card_eq_one ];
        use i.2 + (t / p0) • s; ext; aesop;
      · rw [ Finset.card_filter ];
        refine' Finset.sum_congr rfl fun t ht => _;
        split_ifs <;> simp_all +decide [ Finset.card_eq_one ];
        use i.2 + (t / p0) • s; ext; aesop;

/-
The fraction of t in [0, T) with t % p0 = r such that (t / p0) % q != 0 converges to 1 - 1/q.
-/
/-- Lemma: Asymptotic density of the condition (t / p0) % q != 0 within a residue class modulo p0. -/
theorem Density_Mod_Div_Mod_Compl (p0 q r : ℕ) (hp0 : p0 > 0) (hq : q > 0) (hr : r < p0) :
  Filter.Tendsto (fun T => ((Finset.filter (fun t => t % p0 = r ∧ (t / p0) % q ≠ 0) (Finset.range T)).card : ℝ) /
                           ((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card : ℝ))
                 Filter.atTop (nhds (1 - 1 / (q : ℝ))) := by
                   -- The number of t's in [0, T) where (t / p0) % q = 0 is approximately T / (p0 * q), and those where it's not are approximately T / p0 - T / (p0 * q).
                   have h_approx : Filter.Tendsto (fun T => ((Finset.filter (fun t => t % p0 = r ∧ (t / p0) % q = 0) (Finset.range T)).card : ℝ) / ((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card : ℝ)) Filter.atTop (nhds ((1 : ℝ) / q)) := by
                     convert Density_Mod_Div_Mod p0 q r hp0 hq hr using 1;
                   have h_approx : Filter.Tendsto (fun T => ((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card - (Finset.filter (fun t => t % p0 = r ∧ (t / p0) % q = 0) (Finset.range T)).card : ℝ) / ((Finset.filter (fun t => t % p0 = r) (Finset.range T)).card : ℝ)) Filter.atTop (nhds ((1 : ℝ) - 1 / q)) := by
                     convert h_approx.const_sub 1 |> Filter.Tendsto.congr' _ using 1;
                     filter_upwards [ Filter.eventually_gt_atTop p0 ] with T hT using by rw [ sub_div, div_self <| Nat.cast_ne_zero.mpr <| ne_of_gt <| Finset.card_pos.mpr ⟨ r, Finset.mem_filter.mpr ⟨ Finset.mem_range.mpr <| by linarith, by simp +decide [ Nat.mod_eq_of_lt hr ] ⟩ ⟩ ] ;
                   convert h_approx using 3;
                   rw [ eq_sub_iff_add_eq', ← Nat.cast_add ] ; rw [ ← Finset.card_union_of_disjoint ] ; congr ; ext ; by_cases h : ( ‹_› : ℕ ) / p0 % q = 0 <;> aesop;
                   exact Finset.disjoint_filter.mpr ( by aesop )

/-
OrbitSize is the count of time steps t < T such that t % p0 = i.1.
-/
/-- Lemma: OrbitSize equals the cardinality of the time indices in the residue class. -/
theorem OrbitSize_eq_Card (p0 : ℕ) (s : S) (hp0 : p0 > 0) (i : Fin p0 × S) (T : ℕ) :
  OrbitSize T (OrbitClass p0 s hp0 i) = (Finset.filter (fun t => t % p0 = i.1.val) (Finset.range T)).card := by
    -- The set {t ∈ Finset.range T | t % p0 = i.1.val} is exactly the set of t's that contribute to the orbit class at level i.1.val. Therefore, the sum is equal to the cardinality of this set.
    have h_set_eq : {t ∈ Finset.range T | t % p0 = i.1.val} = Finset.filter (fun t => ∃ x : S, (t, x) ∈ OrbitClass p0 s hp0 i) (Finset.range T) := by
      ext t
      simp [OrbitClass, OrbitMap];
      intro ht
      constructor
      intro h
      use i.2 + (t / p0) • s
      simp [h];
      grind +ring;
    rw [ h_set_eq, Finset.card_filter ];
    refine' Finset.sum_congr rfl fun t ht => _;
    split_ifs <;> simp_all +decide [ Finset.sum_subset ];
    obtain ⟨ x, hx ⟩ := ‹_›; rw [ Finset.card_eq_one ] ; use x; ext y; simp_all +decide [ OrbitClass ] ;
    unfold OrbitMap at *; aesop;

/-
The ratio of counts converges to theta_mixed for a single orbit class.
Proof sketch:
1. Use `MixedSpacetime_OrbitCount_Decomposition` to split the numerator into two parts: one for B' (where (t/p0)%q == 0) and one for B (where (t/p0)%q != 0).
2. Use `OrbitSize_eq_Card` to express the denominator as the cardinality of {t < T | t % p0 = i.1}.
3. Case 1: B = B'. Then theta_mixed is 0 or 1. The decomposition simplifies to the total count (if B=true) or 0 (if B=false). The ratio converges to 1 or 0.
4. Case 2: B != B'.
   a. If B' is true (so B is false), the numerator is the count of {t | t%p0=i.1 and (t/p0)%q == 0}. Use `Density_Mod_Div_Mod` to show the ratio converges to 1/q.
   b. If B' is false (so B is true), the numerator is the count of {t | t%p0=i.1 and (t/p0)%q != 0}. Use `Density_Mod_Div_Mod_Compl` to show the ratio converges to 1 - 1/q.
5. Combine these to show convergence to `theta_mixed`.
-/
/-- Lemma: Convergence of the ratio for a single orbit class in MixedSpacetime. -/
theorem MixedSpacetime_Ratio_Convergence (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0) (hq : q > 0)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s)
  (i : Fin p0 × S) :
  Filter.Tendsto (fun T => (OrbitCount1_idx (MixedSpacetime B B' p0 q) T p0 s hp0 i : ℝ) / (OrbitSize T (OrbitClass p0 s hp0 i)))
    Filter.atTop (nhds (theta_mixed B B' p0 s q i)) := by
      unfold theta_mixed;
      split_ifs <;> simp_all +decide [ MixedSpacetime_OrbitCount_Decomposition, OrbitSize_eq_Card ];
      · refine' tendsto_const_nhds.congr' _;
        filter_upwards [ Filter.eventually_gt_atTop ( i.1 : ℕ ) ] with T hT;
        rw [ eq_div_iff ] <;> norm_cast;
        · rw [ one_mul, ← Finset.card_union_of_disjoint ];
          · exact congr_arg Finset.card ( by ext; by_cases h : ( ‹_› : ℕ ) / p0 % q = 0 <;> aesop );
          · exact Finset.disjoint_filter.mpr ( by aesop );
        · exact ne_of_gt ( Finset.card_pos.mpr ⟨ i.1, Finset.mem_filter.mpr ⟨ Finset.mem_range.mpr hT, Nat.mod_eq_of_lt i.1.2 ⟩ ⟩ );
      · convert Density_Mod_Div_Mod p0 q i.1.val hp0 hq ( Fin.is_lt i.1 ) using 1 ; norm_num [ Nat.mod_eq_of_lt ];
      · convert Density_Mod_Div_Mod_Compl p0 q i.1.val hp0 hq ( Fin.is_lt i.1 ) using 2 ; norm_num

/-
The ratio of counts converges to theta_mixed for a single orbit class. (Version 2)
-/
/-- Lemma: Convergence of the ratio for a single orbit class in MixedSpacetime. -/
theorem MixedSpacetime_Ratio_Convergence_v2 (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0) (hq : q > 0)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s)
  (i : Fin p0 × S) :
  Filter.Tendsto (fun T => (OrbitCount1_idx (MixedSpacetime B B' p0 q) T p0 s hp0 i : ℝ) / (OrbitSize T (OrbitClass p0 s hp0 i)))
    Filter.atTop (nhds (theta_mixed B B' p0 s q i)) := by
      convert MixedSpacetime_Ratio_Convergence B B' p0 s q hp0 hq hB hB' i using 1

/-
The ratio of counts converges to theta_mixed for a single orbit class. (Version 3)
-/
/-- Lemma: Convergence of the ratio for a single orbit class in MixedSpacetime. -/
theorem MixedSpacetime_Ratio_Convergence_v3 (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0) (hq : q > 0)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s)
  (i : Fin p0 × S) :
  Filter.Tendsto (fun T => (OrbitCount1_idx (MixedSpacetime B B' p0 q) T p0 s hp0 i : ℝ) / (OrbitSize T (OrbitClass p0 s hp0 i)))
    Filter.atTop (nhds (theta_mixed B B' p0 s q i)) := by
      convert MixedSpacetime_Ratio_Convergence B B' p0 s q hp0 hq hB hB' i using 1

/-
The ratio of counts converges to theta_mixed for a single orbit class. (Final Version)
-/
/-- Lemma: Convergence of the ratio for a single orbit class in MixedSpacetime. -/
theorem MixedSpacetime_Ratio_Convergence_Final (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0) (hq : q > 0)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s)
  (i : Fin p0 × S) :
  Filter.Tendsto (fun T => (OrbitCount1_idx (MixedSpacetime B B' p0 q) T p0 s hp0 i : ℝ) / (OrbitSize T (OrbitClass p0 s hp0 i)))
    Filter.atTop (nhds (theta_mixed B B' p0 s q i)) := by
      convert MixedSpacetime_Ratio_Convergence_v3 B B' p0 s q hp0 hq hB hB' i using 1

/-
MixedSpacetime satisfies the convergent frequencies assumption with limit theta_mixed.
-/
/-- Lemma: MixedSpacetime satisfies ConvergentFrequencies. -/
theorem MixedSpacetime_ConvergentFrequencies (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0) (hq : q > 0)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s) :
  ConvergentFrequencies (MixedSpacetime B B' p0 q) p0 s hp0 (theta_mixed B B' p0 s q) := by
    intro i
    exact MixedSpacetime_Ratio_Convergence_Final B B' p0 s q hp0 hq hB hB' i

/-
If B != B', the asymptotic rate of MixedSpacetime under (p0, s) is positive.
-/
/-- Lemma: Positive rate for MixedSpacetime under base period. -/
theorem MixedSpacetime_Positive_Rate (B B' : Spacetime S) (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0) (hq : q > 1)
  (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s)
  (h_diff : ∃ i : Fin p0 × S, B i.1 i.2 ≠ B' i.1 i.2) :
  AsymptoticRate p0 s (theta_mixed B B' p0 s q) > 0 := by
    -- Since $B \neq B'$, there exists some orbit class $i$ such that $B i.1 i.2 \neq B' i.1 i.2$.
    obtain ⟨i, hi⟩ : ∃ i : Fin p0 × S, B i.1 i.2 ≠ B' i.1 i.2 := h_diff;
    refine' mul_pos ( one_div_pos.mpr ( mul_pos ( Nat.cast_pos.mpr hp0 ) ( Nat.cast_pos.mpr ( Fintype.card_pos_iff.mpr ⟨ i.2 ⟩ ) ) ) ) ( lt_of_lt_of_le _ ( Finset.single_le_sum ( fun i _ => _ ) ( Finset.mem_univ i ) ) ) <;> norm_num [ hi, theta_mixed ];
    · split_ifs <;> simp_all +decide [ Real.binEntropy ];
      · exact lt_of_le_of_lt ( mul_nonpos_of_nonneg_of_nonpos ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| mod_cast hq.le ) <| Real.log_nonpos ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| mod_cast hq.le ) <| sub_le_self _ <| inv_nonneg.2 <| Nat.cast_nonneg _ ) <| mul_pos ( inv_pos.2 <| Nat.cast_pos.2 hq.le ) <| Real.log_pos <| mod_cast hq;
      · exact lt_of_le_of_lt ( mul_nonpos_of_nonneg_of_nonpos ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| mod_cast hq.le ) <| Real.log_nonpos ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| mod_cast hq.le ) <| sub_le_self _ <| inv_nonneg.2 <| Nat.cast_nonneg _ ) <| mul_pos ( inv_pos.2 <| Nat.cast_pos.2 hq.le ) <| Real.log_pos <| mod_cast hq;
    · split_ifs <;> norm_num [ Real.binEntropy ];
      · exact le_trans ( mul_nonpos_of_nonneg_of_nonpos ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| mod_cast hq.le ) <| Real.log_nonpos ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| mod_cast hq.le ) <| sub_le_self _ <| by positivity ) <| mul_nonneg ( inv_nonneg.2 <| Nat.cast_nonneg _ ) <| Real.log_nonneg <| mod_cast hq.le;
      · exact le_trans ( mul_nonpos_of_nonneg_of_nonpos ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| mod_cast hq.le ) <| Real.log_nonpos ( sub_nonneg.2 <| inv_le_one_of_one_le₀ <| mod_cast hq.le ) <| sub_le_self _ <| inv_nonneg.2 <| Nat.cast_nonneg _ ) <| mul_nonneg ( inv_nonneg.2 <| Nat.cast_nonneg _ ) <| Real.log_nonneg <| mod_cast hq.le

/-
Theorem 4: For MixedSpacetime U, the base period model c1 is eventually not selected against the higher period model c2.
-/
/-- Theorem 4: Nonidentifiability of Background Period. -/
theorem Nonidentifiability (p0 : ℕ) (s : S) (q : ℕ) (hp0 : p0 > 0) (hq : q > 1)
  (B B' : Spacetime S) (hB : IsRelativePeriodic B p0 s) (hB' : IsRelativePeriodic B' p0 s)
  (h_diff : ∃ i : Fin p0 × S, B i.1 i.2 ≠ B' i.1 i.2) :
  let U := MixedSpacetime B B' p0 q
  let c1 : Candidate S := ⟨p0, s, hp0⟩
  let c2 : Candidate S := ⟨q * p0, q • s, mul_pos (zero_lt_one.trans hq) hp0⟩
  let Cs := [c1, c2]
  Filter.Eventually (fun T => ¬ IsNMLMinimizer U Cs T c1) Filter.atTop := by
    intro U c1 c2 Cs
    generalize_proofs at *; (
    -- By Lemma~\ref{lem: mixed_spacetime_positive_rate}, the asymptotic rate of c1 is positive.
    have h_rate_c1_pos : AsymptoticRate p0 s (theta_mixed B B' p0 s q) > 0 := by
      exact?
    generalize_proofs at *; (
    -- By Lemma~\ref{lem: exact_periodicity_implies_zero_rate}, the asymptotic rate of c2 is zero.
    have h_rate_c2_zero : ∃ theta_star : Fin (q * p0) × S → ℝ,
      ConvergentFrequencies U (q * p0) (q • s) (by
      exact?) theta_star ∧
      AsymptoticRate (q * p0) (q • s) theta_star = 0 := by
        apply_rules [ Exact_Periodicity_Implies_Zero_Rate ];
        exact MixedSpacetime_is_RelativePeriodic B B' p0 s q ( by linarith ) ( by linarith ) hB hB'
    generalize_proofs at *; (
    obtain ⟨theta_star, h_conv_c2, h_rate_c2_zero⟩ := h_rate_c2_zero
    generalize_proofs at *; (
    -- By Lemma~\ref{lem: convergence_of_nll_and_complexity}, the per-site NML score for c1 converges to its asymptotic rate plus a complexity penalty.
    have h_nml_c1 : Filter.Tendsto (fun T => (NML U T p0 s hp0) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds (AsymptoticRate p0 s (theta_mixed B B' p0 s q) + (p0 * Fintype.card S : ℝ) / 2 * 0)) := by
      have h_nml_c1 : Filter.Tendsto (fun T => (NLL U T p0 s hp0) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds (AsymptoticRate p0 s (theta_mixed B B' p0 s q))) := by
        apply NLL_convergence U p0 s hp0 (theta_mixed B B' p0 s q) (MixedSpacetime_ConvergentFrequencies B B' p0 s q hp0 (by linarith) hB hB')
      generalize_proofs at *; (
      have h_nml_c1 : Filter.Tendsto (fun T => ((p0 * Fintype.card S : ℝ) / 2 * Real.logb 2 T) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds 0) := by
        convert Complexity_convergence p0 s hp0 using 1
        generalize_proofs at *; (
        norm_num [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm ])
      generalize_proofs at *; (
      convert ‹Filter.Tendsto ( fun T : ℕ => NLL U T p0 s hp0 / ( T * Fintype.card S : ℝ ) ) Filter.atTop ( nhds ( AsymptoticRate p0 s ( theta_mixed B B' p0 s q ) ) ) ›.add ( h_nml_c1.comp tendsto_natCast_atTop_atTop ) using 2 <;> norm_num [ NML ] ; ring!;))
    generalize_proofs at *; (
    -- By Lemma~\ref{lem: convergence_of_nll_and_complexity}, the per-site NML score for c2 converges to its asymptotic rate plus a complexity penalty.
    have h_nml_c2 : Filter.Tendsto (fun T => (NML U T (q * p0) (q • s) (by
    exact?)) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds (AsymptoticRate (q * p0) (q • s) theta_star + (q * p0 * Fintype.card S : ℝ) / 2 * 0)) := by
      have h_nml_c2 : Filter.Tendsto (fun T => (NML U T (q * p0) (q • s) (by
      exact?)) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds (AsymptoticRate (q * p0) (q • s) theta_star)) := by
        have := NML_decomposition U (q * p0) (q • s) (by
        exact?) theta_star h_conv_c2
        have h_nml_c2 : Filter.Tendsto (fun T => ((q * p0 * Fintype.card S : ℝ) / 2 * Real.logb 2 T) / (T * Fintype.card S : ℝ)) Filter.atTop (nhds 0) := by
          convert Complexity_convergence ( q * p0 ) ( q • s ) ( by positivity ) using 1
          generalize_proofs at *; (
          norm_num [ mul_assoc ])
        generalize_proofs at *; (
        have := this.add ( h_nml_c2.comp tendsto_natCast_atTop_atTop ) ; simp_all +decide [ sub_div ] ;)
      generalize_proofs at *; (
      aesop
      skip)
    generalize_proofs at *; (
    have h_nml_c1_gt_c2 : ∀ᶠ T in Filter.atTop, (NML U T p0 s hp0) / (T * Fintype.card S : ℝ) > (NML U T (q * p0) (q • s) (by
    exact?)) / (T * Fintype.card S : ℝ) := by
      exact h_nml_c1.sub h_nml_c2 |> fun h => h.eventually ( lt_mem_nhds <| by aesop ) |> fun h => h.mono fun T hT => by linarith;
    generalize_proofs at *; (
    filter_upwards [ h_nml_c1_gt_c2, Filter.eventually_gt_atTop 0 ] with T hT₁ hT₂ ; simp_all +decide [ IsNMLMinimizer ] ; (
    simp +zetaDelta at *;
    rwa [ div_lt_div_iff_of_pos_right ( by positivity ) ] at hT₁
    skip))))))))

/-
Definition of IsExactBackground.
-/
/-- Definition 5: A background is exact if all orbit classes have asymptotic frequency 0 or 1. -/
def IsExactBackground (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0) (theta_star : Fin p × S → ℝ) : Prop :=
  ConvergentFrequencies U p s hp theta_star ∧ ∀ i, theta_star i = 0 ∨ theta_star i = 1

/-
Definition of FiniteDefects.
-/
/-- U has finite defects relative to B. -/
def FiniteDefects (U B : Spacetime S) : Prop :=
  Set.Finite { pt : ℕ × S | U pt.1 pt.2 ≠ B pt.1 pt.2 }

/-
If U has finite defects relative to a relative-periodic B, then its asymptotic rate is 0.
-/
/-- Lemma: Finite defects implies zero asymptotic rate. -/
theorem FiniteDefects_Implies_Zero_Rate (U B : Spacetime S) (p : ℕ) (s : S) (hp : p > 0)
  (hB : IsRelativePeriodic B p s) (h_fin : FiniteDefects U B) :
  ∃ theta_star : Fin p × S → ℝ,
    ConvergentFrequencies U p s hp theta_star ∧ AsymptoticRate p s theta_star = 0 := by
      convert Exact_Periodicity_Implies_Zero_Rate B p s hp hB using 1;
      ext theta_star; simp +decide [ ConvergentFrequencies, AsymptoticRate ] ;
      intro h
      have h_eq : ∀ i : Fin p × S, Filter.Tendsto (fun T => (OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i)) - (OrbitCount1_idx B T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i))) Filter.atTop (nhds 0) := by
        intro i
        have h_eq : ∀ T, (OrbitCount1_idx U T p s hp i : ℝ) - (OrbitCount1_idx B T p s hp i : ℝ) = ∑ t ∈ Finset.range T, ∑ x : S, if (t, x) ∈ OrbitClass p s hp i ∧ U t x ≠ B t x then if U t x then 1 else -1 else 0 := by
          intro T
          simp [OrbitCount1_idx];
          rw [ show ( Count1 U T ( OrbitClass p s hp i ) : ℝ ) = ∑ t ∈ Finset.range T, ∑ x : S, if ( t, x ) ∈ OrbitClass p s hp i ∧ U t x = Bool.true then 1 else 0 from ?_, show ( Count1 B T ( OrbitClass p s hp i ) : ℝ ) = ∑ t ∈ Finset.range T, ∑ x : S, if ( t, x ) ∈ OrbitClass p s hp i ∧ B t x = Bool.true then 1 else 0 from ?_ ];
          · rw [ ← Finset.sum_sub_distrib ] ; congr ; ext t ; rw [ ← Finset.sum_sub_distrib ] ; congr ; ext x ; by_cases h : U t x = Bool.true <;> by_cases h' : B t x = Bool.true <;> simp +decide [ h, h' ] ;
            split_ifs <;> norm_num;
          · simp +decide [ Count1 ];
          · simp +decide [ Count1 ];
        -- Since the set of defects is finite, the sum of the differences is bounded.
        have h_bounded : ∃ C : ℝ, ∀ T, abs ((OrbitCount1_idx U T p s hp i : ℝ) - (OrbitCount1_idx B T p s hp i : ℝ)) ≤ C := by
          have h_bounded : Set.Finite {pt : ℕ × S | (pt.1, pt.2) ∈ OrbitClass p s hp i ∧ U pt.1 pt.2 ≠ B pt.1 pt.2} := by
            exact h_fin.subset fun x hx => hx.2;
          use ∑ pt ∈ h_bounded.toFinset, 1;
          intro T
          rw [h_eq T];
          refine' le_trans _ ( Finset.sum_le_sum_of_subset_of_nonneg ( show h_bounded.toFinset ⊇ Finset.filter ( fun pt => ( pt.1, pt.2 ) ∈ OrbitClass p s hp i ∧ U pt.1 pt.2 ≠ B pt.1 pt.2 ) ( Finset.product ( Finset.range T ) Finset.univ ) from _ ) fun _ _ _ => zero_le_one );
          · erw [ Finset.sum_filter ];
            erw [ Finset.sum_product ];
            exact le_trans ( Finset.abs_sum_le_sum_abs _ _ ) ( Finset.sum_le_sum fun _ _ => Finset.abs_sum_le_sum_abs _ _ |> le_trans <| Finset.sum_le_sum fun _ _ => by split_ifs <;> norm_num );
          · simp +decide [ Finset.subset_iff ];
        have h_orbit_size_growth : Filter.Tendsto (fun T => (OrbitSize T (OrbitClass p s hp i) : ℝ)) Filter.atTop Filter.atTop := by
          have h_orbit_size_growth : Filter.Tendsto (fun T => (Finset.filter (fun t => t % p = i.1.val) (Finset.range T)).card : ℕ → ℝ) Filter.atTop Filter.atTop := by
            have h_orbit_size_growth : ∀ T, (Finset.filter (fun t => t % p = i.1.val) (Finset.range T)).card ≥ T / p := by
              intro T
              have h_orbit_size_growth : Finset.filter (fun t => t % p = i.1.val) (Finset.range T) ⊇ Finset.image (fun t => t * p + i.1.val) (Finset.range (T / p)) := by
                simp +decide [ Finset.subset_iff ];
                exact fun a ha => ⟨ by nlinarith [ Nat.div_mul_le_self T p, Fin.is_lt i.1 ], Nat.mod_eq_of_lt ( Fin.is_lt i.1 ) ⟩;
              exact le_trans ( by rw [ Finset.card_image_of_injective _ fun x y hxy => by nlinarith ] ; simp +decide ) ( Finset.card_mono h_orbit_size_growth );
            exact tendsto_natCast_atTop_atTop.comp ( Filter.tendsto_atTop_mono h_orbit_size_growth ( Filter.tendsto_atTop_atTop.mpr fun x => ⟨ x * p, fun T hT => Nat.le_div_iff_mul_le hp |>.2 <| by nlinarith ⟩ ) );
          convert h_orbit_size_growth using 1;
          ext T; simp +decide [ OrbitSize_eq_Card ] ;
        exact squeeze_zero_norm ( fun T => by simpa [ ← sub_div ] using div_le_div_of_nonneg_right ( h_bounded.choose_spec T ) ( Nat.cast_nonneg _ ) ) ( tendsto_const_nhds.div_atTop h_orbit_size_growth );
      constructor <;> intro h' a b <;> specialize h_eq ( a, b ) <;> have := h_eq <;> simp_all +decide [ sub_eq_iff_eq_add ] ;
      · simpa using h' a b |> Filter.Tendsto.sub <| this;
      · simpa using this.add ( h' a b )

/-
The orbit class of a refined model is a subset of the orbit class of the base model.
-/
/-- Lemma: Orbit class inclusion under refinement. -/
theorem OrbitClass_Inclusion (p0 : ℕ) (s0 : S) (hp0 : p0 > 0)
  (m : ℕ) (hm : m > 0)
  (i : Fin (m * p0) × S) :
  let p := m * p0
  let s := m • s0
  let hp : p > 0 := mul_pos hm hp0
  let j := OrbitMap p0 s0 hp0 (i.1.val, i.2)
  OrbitClass p s hp i ⊆ OrbitClass p0 s0 hp0 j := by
    unfold OrbitClass OrbitMap;
    simp_all +decide [ Fin.ext_iff, Nat.mod_eq_of_lt ];
    rintro a b ⟨ ha, hb ⟩ ; simp_all +decide [ Fin.ext_iff, Nat.mod_eq_of_lt ] ;
    rw [ show a / p0 = ( a / ( m * p0 ) ) * m + ( a % ( m * p0 ) / p0 ) from ?_ ] ; simp +decide [ add_smul, mul_assoc, smul_smul ] ; ring;
    · rw [ sub_sub ];
    · rw [ ← Nat.div_add_mod a ( m * p0 ) ] ; ring_nf; norm_num [ Nat.add_div, Nat.mul_div_assoc, hp0, hm ] ;
      split_ifs <;> simp_all +decide [ Nat.mul_assoc, Nat.mul_div_assoc, Nat.mod_eq_of_lt ] ; ring;
      · linarith [ Nat.mod_lt a ( by positivity : 0 < m * p0 ) ];
      · norm_num [ Nat.add_mod, Nat.mul_mod ] at * ; linarith [ Nat.mod_lt a hp0 ];
      · linarith [ Nat.mod_lt a ( by positivity : 0 < m * p0 ) ]

/-
If the asymptotic rate is 0 and frequencies are in [0, 1], then every theta_star i is 0 or 1.
-/
/-- Lemma: Zero rate implies pure frequencies (with bounds). -/
theorem Zero_Rate_Implies_Pure_Frequencies (p : ℕ) (s : S) (theta_star : Fin p × S → ℝ)
  (h_bounds : ∀ i, 0 ≤ theta_star i ∧ theta_star i ≤ 1)
  (h_rate : AsymptoticRate p s theta_star = 0) :
  ∀ i, theta_star i = 0 ∨ theta_star i = 1 := by
    contrapose! h_rate; simp_all +decide [ AsymptoticRate ] ;
    obtain ⟨ a, b, ha, hb ⟩ := h_rate; rw [ Finset.sum_eq_add_sum_diff_singleton ( Finset.mem_univ ( a, b ) ) ] ; exact ⟨ by linarith [ Fin.is_lt a ], ne_of_gt ( add_pos_of_pos_of_nonneg ( Real.binEntropy_pos ( lt_of_le_of_ne ( h_bounds a b |>.1 ) ( Ne.symm ha ) ) ( lt_of_le_of_ne ( h_bounds a b |>.2 ) hb ) ) ( Finset.sum_nonneg fun x hx => Real.binEntropy_nonneg ( h_bounds x.1 x.2 |>.1 ) ( h_bounds x.1 x.2 |>.2 ) ) ) ⟩ ;

/-
Convergent frequencies are always in the interval [0, 1].
-/
/-- Lemma: Convergent frequencies are in [0, 1]. -/
theorem ConvergentFrequencies_Bounds (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0) (theta_star : Fin p × S → ℝ)
  (h_conv : ConvergentFrequencies U p s hp theta_star) :
  ∀ i, 0 ≤ theta_star i ∧ theta_star i ≤ 1 := by
    intro i
    have h_counts : ∀ T, 0 ≤ (OrbitCount1_idx U T p s hp i : ℝ) ∧ (OrbitCount1_idx U T p s hp i : ℝ) ≤ (OrbitSize T (OrbitClass p s hp i)) := by
      intro T
      simp [OrbitCount1_idx, OrbitSize];
      norm_cast;
      refine' Finset.sum_le_sum fun t ht => _;
      simp +decide [ Finset.sum_ite ];
      exact Finset.card_le_card fun x hx => by aesop;
    have := h_conv i;
    exact ⟨ le_of_tendsto_of_tendsto' tendsto_const_nhds this fun T => div_nonneg ( h_counts T |>.1 ) ( Nat.cast_nonneg _ ), le_of_tendsto_of_tendsto' this tendsto_const_nhds fun T => div_le_one_of_le₀ ( h_counts T |>.2 ) ( Nat.cast_nonneg _ ) ⟩

/-
The number of t < T with t % p = r is between T/p - 1 and T/p + 1.
-/
/-- Lemma: Bounds on the cardinality of the residue class. -/
theorem Card_Mod_Bounds (p : ℕ) (r : ℕ) (hp : p > 0) (hr : r < p) (T : ℕ) :
  (T : ℝ) / p - 1 ≤ (Finset.filter (fun t => t % p = r) (Finset.range T)).card ∧
  (Finset.filter (fun t => t % p = r) (Finset.range T)).card ≤ (T : ℝ) / p + 1 := by
    let S_T := Finset.filter (fun t => t % p = r) (Finset.range T)
    constructor
    · -- Lower bound
      -- The elements are r, r+p, r+2p, ..., r+k*p < T.
      -- k*p < T - r. k <= (T - r - 1) / p.
      -- The number of elements is floor((T - r - 1)/p) + 1 if T > r.
      -- If T <= r, count is 0. T/p - 1 <= 0 is true if T <= p.
      -- Let's use a rougher bound.
      -- We know the count is at least T/p - 1.
      -- Consider the mapping f(k) = k*p + r.
      -- This maps {0, ..., floor(T/p) - 1} into range T?
      -- If k < T/p - 1, then k <= T/p - 2.
      -- k*p + r <= (T/p - 2)*p + r = T - 2p + r < T - p < T.
      -- So at least floor(T/p) - 1 elements are there.
      -- floor(T/p) - 1 >= T/p - 2.
      -- This is getting messy.
      -- Let's use the fact that the gap between elements is p.
      -- So in any interval of length T, the count is between T/p - 1 and T/p + 1.
      rw [ le_iff_lt_or_eq ];
      refine' lt_or_eq_of_le ( le_trans _ <| Nat.cast_le.mpr <| Finset.card_mono <| show Finset.image ( fun q => q * p + r ) ( Finset.range ( T / p ) ) ⊆ Finset.filter ( fun t => t % p = r ) ( Finset.range T ) from _ );
      · rw [ Finset.card_image_of_injective ] <;> norm_num [ Function.Injective, hp.ne' ];
        rw [ div_le_iff₀ ] <;> norm_cast ; linarith [ Nat.div_add_mod T p, Nat.mod_lt T hp ];
      · exact Finset.image_subset_iff.mpr fun q hq => Finset.mem_filter.mpr ⟨ Finset.mem_range.mpr <| by nlinarith [ Nat.div_mul_le_self T p, Finset.mem_range.mp hq ], by norm_num [ Nat.add_mod, Nat.mod_eq_of_lt hr ] ⟩
    · -- Upper bound
      rw [ div_add_one, le_div_iff₀ ] <;> norm_cast;
      · -- The set $S_T$ is a subset of $\{t \in \mathbb{N} \mid t \equiv r \pmod{p}\}$, which has cardinality $\lfloor T/p \rfloor + 1$.
        have h_card_subset : S_T ⊆ Finset.image (fun k => k * p + r) (Finset.range (T / p + 1)) := by
          exact fun x hx => Finset.mem_image.mpr ⟨ x / p, Finset.mem_range.mpr ( Nat.lt_succ_of_le ( Nat.div_le_div_right ( Finset.mem_range_le ( Finset.mem_filter.mp hx |>.1 ) ) ) ), by linarith [ Nat.mod_add_div x p, Finset.mem_filter.mp hx |>.2 ] ⟩;
        exact le_trans ( Nat.mul_le_mul_right _ ( Finset.card_le_card h_card_subset ) ) ( by rw [ Finset.card_image_of_injective ] <;> norm_num [ Function.Injective, hp.ne' ] ; nlinarith [ Nat.div_mul_le_self T p ] );
      · linarith

/-
The density of numbers congruent to r mod p is 1/p.
-/
/-- Lemma: The density of numbers congruent to r mod p is 1/p. -/
theorem Card_Mod_Asymptotic (p : ℕ) (r : ℕ) (hp : p > 0) (hr : r < p) :
  Filter.Tendsto (fun T => ((Finset.filter (fun t => t % p = r) (Finset.range T)).card : ℝ) / T) Filter.atTop (nhds (1 / (p : ℝ))) := by
    have := @Card_Mod_Bounds p r hp hr;
    -- By dividing the inequalities in `this` by `T`, we can apply the squeeze theorem.
    have h_squeeze : Filter.Tendsto (fun T : ℕ => ((T : ℝ) / p - 1) / T) Filter.atTop (nhds (1 / p)) ∧ Filter.Tendsto (fun T : ℕ => ((T : ℝ) / p + 1) / T) Filter.atTop (nhds (1 / p)) := by
      ring_nf;
      exact ⟨ by simpa using Filter.Tendsto.sub ( tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with T hT; simp +decide [ mul_comm, hT ] ) ) ( tendsto_inverse_atTop_nhds_zero_nat ), by simpa using Filter.Tendsto.add ( tendsto_const_nhds.congr' ( by filter_upwards [ Filter.eventually_ne_atTop 0 ] with T hT; simp +decide [ mul_comm, hT ] ) ) ( tendsto_inverse_atTop_nhds_zero_nat ) ⟩;
    exact tendsto_of_tendsto_of_tendsto_of_le_of_le h_squeeze.1 h_squeeze.2 ( fun T => div_le_div_of_nonneg_right ( this T |>.1 ) ( Nat.cast_nonneg _ ) ) ( fun T => div_le_div_of_nonneg_right ( this T |>.2 ) ( Nat.cast_nonneg _ ) )

/-
OrbitSize / T converges to 1/p.
-/
/-- Lemma: OrbitSize / T converges to 1/p. -/
theorem OrbitSize_Asymptotic (p : ℕ) (s : S) (hp : p > 0) (i : Fin p × S) :
  Filter.Tendsto (fun T => (OrbitSize T (OrbitClass p s hp i) : ℝ) / T) Filter.atTop (nhds (1 / (p : ℝ))) := by
    simp only [OrbitSize_eq_Card]
    exact Card_Mod_Asymptotic p i.1.val hp i.1.is_lt

/-
If the base frequency converges to 0, the refined frequency converges to 0.
-/
/-- Lemma: Convergence to 0 for refined orbit class. -/
theorem Refinement_Convergence_Zero (U : Spacetime S) (p0 : ℕ) (s0 : S) (hp0 : p0 > 0)
  (m : ℕ) (hm : m > 0)
  (i : Fin (m * p0) × S)
  (j : Fin p0 × S) (hj : j = OrbitMap p0 s0 hp0 (i.1.val, i.2))
  (h_conv_0 : Filter.Tendsto (fun T => (OrbitCount1_idx U T p0 s0 hp0 j : ℝ) / (OrbitSize T (OrbitClass p0 s0 hp0 j))) Filter.atTop (nhds 0)) :
  let p := m * p0
  let s := m • s0
  let hp : p > 0 := mul_pos hm hp0
  Filter.Tendsto (fun T => (OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i))) Filter.atTop (nhds 0) := by
    contrapose! h_conv_0;
    -- Since the orbit class of the refined model is a subset of the orbit class of the base model, and the refined model's frequency is not zero, the base model's frequency can't be zero either.
    have h_subset : ∀ T, OrbitCount1_idx U T (m * p0) (m • s0) (mul_pos hm hp0) i ≤ OrbitCount1_idx U T p0 s0 hp0 j := by
      unfold OrbitCount1_idx;
      intro T
      simp [Count1, hj];
      gcongr with x hx;
      exact fun y hy => ⟨ OrbitClass_Inclusion p0 s0 hp0 m hm i hy.1, hy.2 ⟩;
    intro H;
    refine' h_conv_0 ( squeeze_zero ( fun T => by positivity ) ( fun T => div_le_div_of_nonneg_right ( Nat.cast_le.mpr ( h_subset T ) ) ( Nat.cast_nonneg _ ) ) _ );
    have h_orbit_size : Filter.Tendsto (fun T => (OrbitSize T (OrbitClass (m * p0) (m • s0) (mul_pos hm hp0) i) : ℝ) / (OrbitSize T (OrbitClass p0 s0 hp0 j) : ℝ)) Filter.atTop (nhds (1 / (m : ℝ))) := by
      have h_orbit_size : Filter.Tendsto (fun T => (OrbitSize T (OrbitClass (m * p0) (m • s0) (mul_pos hm hp0) i) : ℝ) / T) Filter.atTop (nhds (1 / (m * p0 : ℝ))) ∧ Filter.Tendsto (fun T => (OrbitSize T (OrbitClass p0 s0 hp0 j) : ℝ) / T) Filter.atTop (nhds (1 / (p0 : ℝ))) := by
        exact ⟨ by simpa using OrbitSize_Asymptotic ( m * p0 ) ( m • s0 ) ( mul_pos hm hp0 ) i, by simpa using OrbitSize_Asymptotic p0 s0 hp0 j ⟩;
      have := h_orbit_size.1.div h_orbit_size.2; simp_all +decide [ division_def ] ;
      simpa [ mul_assoc, mul_comm, mul_left_comm, hp0.ne' ] using this hp0.ne' |> fun h => h.congr' ( by filter_upwards [ Filter.eventually_gt_atTop 0 ] with T hT using by simp +decide [ mul_assoc, mul_comm, mul_left_comm, hT.ne' ] );
    have := H.div h_orbit_size; simp_all +decide [ division_def ] ;
    refine' this hm.ne' |> fun h => h.congr' _;
    filter_upwards [ h_orbit_size.eventually_ne ( by positivity : ( m : ℝ ) ⁻¹ ≠ 0 ) ] with T hT ; simp_all +decide [ mul_assoc, mul_comm, mul_left_comm ] ;

/-
If the base frequency converges to 1, the refined frequency converges to 1.
-/
/-- Lemma: Convergence to 1 for refined orbit class. -/
theorem Refinement_Convergence_One (U : Spacetime S) (p0 : ℕ) (s0 : S) (hp0 : p0 > 0)
  (m : ℕ) (hm : m > 0)
  (i : Fin (m * p0) × S)
  (j : Fin p0 × S) (hj : j = OrbitMap p0 s0 hp0 (i.1.val, i.2))
  (h_conv_1 : Filter.Tendsto (fun T => (OrbitCount1_idx U T p0 s0 hp0 j : ℝ) / (OrbitSize T (OrbitClass p0 s0 hp0 j))) Filter.atTop (nhds 1)) :
  let p := m * p0
  let s := m • s0
  let hp : p > 0 := mul_pos hm hp0
  Filter.Tendsto (fun T => (OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i))) Filter.atTop (nhds 1) := by
    -- By replacing $U$ with $flip U$ (flipping all values), we can reduce the problem to the case where the base frequency tends to 0.
    set U' : Spacetime S := fun t x => !U t x;
    -- By definition of $U'$, we know that $U'$ converges to $0$.
    have h_U'_conv : Filter.Tendsto (fun T => (OrbitCount1_idx U' T p0 s0 hp0 j : ℝ) / (OrbitSize T (OrbitClass p0 s0 hp0 j))) Filter.atTop (nhds 0) := by
      have h_U'_conv : ∀ T, (OrbitCount1_idx U' T p0 s0 hp0 j : ℝ) = (OrbitSize T (OrbitClass p0 s0 hp0 j) : ℝ) - (OrbitCount1_idx U T p0 s0 hp0 j : ℝ) := by
        intro T; rw [ eq_sub_iff_add_eq ] ; norm_cast; simp +decide [ OrbitCount1_idx, OrbitSize ] ;
        unfold Count1; simp +decide [ Finset.sum_add_distrib ] ;
        rw [ ← Finset.sum_add_distrib ] ; congr ; ext x ; rw [ ← Finset.card_union_of_disjoint ] ; congr ; ext y ; by_cases hy : U x y <;> aesop;
        exact Finset.disjoint_filter.mpr fun _ _ _ _ => by aesop;
      simp_all +decide [ sub_div ];
      rw [ Filter.tendsto_congr' ( by filter_upwards [ h_conv_1.eventually_ne one_ne_zero ] with T hT using by rw [ div_self <| by aesop ] ) ] ; simpa using h_conv_1.const_sub 1;
    -- By definition of $U'$, we know that $U'$ converges to $0$ for the refined model.
    have h_U'_conv_refined : Filter.Tendsto (fun T => (OrbitCount1_idx U' T (m * p0) (m • s0) (mul_pos hm hp0) i : ℝ) / (OrbitSize T (OrbitClass (m * p0) (m • s0) (mul_pos hm hp0) i))) Filter.atTop (nhds 0) := by
      convert Refinement_Convergence_Zero U' p0 s0 hp0 m hm i j hj h_U'_conv using 1;
    -- By definition of $U'$, we know that $U'$ converges to $0$ for the refined model, which implies that $U$ converges to $1$.
    have h_U_conv_refined : ∀ T, (OrbitCount1_idx U T (m * p0) (m • s0) (mul_pos hm hp0) i : ℝ) + (OrbitCount1_idx U' T (m * p0) (m • s0) (mul_pos hm hp0) i : ℝ) = (OrbitSize T (OrbitClass (m * p0) (m • s0) (mul_pos hm hp0) i)) := by
      intro T
      simp [OrbitCount1_idx, OrbitSize];
      norm_cast
      simp [Count1];
      rw [ ← Finset.sum_add_distrib ] ; refine' Finset.sum_congr rfl fun x hx => _ ; rw [ ← Finset.card_union_of_disjoint ] ; congr ; ext y ; by_cases hy : U x y <;> aesop;
      exact Finset.disjoint_filter.mpr fun _ _ _ _ => by aesop;
    have h_U_conv_refined : Filter.Tendsto (fun T => (OrbitSize T (OrbitClass (m * p0) (m • s0) (mul_pos hm hp0) i) : ℝ) / (OrbitSize T (OrbitClass (m * p0) (m • s0) (mul_pos hm hp0) i))) Filter.atTop (nhds 1) := by
      refine' tendsto_const_nhds.congr' _;
      filter_upwards [ Filter.eventually_gt_atTop ( i.1.val + 1 ) ] with T hT;
      rw [ div_self ];
      norm_cast;
      rw [ OrbitSize_eq_Card ];
      exact ne_of_gt ( Finset.card_pos.mpr ⟨ i.1, Finset.mem_filter.mpr ⟨ Finset.mem_range.mpr ( by linarith ), Nat.mod_eq_of_lt ( by linarith [ Fin.is_lt i.1 ] ) ⟩ ⟩ );
    convert h_U_conv_refined.sub h_U'_conv_refined using 2 <;> ring;
    grind

/-
The orbit count of 1s in the flipped spacetime is the orbit size minus the orbit count of 1s in the original spacetime.
-/
/-- Lemma: Orbit count of flipped spacetime. -/
theorem OrbitCount_Flip (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0) (i : Fin p × S) (T : ℕ) :
  OrbitCount1_idx (fun t x => !U t x) T p s hp i = OrbitSize T (OrbitClass p s hp i) - OrbitCount1_idx U T p s hp i := by
    refine' eq_tsub_of_add_eq _;
    unfold OrbitCount1_idx OrbitSize;
    unfold Count1;
    rw [ ← Finset.sum_add_distrib ] ; congr ; ext t ; rw [ ← Finset.sum_add_distrib ] ; congr ; ext x ; by_cases h : U t x <;> simp +decide [ h ] ;

/-
Refinement of a zero-rate model also has zero rate.
-/
/-- Lemma: Refinement of a zero-rate model also has zero rate. -/
theorem Refinement_Zero_Rate (U : Spacetime S) (p0 : ℕ) (s0 : S) (hp0 : p0 > 0)
  (m : ℕ) (hm : m > 0)
  (theta_star_0 : Fin p0 × S → ℝ)
  (h_conv_0 : ConvergentFrequencies U p0 s0 hp0 theta_star_0)
  (h_rate_0 : AsymptoticRate p0 s0 theta_star_0 = 0) :
  let p := m * p0
  let s := m • s0
  let hp : p > 0 := mul_pos hm hp0
  ∃ theta_star : Fin p × S → ℝ,
    ConvergentFrequencies U p s hp theta_star ∧ AsymptoticRate p s theta_star = 0 := by
      -- By definition of asymptotic rate, if the base period model has an asymptotic rate of zero, then for every orbit class i, the frequency of 1s converges to either 0 or 1.
      have h_orbit_classes : ∀ i : Fin p0 × S, theta_star_0 i = 0 ∨ theta_star_0 i = 1 := by
        apply Zero_Rate_Implies_Pure_Frequencies;
        exacts [ fun i => ConvergentFrequencies_Bounds U p0 s0 hp0 theta_star_0 h_conv_0 i, h_rate_0 ];
      -- By definition of asymptotic rate, if the base period model has an asymptotic rate of zero, then for every orbit class i, the frequency of 1s converges to either 0 or 1. Therefore, the refined model's frequencies will also converge to 0 or 1.
      have h_refined_frequencies : ∀ i : Fin (m * p0) × S, let p := m * p0; let s := m • s0; let hp : p > 0 := mul_pos hm hp0; Filter.Tendsto (fun T => (OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i))) Filter.atTop (nhds (if theta_star_0 (OrbitMap p0 s0 hp0 (i.1.val, i.2)) = 0 then 0 else 1)) := by
        intro i
        by_cases h : theta_star_0 (OrbitMap p0 s0 hp0 (i.1.val, i.2)) = 0;
        · have := h_conv_0 (OrbitMap p0 s0 hp0 (i.1.val, i.2));
          convert Refinement_Convergence_Zero U p0 s0 hp0 m hm i ( OrbitMap p0 s0 hp0 ( i.1.val, i.2 ) ) rfl _ using 1 ; aesop;
          aesop;
        · have h_refined_frequencies : Filter.Tendsto (fun T => (OrbitCount1_idx U T p0 s0 hp0 (OrbitMap p0 s0 hp0 (i.1.val, i.2)) : ℝ) / (OrbitSize T (OrbitClass p0 s0 hp0 (OrbitMap p0 s0 hp0 (i.1.val, i.2)))) ) Filter.atTop (nhds 1) := by
            convert h_conv_0 ( OrbitMap p0 s0 hp0 ( i.1.val, i.2 ) ) using 1;
            grind;
          convert Refinement_Convergence_One U p0 s0 hp0 m hm i ( OrbitMap p0 s0 hp0 ( i.1.val, i.2 ) ) rfl h_refined_frequencies using 1 ; aesop;
      refine' ⟨ fun i => if theta_star_0 ( OrbitMap p0 s0 hp0 ( i.1.val, i.2 ) ) = 0 then 0 else 1, _, _ ⟩ <;> simp_all +decide [ ConvergentFrequencies ];
      unfold AsymptoticRate; simp +decide [ Finset.sum_ite ] ;
      rw [ Finset.sum_eq_zero ] ; aesop;
      intro x hx; split_ifs <;> simp +decide [ *, Real.binEntropy ] ;

/-
If orbit class A is a subset of B, then Count1(A) <= Count1(B).
-/
/-- Lemma: OrbitCount1 monotonicity under inclusion. -/
theorem OrbitCount1_Inclusion (U : Spacetime S) (T : ℕ) (A B : Set (ℕ × S)) (h : A ⊆ B) :
  Count1 U T A ≤ Count1 U T B := by
    refine' Finset.sum_le_sum fun t ht => Finset.sum_le_sum fun x hx => _;
    grind

/-
If base frequencies converge to 0 or 1, refined frequencies converge to the same.
-/
/-- Lemma: Convergence of refined frequencies given pure base frequencies. -/
theorem Refinement_Convergence (U : Spacetime S) (p0 : ℕ) (s0 : S) (hp0 : p0 > 0)
  (m : ℕ) (hm : m > 0)
  (theta_star_0 : Fin p0 × S → ℝ)
  (h_conv_0 : ConvergentFrequencies U p0 s0 hp0 theta_star_0)
  (h_pure_0 : ∀ j, theta_star_0 j = 0 ∨ theta_star_0 j = 1) :
  let p := m * p0
  let s := m • s0
  let hp : p > 0 := mul_pos hm hp0
  let theta_star := fun (i : Fin p × S) => theta_star_0 (OrbitMap p0 s0 hp0 (i.1.val, i.2))
  ConvergentFrequencies U p s hp theta_star := by
    -- By definition of `ConvergentFrequencies`, we know that for any `i`, the ratio of the number of ones in the orbit of `i` to the size of the orbit converges to `theta_star_0 i`.
    have h_conv : ∀ i : Fin (m * p0) × S, Filter.Tendsto (fun T => (OrbitCount1_idx U T (m * p0) (m • s0) (mul_pos hm hp0) i : ℝ) / (OrbitSize T (OrbitClass (m * p0) (m • s0) (mul_pos hm hp0) i))) Filter.atTop (nhds (theta_star_0 (OrbitMap p0 s0 hp0 (i.1.val, i.2)))) := by
      intro i
      by_cases h : theta_star_0 (OrbitMap p0 s0 hp0 (i.1.val, i.2)) = 0 ∨ theta_star_0 (OrbitMap p0 s0 hp0 (i.1.val, i.2)) = 1;
      · cases' h with h h;
        · convert Refinement_Convergence_Zero U p0 s0 hp0 m hm i ( OrbitMap p0 s0 hp0 ( i.1.val, i.2 ) ) rfl _ using 1;
          · rw [ h ];
          · simpa [ h ] using h_conv_0 ( OrbitMap p0 s0 hp0 ( i.1.val, i.2 ) );
        · convert Refinement_Convergence_One U p0 s0 hp0 m hm i ( OrbitMap p0 s0 hp0 ( i.1.val, i.2 ) ) rfl _ using 1;
          · rw [ h ];
          · simpa [ h ] using h_conv_0 ( OrbitMap p0 s0 hp0 ( i.1.val, i.2 ) );
      · exact False.elim ( h ( h_pure_0 _ ) );
    exact h_conv

/-
If orbit class A is a subset of B, then Count0(A) <= Count0(B).
-/
/-- Lemma: OrbitCount0 monotonicity under inclusion. -/
theorem OrbitCount0_Inclusion (U : Spacetime S) (T : ℕ) (A B : Set (ℕ × S)) (h : A ⊆ B) :
  Count0 U T A ≤ Count0 U T B := by
    refine' Finset.sum_le_sum fun t ht => Finset.sum_le_sum fun x hx => _;
    grind +ring

/-
If orbit class A is a subset of B, then Count0(A) <= Count0(B).
-/
/-- Lemma: OrbitCount0 monotonicity under inclusion. -/
theorem OrbitCount0_Inclusion_v2 (U : Spacetime S) (T : ℕ) (A B : Set (ℕ × S)) (h : A ⊆ B) :
  Count0 U T A ≤ Count0 U T B := by
    unfold Count0
    refine' Finset.sum_le_sum fun t ht => Finset.sum_le_sum fun x hx => _
    split_ifs with h1 h2
    · rfl
    · rcases h1 with ⟨hA, hU⟩
      have hB := h hA
      have : (t, x) ∈ B ∧ U t x = false := ⟨hB, hU⟩
      contradiction
    · exact zero_le_one
    · rfl

/-
If the base frequency converges to 1, the refined frequency converges to 1.
-/
/-- Lemma: Convergence to 1 for refined orbit class. -/
theorem Refinement_Convergence_One_v2 (U : Spacetime S) (p0 : ℕ) (s0 : S) (hp0 : p0 > 0)
  (m : ℕ) (hm : m > 0)
  (i : Fin (m * p0) × S)
  (j : Fin p0 × S) (hj : j = OrbitMap p0 s0 hp0 (i.1.val, i.2))
  (h_conv_1 : Filter.Tendsto (fun T => (OrbitCount1_idx U T p0 s0 hp0 j : ℝ) / (OrbitSize T (OrbitClass p0 s0 hp0 j))) Filter.atTop (nhds 1)) :
  let p := m * p0
  let s := m • s0
  let hp : p > 0 := mul_pos hm hp0
  Filter.Tendsto (fun T => (OrbitCount1_idx U T p s hp i : ℝ) / (OrbitSize T (OrbitClass p s hp i))) Filter.atTop (nhds 1) := by
    convert Refinement_Convergence_One U p0 s0 hp0 m hm i j hj h_conv_1 using 1

#check OrbitCount0_Inclusion

/-
OrbitCount0(U) = OrbitCount1(!U).
-/
/-- Lemma: OrbitCount0 equals OrbitCount1 of flipped spacetime. -/
theorem OrbitCount0_eq_OrbitCount1_Flip (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0) (i : Fin p × S) (T : ℕ) :
  OrbitCount0_idx U T p s hp i = OrbitCount1_idx (fun t x => !U t x) T p s hp i := by
    -- By definition of OrbitCount0_idx and OrbitCount1_idx, we can rewrite the goal in terms of sums over the orbit class.
    simp [OrbitCount0_idx, OrbitCount1_idx];
    unfold Count0 Count1; aesop;

/-
OrbitCount1 + OrbitCount0 = OrbitSize.
-/
/-- Lemma: OrbitCount1 + OrbitCount0 = OrbitSize. -/
theorem OrbitCount_Sum (U : Spacetime S) (p : ℕ) (s : S) (hp : p > 0) (i : Fin p × S) (T : ℕ) :
  (OrbitCount1_idx U T p s hp i : ℝ) + (OrbitCount0_idx U T p s hp i : ℝ) = (OrbitSize T (OrbitClass p s hp i) : ℝ) := by
    unfold OrbitCount1_idx OrbitCount0_idx OrbitSize;
    simp +decide only [Count1, Count0];
    push_cast [ ← Finset.sum_add_distrib ];
    exact Finset.sum_congr rfl fun x hx => Finset.sum_congr rfl fun y hy => by cases U x y <;> simp +decide [ * ] ;

/-
The number of t < T with t % p = r is (T - r - 1) / p + 1 if T > r, else 0.
-/
theorem count_mod_eq (p : ℕ) (r : ℕ) (hp : p > 0) (hr : r < p) (T : ℕ) :
  (Finset.filter (fun t => t % p = r) (Finset.range T)).card = if T > r then (T - r - 1) / p + 1 else 0 := by
    split_ifs;
    · rw [ Finset.card_eq_of_bijective ];
      use fun i hi => r + i * p;
      · simp +zetaDelta at *;
        exact fun a ha ha' => ⟨ a / p, Nat.lt_succ_of_le ( Nat.le_div_iff_mul_le hp |>.2 <| Nat.le_sub_of_add_le <| Nat.le_sub_of_add_le <| by linarith [ Nat.mod_add_div a p ] ), by linarith [ Nat.mod_add_div a p ] ⟩;
      · simp +zetaDelta at *;
        exact fun i hi => ⟨ by nlinarith [ Nat.div_mul_le_self ( T - r - 1 ) p, Nat.sub_add_cancel ( show r ≤ T from by linarith ), Nat.sub_add_cancel ( show 1 ≤ T - r from Nat.sub_pos_of_lt ‹_› ) ], Nat.mod_eq_of_lt hr ⟩;
      · aesop;
    · exact Finset.card_eq_zero.mpr ( Finset.filter_eq_empty_iff.mpr fun x hx => by linarith [ Finset.mem_range.mp hx, Nat.mod_eq_of_lt ( show x < p from by linarith [ Finset.mem_range.mp hx ] ) ] )

#check Refinement_Convergence_One